### ISSUE TITLE
go-flutter-desktop 无法播放视频

### ISSUE THREAD

**Issue by gwuhaolin** [befovy/fijkplayer#110]
在mac系统下去本项目example目录下执行 hover run 后播放视频黑屏。

**Comment by befovy** [comment]
可以提供日志吗？ 是整个 App黑屏还是视频画面黑屏？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by gwuhaolin** [comment]
视频黑屏，就是你这个项目的master分支里的example目录下的项目

**Comment by befovy** [comment]
你好，请提供日志。@gwuhaolin
