### ISSUE TITLE
[BUG]拖动进度条放手后进度跳动问题

### ISSUE THREAD

**Issue by luckysmg** [befovy/fijkplayer#113]
比如我拖到00：23放手，然后他会到00：20,我拖到1：20放手，他会调到1：16，反正就是会慢几秒

复现：
直接用你们那个基本示例都会出现

版本：
0.2.1

手机以及操作系统：
iPhoneX iOS 13.2
P30 Pro Android 10

**Comment by befovy** [comment]
我更新了 master 分支，你可以再试一下。
seek 不准确是因为 默认seek操作只能跳转到关键帧位置。 而视频中关键帧间隔太大。

加上这个选项应该可以解决此问题。
```dart
await player.setOption(FijkOption.playerCategory, "enable-accurate-seek", 1); 
```

**Comment by luckysmg** [comment]
这个的确可以解决seek精确度的问题，但是跳转缓冲非常慢。。。。。。。。

**Comment by befovy** [comment]
> 这个的确可以解决seek精确度的问题，但是跳转缓冲非常慢。。。。。。。。

是收的 m3u8 流吗？ 如果是的话， m3u8 seek 的时候要读去多个ts分片，是会慢一些
