### ISSUE TITLE
[BUG]退出全屏后，界面排版乱了

### ISSUE THREAD

**Issue by JiangJuHong** [befovy/fijkplayer#115]
如下两张图分别全屏前和点击全屏后，期间没有收到任何错误日志。
我在两天设备上都进行了测试，其中 小米8(Android 10) 一定会出现错误，iPhone11 有一定几率出现错误!
![image](https://user-images.githubusercontent.com/17740963/69476817-a09f7f00-0e19-11ea-9f9d-2ca4b6f3c9c8.png)
![image](https://user-images.githubusercontent.com/17740963/69476819-a39a6f80-0e19-11ea-891e-d1090bdb92e3.png)

**Comment by befovy** [comment]
UI 中布局是否依赖获取当前屏幕的高度和宽度信息？
全屏后宽和高变了，再回来是否刷新重新获取宽后高？

**Comment by JiangJuHong** [comment]
是的，它正是这个原因造成的，但是那一个解决方案不适用于我，我需要自适应和全屏都起作用，我正在尝试找出新的解决办法。解决后我将第一时间上来回答。

**Comment by JiangJuHong** [comment]
请问有没有办法可以监听到全屏退出后事件（完全退出恢复到正常后），我通过 player.addListener 方法，只能监听到退出全屏之前

**Comment by befovy** [comment]
全屏状态目前只能在 `player.addListener` 中监听 `value.fullScreen` 变量的值。

主要代码在，退出全屏有两种方式，一种  `value.fullScreen` 先变化再退出全屏，另一种是先退全屏， `value.fullScreen` 后发生变化。
https://github.com/befovy/fijkplayer/blob/master/lib/core/fijkview.dart#L186
https://github.com/befovy/fijkplayer/blob/master/lib/core/fijkview.dart#L226

如果有什么好的方案，欢迎提出来或者发起 pull request。 @JiangJuHong

**Comment by JiangJuHong** [comment]
我发现通过在整个页面  this.setState 有助于解决这个问题，但是无理由重新渲染总是不好的。我不知道全屏的工作原理，但是如果可以的话，我更倾向于全屏后不影响现有组件，例如Flutter 中的 Stack Widget，我不清楚是否能够通过这种方式进行改善？ @befovy

**Comment by befovy** [comment]
@JiangJuHong 你好，说一下我个人观点。

1. 全屏修改了屏幕方向，这是一个很大的屏幕UI 变动， setState 是有必要的，不是无理由的。
2. fijkplayer 默认支持全屏的方式用了  `Navigator push` 添加了新页面，退出全屏是 pop 此页面并返回之前页面。 我计划给 FijkView 增加一个参数，不响应 fullScreen 变化。用户可以实现自己的全屏效果。
3. 在 FIjkView 新增参数不响应 fullScreen 之前，用户仍旧可以自己实现全屏效果。前提是不要调用 enterFullScreen 和 exitFullScreen 接口。
4. 你提到的 Stack 实现全屏我没有仔细研究过，可以作为用户实现自定义全屏的一种思路。

**Comment by JiangJuHong** [comment]
感谢你的帮助 @befovy
