### ISSUE TITLE
ListView里使用它

### ISSUE THREAD

**Issue by JamesGZM** [befovy/fijkplayer#117]
我在PageView+ListView的环境下使用FijkPlayer 
我当时是有2种思路
1.一个 PageView持有一个Player 对象 
2.ListView中Item单独持有一个Player对象（多了会直接闪退）
但是在构建列表视频中还是碰到了各种问题 
想问下作者，看看能不能出一个ListView使用的demo，

**Comment by befovy** [comment]
谢谢你的建议，我会在后面版本中增加 ListView 中使用 播放器的 dmeo

**Comment by befovy** [comment]
@JamesGZM hi， 我尝试加了一个在 ListView 中使用的 demo，可以看上面的提交。有任何问题欢迎继续交流

**Comment by JamesGZM** [comment]
好的

**Comment by JamesGZM** [comment]
列表静音会有问题 @befovy  具体表现是静音第一个第二个也静音了 但是图标没有变化

**Comment by befovy** [comment]
@JamesGZM  不会的呀，其中一个播放器静音，不会影响其他播放器的音量。
是不是已经播放结束了？

**Comment by JamesGZM** [comment]
emm 不好意思 是我弄错了 有一个视频没有声音

**Comment by befovy** [comment]
如果你的 list 太长的话，当视频滑到屏幕之外，还是应该把播放器资源释放掉。否则，内存可能不够。

**Comment by JamesGZM** [comment]
我尝试一下

**Comment by JamesGZM** [comment]
我现在是视频滑动到可视范围之外 release掉 视频滑动到可视范围之内 只能先 reset 再 setDataSource 吗

**Comment by befovy** [comment]
不，一旦调用了 release ，就不能在调用别的接口了。

两种方法：
1、滑动到屏幕之外时调用 release，再滑动回来需要重新创建播放器，setDataSource，seek 到之前的进度，并且 **新的播放器要重新设置给 FijkView** 。
2、滑动到屏幕之外时调用 stop， reset，再滑动回来重新调用 setDataSource， 并且seek 之前的进度。

**Comment by JamesGZM** [comment]
我使用 SliverChildBuilderDelegate 监听列表可见视频和不可见视频Item 采取你说的2种方案 我用第一个方法 重新创建好像创建不了 第二个方法是可以的 ；
**新的播放器要重新设置给 FijkView 。** 这个在我的多类型列表里需要怎么实现呢 我按照你的demo是创建了一个map存players对象 item我是初始化判断是不是视频类型的在去创建palyer对象并且赋值给item那种 我得怎么重新设置

**Comment by befovy** [comment]
如果你用我说的方法2， 就没有新的播放器，播放器还是旧的。
不需要 “新的播放器要重新设置给 FijkView ”  @JamesGZM

**Comment by befovy** [comment]
可以把 SliverChildBuilderDelegate 监听列表是否可见的内容 ，贡献一下 pr 吗？ 谢谢

**Comment by JamesGZM** [comment]
好的

**Comment by JamesGZM** [comment]
我会在拷贝一份你的listview界面单独出一个界面实现这个功能

**Comment by JamesGZM** [comment]
#124 @befovy  已经提交pr 还是有点问题 比如说autopaly不能设置为true这种

**Comment by GanZhiXiong** [comment]
@JamesGZM  能不能显示个封面啊？

**Comment by JamesGZM** [comment]
@GanZhiXiong 这个可以根据自己得需求 实现一个自定义播放界面

**Comment by befovy** [comment]
released in v0.3.0
