### ISSUE TITLE
视频加载完后为什么背景是黑的？

### ISSUE THREAD

**Issue by ivan5151** [befovy/fijkplayer#118]
视频加载完后为什么背景是黑的？而且也看不到时长，需要播放后才有。

**Comment by befovy** [comment]
你描述的加载完成后具体是指调用什么接口后？ 你认为应该是什么样子，请描述一下

**Comment by ivan5151** [comment]
FijkPlayer player = FijkPlayer();
player.setDataSource(url, autoPlay: false);

就是调用完setDataSource，希望是可以出现视频的画面，是时长。但是现在调用完setDataSource如果不设置自动播放，就是一个黑色的背景，时间也是00:00

**Comment by befovy** [comment]
`player.setDataSource(url, autoPlay: false);` 
这一行仅仅是传递 url 参数到C层播放器内部，没有启动任何线程，没有网络访问。

`await player.setDataSource(url, autoPlay: true);` 
差别就大了，相当于
```dart
await player.setDataSource(url);
await player.setOption(FijkOption.playerCategory, "start-on-prepared", 1);
await player.prepareAsync();
```
----

我明白你的需求，但是现在对这个没有很好地支持。
以 fijkplayer 目前的功能实现你的需求，你需要先设置静音，再开始播放，然后在第一帧视频渲染之后调用暂停。

我会在 ijkplayer 中真正实现你所说的这个需求，不过得等段时间了。

@ivan5151

**Comment by ivan5151** [comment]
好的，谢谢。

**Comment by befovy** [comment]
@ivan5151 更新支持了，可以试试。

文档见 https://fijkplayer.befovy.com/docs/zh/fijkplayer-api.html 中 setDataSource 部分。

**Comment by ivan5151** [comment]
好的，感谢。

**Comment by flashliu** [comment]
setDataSource 设置 showCover 为true 依然显示黑屏
