### ISSUE TITLE
How to show video controls

### ISSUE THREAD

**Issue by cc123** [befovy/fijkplayer#121]
I'm probably missing a simple configuration setting - how can I get the video controls to always show? (Right now, they don't appear until I touch the control itself.)

Great work, thanks!

**Comment by befovy** [comment]
Hi @cc123 

`video controls` is a widget build from `panelBuilder` argument of `FijkView`.

The`defaultFijkPanelBuilder` dose not take any user argument, so you can't change it's behavior if you do not changes the code. 

So, there are at least two ways for you to getting the video controls to always show.
1. fork this repo and change the code of `defaultFijkPanelBuilder`. In details, search `_hideTimer` in the code.
2. Implement your own panel, and pass it to `FijkView`. If you are not skill on building custom panel, just copy and change the code of  `defaultFijkPanelBuilder`.
