### ISSUE TITLE
关于MethodChannel和EventChannel释放的问题

### ISSUE THREAD

**Issue by MMMzq** [befovy/fijkplayer#126]
- 问题描述
我看到android的`FijkPlayer.java`时发现每次创建播放器时都只是创建`MethodChannel`和`EventChannel`而并没有主动去释放,这可能会造成内存泄露
[具体代码](https://github.com/befovy/fijkplayer/blob/master/android/src/main/java/com/befovy/fijkplayer/FijkPlayer.java#L106-L110)

- 正确的做法:
应该在`FijkPlayer`销毁时调用`mMethodChannel.setMethodCallHandler(null)`和`mEventChannel.setStreamHandler(null)`主动释放

- 为什么这么做可以释放?
[可看这里](https://github.com/flutter/engine/blob/6fd58edd3e9cf15d2a29442ae86804530dd171a5/shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java#L45-L53)

当然这只是android端的而ios我就不太清楚了😐

**Comment by befovy** [comment]
哦，这里确实有问题。 代码里出现循环引用里。
iOS 那边释放过了，android 这忘了。
应该在 release() 的最后进行释放，也就是你说的“正确做法”。

@all-contributors please add @MMMzq  for bug
