### ISSUE TITLE
foreground control

### ISSUE THREAD

**Issue by sbilketay** [befovy/fijkplayer#135]
Does it support background playback and foreground control?

**Comment by befovy** [comment]
Yeah, it supports background playback. 
The control and playback can be separated.
 
But what's the foreground when the app is running in background?

**Comment by sbilketay** [comment]
@befovy play / pause controls in notification bar. or the controls on the lock screen.

**Comment by befovy** [comment]
Controls in notification bar or lock screen are android / iOS native views or widgets.

If you want to connect these controls and the flutter player, you need implement your own flutter plugins. 

Set the controls in java/kotlin and objc/swift code, and interact with  dart through flutter event channel and method channel.


BTW, there's no plan to implementing these controls in fijkplayer.
