### ISSUE TITLE
ios端pod install 报错

### ISSUE THREAD

**Issue by ivan5151** [befovy/fijkplayer#136]
[!] CocoaPods could not find compatible versions for pod "FIJKPlayer":
      In snapshot (Podfile.lock):
        FIJKPlayer (= 0.4.3, ~> 0.4.3)

      In Podfile:
        fijkplayer (from `.symlinks/plugins/fijkplayer/ios`) was resolved to 0.2.3, which depends on
          FIJKPlayer (~> 0.4.4)

    Specs satisfying the `FIJKPlayer (= 0.4.3, ~> 0.4.3), FIJKPlayer (~> 0.4.4)` dependency were found, but they required a higher minimum deployment target.

你好，ios端报这个错，请问怎么解决？

**Comment by befovy** [comment]
参考 https://fijkplayer.befovy.com/docs/zh/faq.html#%E5%8D%87%E7%BA%A7%E5%BA%93%E7%89%88%E6%9C%AC%E5%90%8E-pod-%E5%87%BA%E9%94%99

解决办法：在 ios 目录运行 `pod update FIJKPlayer --verbose`

**Comment by ivan5151** [comment]
好的，已解决，谢谢。
