### ISSUE TITLE
播放oss上的视频播放不了

### ISSUE THREAD

**Issue by MMMzq** [befovy/fijkplayer#137]
**Describe the bug**
- 播放oss上的视频播放不了

**To Reproduce**
- 1.使用example输入`http://tldevpub.oss-cn-hangzhou.aliyuncs.com/tester/146/shipin/xcsp.mp4`链接进行播放

**Expected behavior**
- 希望能稳定播放

**Screenshots**
![_](https://raw.githubusercontent.com/MMMzq/fijkplayer/master/docs/20191211_164532.gif)

**fijkplayer version**
- 0.2.3

**Smartphone (please complete the following information):**
 - android虚拟机

**Additional context**
- 有时候能正常播放有时候又不能播放

**Comment by befovy** [comment]
你好，我这边用你提供的 url ，在 android 真机上测试了好几十次，wifi 和联通 4G 都试了，每次都可以播放。

网络问题沟通起来确实比较麻烦，远程支持也很不方便。
建议你多看看播放器日志，或者网络抓包，ping 等工具多角度分析一下网络情况。或许能有什么新发现。

**Comment by MMMzq** [comment]
行,我换个真机试试看先

**Comment by befovy** [comment]
@MMMzq 怎么样？

**Comment by MMMzq** [comment]
我在真机上试过了(小米，华为)，好像都不会出现这个问题(不过我记得之前好像在华为手机上出现过,现就没有再出现了)。

但是在虚拟机还是能稳定复现出来
下面是错误时输出的日志:
```
E/IJKMEDIA( 3770): Stream ends prematurely at 7464854, should be 7464856
E/IJKMEDIA( 3770): error reading header
E/IJKMEDIA( 3770): http://tldevpub.oss-cn-hangzhou.aliyuncs.com/tester/146/shipin/xcsp.mp4: End of file
I/IJKMEDIA( 3770): SDL_JNI_DetachThreadEnv: [4102]
D/IJKMEDIA( 3770): FFP_MSG_ERROR: -541478725
E/tv.danmaku.ijk.media.player.IjkMediaPlayer( 3770): Error (-541478725,0,End of file)
I/flutter ( 3770): [err] 2019-12-17 00:18:01.850251 [fijk] FijkPlayer{id:8} errorListerner: FijkException(-541478725, End of file)
I/flutter ( 3770): [inf] 2019-12-17 00:18:01.850831 [fijk] FijkPlayer{id:8} state changed to FijkState.error <= FijkState.asyncPreparing
I/flutter ( 3770): [inf] 2019-12-17 00:18:03.090757 [fijk] FijkPlayer{id:8} invoke release #2
```
