### ISSUE TITLE
Compiling native code for Mac and Windows

### ISSUE THREAD

**Issue by winwisely99** [befovy/fijkplayer#138]
Could you include a Makefile for compiling the native code for Windows and Mac ?

You can see how we do it here: https://github.com/winwisely99/main/blob/master/client/Makefile#L76

It relies on golang in the top of the Makefile.

Make files work on Windows, Mac and Linux.
You can see how we do it here: https://github.com/winwisely99/bootstrap/tree/master/os

**Comment by befovy** [comment]
The fijkplayer for mac need `libIjkPlayer.dylib` which can be downloaded here https://github.com/befovy/ijkplayer/releases/tag/f0.4.3

I have built the mac version, but I don't have windows devices.

To build `libIjkPlayer.dylib`,  you need to build `ffmpeg` and `openssl`(optional) firstly.
And then build ijkplayer.

The constructions about build ffmpeg can be found here.  https://github.com/befovy/ijkplayer/blob/master/README.md

I will write new doc about how to build mac release in later.
But it is difficult for me to write makefile for this.

BTW, desktop support of fijkplayer is not ready for production.

**Comment by befovy** [comment]
see the steps about how to build native code for Mac here 
https://github.com/befovy/ijkplayer#build-for-mac-os
