### ISSUE TITLE
大佬计划啥时候加入进度、亮度、音量调节手势呀？

### ISSUE THREAD

**Issue by GanZhiXiong** [befovy/fijkplayer#140]

**Comment by befovy** [comment]
“进度” 你可以说的在明确一些吗？

**Comment by GanZhiXiong** [comment]
就是视频上通过手势左右滑动控制快进快退

**Comment by befovy** [comment]
明白。

左右手势滑动，控制前进后退。
左侧上下滑动控制屏幕亮度，右侧上下滑动控制音量。

其实这些都可以自己实现的，不算播放器核心功能。当然我也考虑把这个加进来的，只不过这两天太忙了

**Comment by GanZhiXiong** [comment]
表示非常期待！
你这个插件是通过原生视图显示在widget上吗？还是其他原理呢？期待您能出一个该插件的原理和实现的文章！！！😀

**Comment by befovy** [comment]
不是原生视图。是用了 Flutter 中的 Texture 对接的。

**Comment by GanZhiXiong** [comment]
好的，我也去了解下，刚好最近做flutter项目，需要用到视频播放器，flutter官方的video_palyer太简单了，所以找到您这个。不知对于大文件的快进快退卡顿情况是否是Texture导致的呢？这几天一直在找Flutter中实现视频播放器的最佳方案。

**Comment by mrdong916** [comment]
期待这些功能

**Comment by lchjczw** [comment]
期待这三个功能

**Comment by lchjczw** [comment]
@befovy 我觉得这个功能可以提上日程来,虽然不是最重要的,但是,确实是最常用的功能

**Comment by befovy** [comment]
最近正在利用空闲时间开发这些功能，比较慢，抱歉让各位久等了。
这里先提前声明一下：

虽然这些功能正在逐步加入默认 UI 中，但我还是希望默认 UI 只是给各位一个参考。
最好都能自己做 UI。

我会保证 FijkPlayer 和 FijkView 的接口是稳定的，但是默认 UI 没有任何保证。
默认 UI 的价值是让大家参考代码去实现自己的符合 App 实际使用场景的 UI。                                      
默认 UI 可能随时变化。

**Comment by gaoyong06** [comment]
大佬进展怎么样了，这些很『基础』的功能确实很需要啊，能避免很多『重复』

**Comment by befovy** [comment]
@GanZhiXiong @mrdong916 @lchjczw @gaoyong06 
此功能已经在  develop 分支开发完成，可以的话希望几位能够帮忙测试一下

**Comment by ntcat** [comment]
测试效果，同一个m3u8文件 ，画质不如用apicloud编译的H5播放效果，看上去马赛克感更强。

**Comment by befovy** [comment]
> 测试效果，同一个m3u8文件 ，画质不如用apicloud编译的H5播放效果，看上去马赛克感更强。

和这些手势调节有啥关系呢？ 是不是评论错位置了
