### ISSUE TITLE
[BUG]NoSuchMethodError: The method 'toDouble' was called on null.

### ISSUE THREAD

**Issue by jiongjarjar** [befovy/fijkplayer#145]
**Describe the bug**
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'toDouble' was called on null.
    Receiver: null
    Tried calling: toDouble()
    #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
    #1      FijkPlayer._eventListener (package:fijkplayer/core/fijkplayer.dart:495:45)
    #2      _rootRunUnary (dart:async/zone.dart:1132:38)
    #3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
    #6      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
    #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
    #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
    #9      _rootRun (dart:async/zone.dart:1120:38)
    #10     _CustomZone.run (dart:async/zone.dart:1021:19)
    #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #13     _rootRun (dart:async/zone.dart:1124:13)
    #14     _CustomZone.run (dart:async/zone.dart:1021:19)
    #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**flutter --version**
Flutter 1.9.1+hotfix.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68587a0916 (3 months ago) • 2019-09-13 19:46:58 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

**Comment by befovy** [comment]
@jiongjarjar  Thanks.

@all-contributors please add @jiongjarjar  for bug
