### ISSUE TITLE
支持代理预加载吗?

### ISSUE THREAD

**Issue by lchjczw** [befovy/fijkplayer#150]
之前网上看到有实现,大概流程类似这种:

1. 启动播放器,
2. 建立本地服务,
3. 通过代理服务分段多线程下载,
4. 进行视频缓存拼接
5. 播放器从本地代理播放视频

大概流程就是这种,不知道这种支持不,或者有没有更好的预加载方式,暂时先用起来,flutter写起来舒服的多

之所以有这种需求,是因为有时候网络不好,造成卡顿,还有就是国内的带宽确实有点贵,相比之下,国外的大带宽就相当亲民了

**Comment by lchjczw** [comment]
感谢作者在flutter播放器的付出,让我们少了好多工作,
#122 这个issue的方案和 https://github.com/bilibili/ijkplayer/issues/4069 上面有人解决了,基本就是上面的思路就可以实现这个流程,不知道 #122 现在可以缓存了吗?

**Comment by befovy** [comment]
@lchjczw  你上面补充评论中提到的两个 issue 是关于设置播放器缓存的。
fijkplayer 是支持缓存的， 只要按照 ijkplayer 中缓存相关的几个 option 参数进行设置就可以。
ijkplayer 中设置 option 的接口在 fijkplayer 中也有对应的设置 option 接口可以用。

然而你上面提到预先加载，这个和缓存是不一样的，目前没有支持预先加载、代理服务的功能。

**Comment by befovy** [comment]
代理服务，预先加载等不在计划中。
缓存可以使用 ijkplayer 中的协议实现（通过设置 options）
