### ISSUE TITLE
example dubug闪退

### ISSUE THREAD

**Issue by The-five-stooges** [befovy/fijkplayer#151]
测试机型：小米mix2
安卓： 9.0
miui 11

**Comment by befovy** [comment]
可以捕获一下闪退时 logcat 信息吗？ 另外时进行什么操作是闪退？

**Comment by The-five-stooges** [comment]
没有报错信息，就是在example中执行flutter run命令，编辑器仍然处于运行状态，真机应用闪退

**Comment by befovy** [comment]
@The-five-stooges 
你可以在 android studio 中打开 example/android 目录，在 android  studio 中点击运行，这种方式会看到 logcat。
不知你有没有 android 开发经验

**Comment by The-five-stooges** [comment]
好的，在android studio里跑了一遍，可以运行了👍，之前没有使用android studio进行编译
