### ISSUE TITLE
fijkplayer支持ts格式的视频吗？

### ISSUE THREAD

**Issue by yuffiepro** [befovy/fijkplayer#152]
显示结果是：errorListerner: FijkException(-1381258232, Stream not found)

**Comment by befovy** [comment]
@yuffiepro  具体路径怎么设置的呢？  philips.ts 打包在 app 什么位置了？

**Comment by yuffiepro** [comment]
assets:
    - assets/butterfly.mp4
    - assets/philips.ts

**Comment by befovy** [comment]
现在错误成了 stream not found 了。
直接播放 ts 文件没试过。ts 文件是 hls 协议的一部分。
hls 协议包含 m3u8 文件和 ts 文件，单独使用 ts 文件播放可能不支持。

**Comment by yuffiepro** [comment]
我试了下使用ts直播流好像也是errorListerner: FijkException(-1381258232, Stream not found)这个错误

**Comment by befovy** [comment]
你先用其他电脑上的播放器试试，比如 vlc player。是不是你的ts 文件就是不能播？

其实我是没有遇到过要直接播放 ts 文件的情况，一般都是播放 m3u8 网络文件

**Comment by yuffiepro** [comment]
之前用bilibili/ijkplayer，播放过同一个文件和文件流都可以播放的，但需要硬解好像，是不是需要对fijkplayer 进行一些参数设置？

**Comment by befovy** [comment]
这个错误和硬解没有关系

**Comment by yuffiepro** [comment]
请问有计划支持ts文件播放吗？？

**Comment by befovy** [comment]
@yuffiepro 方便微信联系吗？ 我的微信id 和 github id 相同，支持 ts 文件播放需要你的帮助

**Comment by yuffiepro** [comment]
根据https://fijkplayer.befovy.com/docs/zh/replace-ijkplayer.html处理，替换重新编译的aar（ijkplayer使用default.sh），Android可以播放ts文件了，效果什么的需要再调吧！

**Comment by befovy** [comment]
`module-default.sh` 没有 `--disable-demuxers` , 编译出来体积应该大了不少。
不过看来我写的文档还有些用，😄

**Comment by yuffiepro** [comment]
default出来的是 20M，要重新调配下属性，再编个

**Comment by befovy** [comment]
@yuffiepro 请问有没有重新调整一下 ffmpeg 编译的 config 参数， 支持 ts 播放最少需要增加的参数是哪些？
