### ISSUE TITLE
播放网络视频显示I/O error

### ISSUE THREAD

**Issue by xuelongqy** [befovy/fijkplayer#159]
视频地址：http://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4
错误现象：播放器中央显示I/O error

**Comment by befovy** [comment]
@xuelongqy 你好，

http://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4 
这个网站有时候不稳定，尤其是在国内的网络环境，经常访问不了。建议更换其他测试视频地址。

> 播放器中央显示I/O error

这个是我在默认的UI中简单粗暴把错误信息显示出来了，后续会处理一下 UI 显示。
