### ISSUE TITLE
请问如何实现视频水平翻转和垂直翻转功能？

### ISSUE THREAD

**Issue by bjgxssh** [befovy/fijkplayer#164]
请问如何实现视频水平翻转和垂直翻转功能？我看里面有rotate:degree的代码，但是没有传入的地方。

**Comment by befovy** [comment]
谢谢支持。

你找到的 Rotate 代码是适配本身带有旋转角度视频的播放的。目前没有额外对镜像翻转的功能支持。

你可以考虑看看 Flutter 中的 Rotate 等这些 Widget 是否可以实现此功能

**Comment by bjgxssh** [comment]
好的，非常感谢

**Comment by bjgxssh** [comment]
我把插件下到本地，修改了一下可以支持水平翻转和垂直翻转，以及移位、放大等功能。建议后续可以加上，需要对外面暴露一个参数设置。

  Widget buildTexture() {
    Widget tex = _textureId > 0 ? Texture(textureId: _textureId) : Container();
    if (_degree != 0 && _textureId > 0) {
      /*return RotatedBox(
        quarterTurns: _degree ~/ 90,
        child: tex,
      );*/
     //这里需要传入一个参数控制，可以_degree,但是名称可能需要换下。
      //var trans = Matrix4.identity()..rotateY(pi); //水平镜像
      //var trans = Matrix4.identity()..rotateX(pi); //垂直镜像
      //var trans = Matrix4.identity()..rotateZ(pi); //旋转360
     if (_degree == 1) {
      var trans = Matrix4.identity()..scale(2.0); //放大2倍
     } else {
      var trans = null;
     }
      return Transform(
          transform: trans,
          alignment: Alignment.center,
          child: tex
      );
    }
    return tex;
  }
