### ISSUE TITLE
[BUG]   java.lang.UnsatisfiedLinkError: JNI_OnLoad failed

### ISSUE THREAD

**Issue by jinjilynn** [befovy/fijkplayer#167]
--------- beginning of crash
01-11 23:44:17.142  1495  1495 E AndroidRuntime: FATAL EXCEPTION: main
01-11 23:44:17.142  1495  1495 E AndroidRuntime: Process: com.example.standard, PID: 1495
01-11 23:44:17.142  1495  1495 E AndroidRuntime: java.lang.UnsatisfiedLinkError: JNI_OnLoad failed on a previous attempt to load "/data/app/com.example.standard-1/lib/x86/libijksdl.so"
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary(Runtime.java:373)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1076)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.b()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.a()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at b.a.a.a.<init>()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at b.a.a.b.a()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at com.example.standard.MainActivity.a()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at c.a.b.a.e.a()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at c.a.b.a.d.onCreate()
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6279)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2396)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2503)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5539)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
01-11 23:44:17.142  1495  1495 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
01-11 23:44:17.145   421   876 W ActivityManager:   Force finishing activity com.example.standard/.MainActivity
01-11 23:44:17.146   421   442 D ActivityManager: Nemu don't show crash dialog of ProcessRecord{f152184 1495:com.example.standard/u0a36}
01-11 23:44:17.147   421   441 D Interception: result: allow, reason: calleePkg is system app, rule: runType===broadcast|||callerPkg===android|||calleePkg===com.mumu.acc|||calleeClass===com.mumu.acc.AccMsgReceiver|||action===uu.intent.action.STOP_ACCELERATE
01-11 23:44:17.148  1044  1044 D AccService: AccMsgReceiver: uu.intent.action.STOP_ACCELERATE
01-11 23:44:17.149   842   985 D com.netease.nemu_android_watchdog_lib.core.Watchdog: upload event: {"architecture":"x86_64","channel":"mac-nochannel","engine":"MAC","language":"zh-Hans","package":"mac-nopackage","usage":"0","uuid":"393eaf4d2f4d5ac89a885dec9c34a2f0","version":"1.9.0","x":{"app_elapse":0,"app_name":"video","app_package":"com.example.standard","error":{"code":0,"msg":"ok"},"token":""}}	type: ExitAPP	sign: uZvaUgJubgKqfzW6DUye2sAc3yM=	uid: 1000
01-11 23:44:17.153   421   876 I com.android.server.tabs.TabManagerService: notifyClosing:725: notify tab closed in android as it's closed task com.example.standard, taskId: 13, elapseTime: 950
01-11 23:44:17.153   842   842 D com.netease.nemu_vapi_android.service.AppService: dropbox tag: data_app_crash

说是failed on a previous attempt to load "/data/app/com.example.standard-1/lib/x86/libijksdl.so"

但是apk里的lib/x86下面是有libijksdl.so文件的

**Comment by befovy** [comment]
混淆问题 你看看 readme 中的 faq 链接

**Comment by jinjilynn** [comment]
-keep class tv.danmaku.ijk.media.player.** {*; }

i tried, bu it didn't work!

**Comment by befovy** [comment]
看这个报错信息确实是混淆了，类名都成了 a b c d 等。

你按照这个 https://github.com/befovy/fijkplayer/pull/98/files 修改了吗？  gradle 文件也需要改
