### ISSUE TITLE
如何只旋转ikjplayerview，而不触发[UIViewController attemptRotationToDeviceOrientation]

### ISSUE THREAD

**Issue by y0unghe** [befovy/fijkplayer#169]
如何只可以点击全屏播放，当旋转手机不触发playerview旋转，怎么做啊？

**Comment by befovy** [comment]
没明白你的意思，请说具体些。

**Comment by befovy** [comment]
@y0unghe 
没收到你的具体意思，我也只能回复个大概了。

可以尝试把 FijkView 作为 Rotate 的 child，这样随意改变角度，但屏幕方向不发生变化。

关于此问题如果有进一步讨论的必要，可以再次打开这个 issue。
