### ISSUE TITLE
在ios端添加插件以后无法编译，对原生不大懂 哪位大神指点下

### ISSUE THREAD

**Issue by Slhaos7373** [befovy/fijkplayer#170]
Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone Xʀ.

**Comment by befovy** [comment]
错误提示让你运行 `pod repo update` ， 这个命令运行了吗？ 什么结果
