### ISSUE TITLE
能支持选择音轨么？类似KTV效果，原声和伴奏可以切换

### ISSUE THREAD

**Issue by Galaxyjia** [befovy/fijkplayer#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by befovy** [comment]
ijkplayer 有切花音轨的功能，但是达不到 ktv 那种无缝切换效果，时间戳会出错。
fijkplayer 没有暴露 ijkplayer 的切换音轨接口，所以在 fijkplayer 目前还不能切换音轨。
