### ISSUE TITLE
怎么设置播放完成后的回调，能给个案例么？

### ISSUE THREAD

**Issue by Galaxyjia** [befovy/fijkplayer#175]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by befovy** [comment]
FijkValue 中 completed 变为 true 就表示播放完成了。

使用 FijkPlayer 的 addListener 方法注册函数，监听 FijkValue 的变化
