### ISSUE TITLE
Support new Android plugins APIs

### ISSUE THREAD

**Issue by artannyel** [befovy/fijkplayer#181]
**Describe the bug**
Recompile with -Xlint:deprecation for details.

**Comment by befovy** [comment]
I will support the new Android plugins APIs in weeks.
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by Galaxyjia** [comment]
Recompile with -Xlint:deprecation for details.
我也是这个问题，打包会提示，点击会闪退
