### ISSUE TITLE
Very slow or laggy playback and no audio on Firestick.

### ISSUE THREAD

**Issue by pharshdev** [befovy/fijkplayer#187]
Same video works on VideoPlayer package fine. Checked the similar issue #176 tried setting player flags, but it doesn't solve my problem.

Flutter (Channel **beta**, v1.14.6)

Console Log:
`I/flutter (32474): [war] 2020-02-28 10:29:14.653393 [fijk] call setDataSource with both autoPlay and showCover true, showCover will be ignored
I/flutter (32474): [inf] 2020-02-28 10:29:14.653904 [fijk] FijkPlayer{id:-1} enterFullScreen
I/flutter (32474): [inf] 2020-02-28 10:29:14.675289 [fijk] create player id:2
I/flutter (32474): [inf] 2020-02-28 10:29:14.676718 [fijk] FijkPlayer{id:2} invoke setDataSource https://samantha.nahn0.biz/dl/2Iq-uw0qeCY8p5sZlFm-pQ/1583470751/694180459/5dfd3886f284b1.19580127/Genius.S01E01.Einstein.Chapter.One.1080p.AMZN.WEB-DL.DD.5.1.H.265-SiGMA.mkv
I/flutter (32474): [inf] 2020-02-28 10:29:14.680379 [fijk] FijkPlayer{id:2} invoke setVolume 100.0
I/flutter (32474): [inf] 2020-02-28 10:29:14.684490 [fijk] FijkPlayer{id:2} state changed to FijkState.initialized <= FijkState.idle
I/flutter (32474): [inf] 2020-02-28 10:29:14.694696 [fijk] FijkPlayer{id:2} invoke prepareAsync and start #1
I/flutter (32474): [inf] 2020-02-28 10:29:14.695016 [fijk] FijkPlayer{id:2} setOption k:start-on-prepared, v:1
I/flutter (32474): [inf] 2020-02-28 10:29:14.707048 [fijk] FijkPlayer{id:2} state changed to FijkState.asyncPreparing <= FijkState.initialized
I/flutter (32474): [inf] 2020-02-28 10:29:14.707762 [fijk] FijkPlayer{id:2} invoke prepareAsync and start #1 -> done
I/flutter (32474): [inf] 2020-02-28 10:29:14.717991 [fijk] FijkPlayer{id:2} state changed to FijkState.initialized <= FijkState.idle
I/flutter (32474): [inf] 2020-02-28 10:29:14.718648 [fijk] FijkPlayer{id:2} state changed to FijkState.asyncPreparing <= FijkState.initialized
I/flutter (32474): [inf] 2020-02-28 10:29:17.760445 [fijk] FijkPlayer{id:2} rotate degree 0
I/flutter (32474): [inf] 2020-02-28 10:29:17.764213 [fijk] FijkPlayer{id:2} size changed (1920, 960)
I/flutter (32474): [inf] 2020-02-28 10:29:17.769816 [fijk] FijkPlayer{id:2} prepared duration 1:04:51.104000
I/flutter (32474): [inf] 2020-02-28 10:29:17.770653 [fijk] FijkPlayer{id:2} setupSurface
I/flutter (32474): [inf] 2020-02-28 10:29:17.774186 [fijk] FijkPlayer{id:2} state changed to FijkState.prepared <= FijkState.asyncPreparing
I/flutter (32474): [inf] 2020-02-28 10:29:17.775388 [fijk] FijkPlayer{id:2} setupSurface
I/flutter (32474): [inf] 2020-02-28 10:29:17.776658 [fijk] FijkPlayer{id:2} state changed to FijkState.started <= FijkState.prepared
I/flutter (32474): [inf] 2020-02-28 10:29:17.777210 [fijk] FijkPlayer{id:2} setupSurface
I/flutter (32474): [inf] 2020-02-28 10:29:17.813649 [fijk] view setup, vid:1
I/flutter (32474): [inf] 2020-02-28 10:29:17.814079 [fijk] view setup, vid:1
I/flutter (32474): [inf] 2020-02-28 10:29:17.815256 [fijk] view setup, vid:1
I/flutter (32474): [inf] 2020-02-28 10:29:17.928808 [fijk] FijkPlayer{id:2} size changed (1920, 960)
I/flutter (32474): [inf] 2020-02-28 10:29:18.080356 [fijk] FijkPlayer{id:2} size changed (1920, 960)
I/flutter (32474): [inf] 2020-02-28 10:29:18.163347 [fijk] FijkPlayer{id:2} video rendering started
I/flutter (32474): [inf] 2020-02-28 10:29:18.223137 [fijk] FijkPlayer{id:2} size changed (1920, 960)
I/flutter (32474): [inf] 2020-02-28 10:29:23.232503 [fijk] FijkPlayer{id:2} invoke seekTo msec:15097`

**Comment by befovy** [comment]
I guess it did not find codec for the audio. You need to recompile ffmpeg in this case.

Need native logs to check audio codec.

**Comment by pharshdev** [comment]
Yes I thought so. Recompiling ffmpeg with ["more codec/format"](https://github.com/befovy/ijkplayer#before-build), [here](https://github.com/befovy/ijkplayer/issues/16).
