### ISSUE TITLE
Changing Playlists options

### ISSUE THREAD

**Issue by Michael24884** [befovy/fijkplayer#188]
`
I/flutter (12536): [inf] 2020-03-01 15:01:59.907737 [fijk] FijkPlayer{id:13} invoke reset #1
D/IJKMEDIA(12536): IjkMediaPlayer_reset
D/IJKMEDIA(12536): ijkmp_reset()
D/IJKMEDIA(12536): ijkmp_reset()=0
I/flutter (12536): [inf] 2020-03-01 15:01:59.919411 [fijk] FijkPlayer{id:13} invoke reset #1 -> done
I/flutter (12536): [inf] 2020-03-01 15:02:04.939290 [fijk] FijkPlayer{id:13} setOption k:headers, v:Referer:http://vidstreaming.io/
D/IJKMEDIA(12536): IjkMediaPlayer_setOption
I/flutter (12536): [inf] 2020-03-01 15:02:04.957793 [fijk] FijkPlayer{id:13} setOption k:videotoolbox, v:1
I/flutter (12536): [inf] 2020-03-01 15:02:04.958155 [fijk] FijkPlayer{id:13} invoke setDataSource https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.m3u8
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
D/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): Couldn't open file on client side, trying server side
D/IJKMEDIA(12536): IjkMediaPlayer_setDataSourceAndHeaders
V/IJKMEDIA(12536): setDataSource: path https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.m3u8
D/IJKMEDIA(12536): ijkmp_set_data_source(url="https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.m3u8")
D/IJKMEDIA(12536): ijkmp_set_data_source(url="https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.m3u8")=0
I/flutter (12536): [inf] 2020-03-01 15:02:04.963769 [fijk] FijkPlayer{id:13} setOption k:videotoolbox-async, v:1
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/flutter (12536): [inf] 2020-03-01 15:02:04.968864 [fijk] FijkPlayer{id:13} state changed to FijkState.initialized <= FijkState.idle
I/flutter (12536): [inf] 2020-03-01 15:02:04.975852 [fijk] FijkPlayer{id:13} invoke prepareAsync and start #2
I/flutter (12536): [inf] 2020-03-01 15:02:04.976063 [fijk] FijkPlayer{id:13} setOption k:start-on-prepared, v:1
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/flutter (12536): [inf] 2020-03-01 15:02:04.996161 [fijk] FijkPlayer{id:13} setOption k:videotoolbox-wait-async, v:1
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/flutter (12536): [inf] 2020-03-01 15:02:05.003377 [fijk] FijkPlayer{id:13} setOption k:videotoolbox-handle-resolution-change, v:1
D/IJKMEDIA(12536): IjkMediaPlayer_prepareAsync
D/IJKMEDIA(12536): ijkmp_prepare_async()
I/IJKMEDIA(12536): ===== versions =====
I/IJKMEDIA(12536): ijkplayer    : f0.4.4
I/IJKMEDIA(12536): FFmpeg       : ff3.4--ijk0.8.7--20180103--001
I/IJKMEDIA(12536): libavutil    : 55.78.100
I/IJKMEDIA(12536): libavcodec   : 57.107.100
I/IJKMEDIA(12536): libavformat  : 57.83.100
I/IJKMEDIA(12536): libswscale   : 4.8.100
I/IJKMEDIA(12536): libswresample: 2.9.100
I/IJKMEDIA(12536): SDL_RunThread: [13839] ff_msg_loop
D/IJKMEDIA(12536): message_loop
I/IJKMEDIA(12536): ===== options =====
I/IJKMEDIA(12536): player-opts : enable-position-notify       = 1
I/IJKMEDIA(12536): player-opts : videotoolbox-async           = 1
I/IJKMEDIA(12536): player-opts : videotoolbox                 = 1
I/IJKMEDIA(12536): player-opts : start-on-prepared            = 1
I/IJKMEDIA(12536): player-opts : videotoolbox-wait-async      = 1
I/IJKMEDIA(12536): format-opts : ijkapplication               = -564107632
I/IJKMEDIA(12536): format-opts : ijkiomanager                 = -1189926272
I/IJKMEDIA(12536): format-opts : headers                      = Referer:http://vidstreaming.io/
I/IJKMEDIA(12536):
I/IJKMEDIA(12536): ===================
D/IJKMEDIA(12536): FFP_MSG_FLUSH:
D/IJKMEDIA(12536): ijkmp_prepare_async()=0
I/IJKMEDIA(12536): SDL_RunThread: [13840] ff_vout
I/IJKMEDIA(12536): SDL_RunThread: [13841] ff_read
I/flutter (12536): [inf] 2020-03-01 15:02:05.018798 [fijk] FijkPlayer{id:13} state changed to FijkState.asyncPreparing <= FijkState.initialized
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 1
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131073
I/flutter (12536): [inf] 2020-03-01 15:02:05.028953 [fijk] FijkPlayer{id:13} invoke prepareAsync and start #2 -> done
I/flutter (12536): [inf] 2020-03-01 15:02:05.042938 [fijk] FijkPlayer{id:13} setOption k:max-buffer-size, v:1048576
I/flutter (12536): [inf] 2020-03-01 15:02:05.047614 [fijk] FijkPlayer{id:13} state changed to FijkState.initialized <= FijkState.idle
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/flutter (12536): [inf] 2020-03-01 15:02:05.057821 [fijk] FijkPlayer{id:13} state changed to FijkState.asyncPreparing <= FijkState.initialized
I/flutter (12536): [inf] 2020-03-01 15:02:05.062336 [fijk] FijkPlayer{id:13} setOption k:next-high-water-mark-ms, v:6000
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/flutter (12536): [inf] 2020-03-01 15:02:05.079034 [fijk] FijkPlayer{id:13} setOption k:max-fps, v:60
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/flutter (12536): [inf] 2020-03-01 15:02:05.082896 [fijk] FijkPlayer{id:13} setOption k:mediacodec-avc, v:1
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/flutter (12536): [inf] 2020-03-01 15:02:05.087021 [fijk] FijkPlayer{id:13} setOption k:mediacodec-handle-resolution-change, v:1
D/IJKMEDIA(12536): IjkMediaPlayer_setOptionLong
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 2
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.360.m3u8' for reading
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.480.m3u8' for reading
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.720.m3u8' for reading
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.1080.m3u8' for reading
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.3600.ts' for reading
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 1
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 2
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.4800.ts' for reading
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 1
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 2
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.7200.ts' for reading
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 1
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 2
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.10800.ts' for reading
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 1
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 2
E/IJKMEDIA(12536): Option ijkiomanager not found.
D/IJKMEDIA(12536): FFP_MSG_OPEN_INPUT:
E/IJKMEDIA(12536): Invalid NAL unit 0, skipping.
I/chatty  (12536): uid=10185(com.example.taiyaki_anime) Thread-22 identical 2 lines
E/IJKMEDIA(12536): Invalid NAL unit 0, skipping.
I/IJKMEDIA(12536): max_frame_duration: 10.000
I/IJKMEDIA(12536): Input #0, hls,applehttp, from 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.m3u8':
I/IJKMEDIA(12536):   Duration:
I/IJKMEDIA(12536): 00:23:39.92
I/IJKMEDIA(12536): , start:
I/IJKMEDIA(12536): 1.400000
D/IJKMEDIA(12536): FFP_MSG_FIND_STREAM_INFO:
I/IJKMEDIA(12536): , bitrate:
I/IJKMEDIA(12536): 0 kb/s
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):   Program 0
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 421912
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Stream #0:0
I/IJKMEDIA(12536): : Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 640x360 [SAR 1:1 DAR 16:9]
I/IJKMEDIA(12536): ,
I/IJKMEDIA(12536): 23.98 fps,
I/IJKMEDIA(12536): 23.98 tbr,
I/IJKMEDIA(12536): 90k tbn,
I/IJKMEDIA(12536): 47.95 tbc
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 421912
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Stream #0:1
I/IJKMEDIA(12536): : Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 421912
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):   Program 1
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 626089
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Stream #0:2
I/IJKMEDIA(12536): : Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 854x480 [SAR 1:1 DAR 427:240]
I/IJKMEDIA(12536): ,
I/IJKMEDIA(12536): 23.98 fps,
I/IJKMEDIA(12536): 23.98 tbr,
I/IJKMEDIA(12536): 90k tbn,
I/IJKMEDIA(12536): 47.95 tbc
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 626089
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Stream #0:3
I/IJKMEDIA(12536): : Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 626089
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):   Program 2
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 1365217
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Stream #0:4
I/IJKMEDIA(12536): : Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9]
I/IJKMEDIA(12536): ,
I/IJKMEDIA(12536): 23.98 fps,
I/IJKMEDIA(12536): 23.98 tbr,
I/IJKMEDIA(12536): 90k tbn,
I/IJKMEDIA(12536): 47.95 tbc
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 1365217
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Stream #0:5
I/IJKMEDIA(12536): : Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 1365217
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):   Program 3
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 2336723
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Stream #0:6
I/IJKMEDIA(12536): : Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9]
I/IJKMEDIA(12536): ,
I/IJKMEDIA(12536): 23.98 fps,
I/IJKMEDIA(12536): 23.98 tbr,
I/IJKMEDIA(12536): 90k tbn,
I/IJKMEDIA(12536): 47.95 tbc
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 2336723
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Stream #0:7
I/IJKMEDIA(12536): : Audio: aac ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
I/IJKMEDIA(12536):
I/IJKMEDIA(12536):     Metadata:
I/IJKMEDIA(12536):       variant_bitrate :
I/IJKMEDIA(12536): 2336723
I/IJKMEDIA(12536):
W/IJKMEDIA(12536): multiple video stream found, prefer first h264 stream: 0
I/IJKMEDIA(12536): SDL_Android_AudioTrack: CHANNEL_OUT_STEREO
I/IJKMEDIA(12536): SDL_Android_AudioTrack: ENCODING_PCM_16BIT
W/AudioTrack(12536): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(12536): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/IJKMEDIA(12536): SDL_Android_AudioTrack_new_from_spec: init volume as 1.000000/(0.000000,1.000000)
I/IJKMEDIA(12536): audio_session_id = 49
I/IJKMEDIA(12536): AudioCodec: avcodec, aac
I/IJKMEDIA(12536): SDL_RunThread: [13847] ff_aout_android
I/IJKMEDIA(12536): SDL_RunThread: [13848] ff_audio_dec
I/IJKMEDIA(12536): VideoCodec: avcodec, h264
W/IJKMEDIA(12536): fps: 23.976024 (normal)
W/IJKMEDIA(12536): fps: 23.976024 (normal)
D/IJKMEDIA(12536): FFP_MSG_COMPONENT_OPEN:
D/IJKMEDIA(12536): FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
D/IJKMEDIA(12536): FFP_MSG_SAR_CHANGED: 1, 1
D/IJKMEDIA(12536): ijkmp_get_msg: FFP_MSG_PREPARED
D/IJKMEDIA(12536): FFP_MSG_PREPARED:
D/IJKMEDIA(12536): avcodec/Audio: first frame decoded
D/IJKMEDIA(12536): FFP_MSG_AUDIO_DECODED_START:
D/IJKMEDIA(12536): FFP_MSG_AUDIO_RENDERING_START:
I/IJKMEDIA(12536): SDL_RunThread: [13854] ff_video_dec
D/IJKMEDIA(12536): FFP_MSG_VIDEO_ROTATION_CHANGED: 0
I/flutter (12536): [inf] 2020-03-01 15:02:15.937045 [fijk] FijkPlayer{id:13} prepared duration 0:23:39.919000
I/flutter (12536): [inf] 2020-03-01 15:02:15.937217 [fijk] FijkPlayer{id:13} setupSurface
D/IJKMEDIA(12536): IjkMediaPlayer_setVideoSurface
D/IJKMEDIA(12536): ijkmp_set_android_surface(surface=0xffe096d0)
D/IJKMEDIA(12536): ffpipeline_set_surface()
D/IJKMEDIA(12536): ijkmp_set_android_surface(surface=0xffe096d0)=void
D/IJKMEDIA(12536): SDL_VoutFFmpeg_CreateOverlay(w=640, h=360, fmt=RV32(0x32335652, dp=0xbb3fcd60)
D/IJKMEDIA(12536): FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
D/IJKMEDIA(12536): Video: first frame decoded
D/IJKMEDIA(12536): FFP_MSG_VIDEO_DECODED_START:
D/IJKMEDIA(12536): SDL_VoutFFmpeg_CreateOverlay(w=640, h=360, fmt=RV32(0x32335652, dp=0xbb3fcd60)
D/IJKMEDIA(12536): FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
D/IJKMEDIA(12536): SDL_VoutFFmpeg_CreateOverlay(w=640, h=360, fmt=RV32(0x32335652, dp=0xbb3fcd60)
D/IJKMEDIA(12536): FFP_MSG_VIDEO_SIZE_CHANGED: 640, 360
I/flutter (12536): [inf] 2020-03-01 15:02:15.938342 [fijk] FijkPlayer{id:13} state changed to FijkState.prepared <= FijkState.asyncPreparing
I/flutter (12536): [inf] 2020-03-01 15:02:15.954290 [fijk] FijkPlayer{id:13} setupSurface
D/IJKMEDIA(12536): ANativeWindow_setBuffersGeometry: w=1, h=1, f=(0x1) => w=640, h=360, f=RV32(0x32335652)
I/flutter (12536): [inf] 2020-03-01 15:02:15.992365 [fijk] FijkPlayer{id:13} state changed to FijkState.started <= FijkState.prepared
I/flutter (12536): [inf] 2020-03-01 15:02:15.992992 [fijk] FijkPlayer{id:13} setupSurface
I/flutter (12536): [inf] 2020-03-01 15:02:15.994756 [fijk] FijkPlayer{id:13} audio rendering started
I/flutter (12536): [inf] 2020-03-01 15:02:15.994897 [fijk] FijkPlayer{id:13} setupSurface
I/flutter (12536): [inf] 2020-03-01 15:02:15.995802 [fijk] FijkPlayer{id:13} rotate degree 0
I/flutter (12536): [inf] 2020-03-01 15:02:15.996207 [fijk] FijkPlayer{id:13} size changed (640, 360)
I/flutter (12536): [inf] 2020-03-01 15:02:16.002842 [fijk] FijkPlayer{id:13} setupSurface
I/flutter (12536): [inf] 2020-03-01 15:02:16.015876 [fijk] view setup, vid:7
I/flutter (12536): [inf] 2020-03-01 15:02:16.019537 [fijk] FijkPlayer{id:13} size changed (640, 360)
D/IJKMEDIA(12536): FFP_MSG_VIDEO_RENDERING_START:
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): Info: MEDIA_INFO_VIDEO_RENDERING_START
I/flutter (12536): [inf] 2020-03-01 15:02:16.025048 [fijk] FijkPlayer{id:13} size changed (640, 360)
I/flutter (12536): [inf] 2020-03-01 15:02:16.029534 [fijk] FijkPlayer{id:13} size changed (640, 360)
I/flutter (12536): [inf] 2020-03-01 15:02:16.029944 [fijk] view setup, vid:7
I/flutter (12536): [inf] 2020-03-01 15:02:16.033083 [fijk] view setup, vid:7
I/flutter (12536): [inf] 2020-03-01 15:02:16.034067 [fijk] view setup, vid:7
I/flutter (12536): [inf] 2020-03-01 15:02:16.038238 [fijk] view setup, vid:7
I/flutter (12536): [inf] 2020-03-01 15:02:16.042554 [fijk] FijkPlayer{id:13} video rendering started
D/IJKMEDIA(12536): FFP_MSG_BUFFERING_START:
D/IJKMEDIA(12536): FFP_MSG_BUFFERING_END:
I/IJKMEDIA(12536): No longer receiving playlist 1
I/IJKMEDIA(12536): No longer receiving playlist 3
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.3601.ts' for reading
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 1
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 2
I/IJKMEDIA(12536): No longer receiving playlist 2
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.3602.ts' for reading
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 1
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 2
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.3603.ts' for reading
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 1
I/IJKMEDIA(12536): Hit DNS cache hostname = hls10xx.cdnfile.info
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 131074
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(12536): onNativeInvoke 2
I/IJKMEDIA(12536): Opening 'https://hls10xx.cdnfile.info/videos/hls/LKlSmujDpzcYnmxhv0vxBA/1583118126/135462/62a6b8aacf52ca24a015365192d10683/sub.1.3604.ts' for reading
`

Hello there. As you can see above, there are multiple streams /
sub.1.360, 
sub.1.480,
sub.1.720,
and sub.1.1080

however FijkPlayer always plays the 360, the lowest quality. Is there any options or ways to choose my streams? Seems like at some point FijkPlayer always stops reading the playlists.

`W/IJKMEDIA(12536): multiple video stream found, prefer first h264 stream: 0`
this is also shown in the log, anyway to change the preference?

**Comment by befovy** [comment]
Sorry, fijkplayer dose not have an API to select a special stream track to play.
