### ISSUE TITLE
请问如何播放已下载至本地的视频？[BUG]

### ISSUE THREAD

**Issue by SpanishOnion** [befovy/fijkplayer#189]
**Describe the bug**
播放已下载的文件视频，会直接报错，我确定文件是存在的，路径也是正确的，这个文件可以在手机相册中打开并播放。
app 也有读取、写入本地文件的权限。

**To Reproduce**
代码如下：
```dart
player.setDataSource('file:///storage/emulated/0/Android/data/com.vhiphop.app/files/download/1556694276826.mp4');
player.prepareAsync();
```

报错如下：

```dart
I/flutter (12769): [inf] 2020-03-02 21:10:36.953147 [fijk] create player id:8
I/flutter (12769): [inf] 2020-03-02 21:10:36.953917 [fijk] FijkPlayer{id:8} invoke setDataSource file:///storage/emulated/0/Android/data/com.vhiphop.app/files/download/1556694276826.mp4
I/flutter (12769): [inf] 2020-03-02 21:10:36.954365 [fijk] FijkOption cloned
E/DataSource(12769): failed to open RandomAccessfile:/storage/emulated/0/Android/data/com.vhiphop.app/files/download/1556694276826.mp4: open failed: ENOENT (No such file or directory)
```

我尝试使用 flutter 官方的 video_player 插件播放，可以成功播放：

```dart
_controller = VideoPlayerController.file(File('/storage/emulated/0/Android/data/com.vhiphop.app/files/download/1556694276826.mp4'))
```
**fijkplayer version**
0.5.2

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
 - Device: [e.g. 华为 JSN-AL00a]
 - OS: [e.g. Android 9]

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.239], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!

**Comment by befovy** [comment]
@SpanishOnion 谢谢反馈。

追问一下，如果文件是保存在外置 sd 卡存储，是否出现这样的情况

**Comment by SpanishOnion** [comment]
我的测试机没有外置 sd 卡，所以也没尝试过。

**Comment by fangmd** [comment]
/emulated/0/Android/data/ 已经算外部sd卡了吧
内部的是: /data/data/com.xxxx/xxx

**Comment by befovy** [comment]
file:// 协议解析有问题，打开文件没有去掉 scheme

**Comment by L-Jay** [comment]
/data/user/0/com.xxx
本地下载视频播放不了，open failed: ENOENT (No such file or directory)
请问怎么解决的，谢谢

**Comment by befovy** [comment]
@L-Jay 找不到文件，请确认文件存在，以及有打开此文件的权限
