### ISSUE TITLE
请问下播放器能不能在横屏状态下，点击全屏后保持横屏

### ISSUE THREAD

**Issue by gneL1** [befovy/fijkplayer#190]
现在如果在横屏情况下点击全屏，会转变成竖屏全屏。我想请问下能不能做到保持横屏全屏

**Comment by befovy** [comment]
> 如果在横屏情况下点击全屏，会转变成竖屏全屏

视频宽高比例是多少？

**Comment by gneL1** [comment]
宽高比例是16/9，FijkFit里的3个参数都尝试过了，宽高比不会对横屏状态点击全屏转变成竖屏全屏产生影响

**Comment by gneL1** [comment]
抱歉不好意思，因为用的是平板所以没注意到到。。横屏拍摄的视频能够横屏全屏播放，竖屏拍摄的视频竖屏全屏播放，之前使用的视频都是在竖屏状态下拍摄的，难怪不能全屏横屏。谢谢作者的帮助
