### ISSUE TITLE
panelBuilder这个属性的demo能出一个完整的嘛 

### ISSUE THREAD

**Issue by hippoBoom** [befovy/fijkplayer#194]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by befovy** [comment]
看这个文档吧 https://fijkplayer.befovy.com/docs/zh/custom-ui.html#%E4%BD%BF%E7%94%A8-fijkpanel2builder

一共没几个参数，试一下就知道效果了
