### ISSUE TITLE
Add user agent header 

### ISSUE THREAD

**Issue by MiriDevAndro** [befovy/fijkplayer#198]
Need to add user agent programmatically

**Comment by befovy** [comment]
please read faq

https://fijkplayer.befovy.com/docs/zh/faq.html

**Comment by MiriDevAndro** [comment]
now i have a problem , is not playing videos  , yesterday works fine but today not working 


 IjkMediaPlayer_native_setup
I/IJKMEDIA(17379): av_version_info: ff4.0--ijk0.8.25--20191031--001
I/IJKMEDIA(17379): ijk_version_info: f0.5.1
D/IJKMEDIA(17379): ffpipeline_create_from_android()
D/IJKMEDIA(17379): ijkmp_set_inject_opaque(0x249a)
D/IJKMEDIA(17379): ijkmp_set_inject_opaque()=void
D/IJKMEDIA(17379): ijkmp_set_ijkio_inject_opaque(0x249a)
D/IJKMEDIA(17379): ijkmp_set_ijkio_inject_opaque()=void
D/IJKMEDIA(17379): ijkmp_android_set_mediacodec_select_callback()
D/IJKMEDIA(17379): ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA(17379): ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA(17379): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(17379): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(17379): IjkMediaPlayer_native_setLogLevel(4)
D/IJKMEDIA(17379): moncleanup
I/flutter (17379): [inf] 2020-03-12 18:18:24.819269 [fijk] create player id:3
I/flutter (17379): [inf] 2020-03-12 18:18:24.855158 [fijk] FijkPlayer{id:3} setOption k:headers, v:user-agent:okokok
D/IJKMEDIA(17379): IjkMediaPlayer_setOption
I/flutter (17379): [inf] 2020-03-12 18:18:24.865306 [fijk] FijkPlayer{id:3} invoke setDataSource http://docs.evostream.com/sample_content/assets/hls-bunny-166/playlist.m3u8
D/tv.danmaku.ijk.media.player.IjkMediaPlayer(17379): Couldn't open file on client side, trying server side
D/IJKMEDIA(17379): IjkMediaPlayer_setDataSourceAndHeaders
V/IJKMEDIA(17379): setDataSource: path http://docs.evostream.com/sample_content/assets/hls-bunny-166/playlist.m3u8
D/IJKMEDIA(17379): ijkmp_set_data_source(url="http://docs.evostream.com/sample_content/assets/hls-bunny-166/playlist.m3u8")
D/IJKMEDIA(17379): ijkmp_set_data_source(url="http://docs.evostream.com/sample_content/assets/hls-bunny-166/playlist.m3u8")=0
I/flutter (17379): [inf] 2020-03-12 18:18:25.254683 [fijk] FijkPlayer{id:3} state changed to FijkState.initialized <= FijkState.idle
I/flutter (17379): [inf] 2020-03-12 18:18:25.281070 [fijk] FijkPlayer{id:3} invoke prepareAsync and start #1
I/flutter (17379): [inf] 2020-03-12 18:18:25.281799 [fijk] FijkPlayer{id:3} setOption k:start-on-prepared, v:1
D/IJKMEDIA(17379): IjkMediaPlayer_setOptionLong
D/IJKMEDIA(17379): IjkMediaPlayer_prepareAsync
D/IJKMEDIA(17379): ijkmp_prepare_async()
I/IJKMEDIA(17379): ===== versions =====
I/IJKMEDIA(17379): ijkplayer    : f0.5.1
I/IJKMEDIA(17379): FFmpeg       : ff4.0--ijk0.8.25--20191031--001
I/IJKMEDIA(17379): libavutil    : 56.14.100
I/IJKMEDIA(17379): libavcodec   : 58.18.100
I/IJKMEDIA(17379): libavformat  : 58.12.100
I/IJKMEDIA(17379): libswscale   : 5.1.100
I/IJKMEDIA(17379): libswresample: 3.1.100
I/IJKMEDIA(17379): ===== options =====
I/IJKMEDIA(17379): player-opts : enable-position-notify       = 1
I/IJKMEDIA(17379): player-opts : start-on-prepared            = 1
I/IJKMEDIA(17379): format-opts : ijkapplication               = 527522636320
I/IJKMEDIA(17379): format-opts : ijkiomanager                 = 527676282112
I/IJKMEDIA(17379): format-opts : headers                      = user-agent:okokok
I/IJKMEDIA(17379): 
I/IJKMEDIA(17379): ===================
D/IJKMEDIA(17379): ijkmp_prepare_async()=0
I/IJKMEDIA(17379): SDL_RunThread: [17523] ff_read
I/IJKMEDIA(17379): SDL_RunThread: [17522] ff_vout
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(17379): onNativeInvoke 1
I/flutter (17379): [inf] 2020-03-12 18:18:25.306915 [fijk] FijkPlayer{id:3} state changed to FijkState.asyncPreparing <= FijkState.initialized
I/IJKMEDIA(17379): SDL_RunThread: [17521] ff_msg_loop
D/IJKMEDIA(17379): message_loop
D/IJKMEDIA(17379): FFP_MSG_FLUSH:
I/flutter (17379): [inf] 2020-03-12 18:18:25.310707 [fijk] FijkPlayer{id:3} invoke prepareAsync and start #1 -> done
E/IJKMEDIA(17379): Failed to resolve hostname docs.evostream.com: No address associated with hostname
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(17379): onNativeInvoke 2
E/IJKMEDIA(17379): http://docs.evostream.com/sample_content/assets/hls-bunny-166/playlist.m3u8: Unknown error 2004
I/IJKMEDIA(17379): SDL_JNI_DetachThreadEnv: [17523]
D/IJKMEDIA(17379): FFP_MSG_ERROR: -2004
E/tv.danmaku.ijk.media.player.IjkMediaPlayer(17379): Error (-2004,0,Unknown error 2004)

**Comment by MiriDevAndro** [comment]
im sorry i had wifi of sorry  i havent see sorry , thnx for replay
