### ISSUE TITLE
Lock screen notification

### ISSUE THREAD

**Issue by dvasea1** [befovy/fijkplayer#203]
Does suport this library lock screen notification? To control plyer when app is in foreground.

**Comment by befovy** [comment]
This plugin dose not suport lock screen notification.

**Comment by dvasea1** [comment]
Does knows anyone, it's hard to implement this feature?

**Comment by befovy** [comment]
You can follow this https://stackoverflow.com/questions/3170563/android-detect-phone-lock-event to add listener about screen lock.
I don't think it is appropriate to implement this feature in the plugin
