### ISSUE TITLE
这个播放器是否支持通过cookie来请求hls（.m3u8）视频的方法？

### ISSUE THREAD

**Issue by jacksun0124** [befovy/fijkplayer#204]
**Is your feature request related to a problem? Please describe.**
我们现在有个网站是用的是M3U8的视频，但是在请求视频的时候必须要通过附加Cookie来验证用户是否有播放权限。我们网站用HLS.js，在请求视频的时候有个选项"xhr.withCredentials = true; // do send cookies"。 请问咱们这个播放器有没有这样的功能？

**Comment by befovy** [comment]
应该可以通过设置 http headers 实现。
https://fijkplayer.befovy.com/docs/zh/faq.html#%E8%AE%BE%E7%BD%AE-http-%E8%AF%B7%E6%B1%82%E5%A4%B4
