### ISSUE TITLE
ios播放webm格式视频，视频颜色为浅蓝色，android显示正常

### ISSUE THREAD

**Issue by chenyifan88** [befovy/fijkplayer#207]
**To Reproduce**
问题的复现步骤
核心代码

  @override
  void initState() {
    super.initState();
    player.setDataSource(widget.url, autoPlay: true);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Fijkplayer Example")),
        body: Container(
          alignment: Alignment.center,
          child: FijkView(
            player: player,
          ),
        ));
  }

**Expected behavior**
描述清楚你希望的运行结果是什么
- 视频颜色变蓝

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer
- 版本0.7.0

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
 - OS: [e.g. iOS12.4.3]

**Additional context**
其他有关此问题的内容

**Comment by befovy** [comment]
colorSpace 设置不对吗？！

@chenyifan88 
有没有测试文件或者视频播放地址？ 我调试看一下
