### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jeromekai** [befovy/fijkplayer#208]
pod install 

[!] Error installing BIJKPlayer
[!] /usr/bin/curl -f -L -o /var/folders/p5/v30yn3sj2gxdmpklvqcwltxw0000gn/T/d20200410-39032-cjqqpc/file.tgz https://github.com/befovy/ijkplayer/releases/download/f0.5.1/IJKPlayer.tar.gz --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   629  100   629    0     0    113      0  0:00:05  0:00:05 --:--:--   149
curl: (7) Failed to connect to github-production-release-asset-2e65be.s3.amazonaws.com port 443: Connection refused

**Comment by BestYun** [comment]
我也遇到这个问题，我是将cocoapods版本降到1.7.5，然后全局vpn就解决了

**Comment by jeromekai** [comment]
> 我也遇到这个问题，我是将cocoapods版本降到1.7.5，然后全局vpn就解决了

问题中的下载链接也访问不到，国内有这个有镜像吗？能贡献出来供大家下载吗？

**Comment by BestYun** [comment]
> > 我也遇到这个问题，我是将cocoapods版本降到1.7.5，然后全局vpn就解决了
> 
> 问题中的下载链接也访问不到，国内有这个有镜像吗？能贡献出来供大家下载吗？

国内有没有镜像我没找到，这个问题是网络导致的，群里有人说4G网络能下载，你可以试试
**科学上网**肯定能解决这个问题

**Comment by ikecoolon** [comment]
现在用vpn全局也无法下载 cocoapods 1.10.1,怎么解决呢

**Comment by befovy** [comment]
周日会解决此问题

**Comment by judastatus** [comment]
> 周日会解决此问题

你好，这个解决了吗？

**Comment by befovy** [comment]
已经解决了
