### ISSUE TITLE
[BUG]ios 版本panelBuilder: fijkPanel2Builder()点击全屏按钮后是横屏的，然后APP进入后台再切回当前界面，这时是竖屏

### ISSUE THREAD

**Issue by BestYun** [befovy/fijkplayer#209]
环境：
ios 13.3
fijkplayer 0.7.0

```
Container(
  child: FijkVolumeWatcher(
    watcher: null,
    showToast: false,
    child: FijkView(
      player: player,
      panelBuilder: fijkPanel2Builder(),
    ),
),

```
点击全屏按钮，会进入横屏状态，但是将APP切换到后台时，再切换会app时，这个时候状态就变成竖屏全屏了

[横屏状态](http://img.cloudnear.cn/WechatIMG167.jpeg)
[竖屏状态](http://img.cloudnear.cn/WechatIMG165.jpeg)

不知道这算不算bug？如果再次进入APP仍然想要继续保持横屏该如何做？

**Comment by befovy** [comment]
算一个 bug。 

@all-contributors please add @BestYun  for bug

**Comment by befovy** [comment]
0.7.2 版本已修复
