### ISSUE TITLE
Provider 丢失[BUG]

### ISSUE THREAD

**Issue by pslxx** [befovy/fijkplayer#211]
我在播放页面 注入了几个Provider 比如弹幕列表数据,已经页面的相关数据,
这些Provider是会随着dispose销毁的,属于页面级别,不属于APP级别的

但是在全屏之后 这个Provider就找不到了
但是全局的Provider是可以的,比如用户登陆信息..

我看了代码,是跳转到一个新的页面,然后自定义UI 也是重新渲染了一遍,但是这个全屏的Page 我是没办法注入 Provider

不知道有什么办法处理,或者可以开放自定义全屏视图的参数

**Comment by pslxx** [comment]
这个问题,解决了, 在buildPanel的时候 直接把Provider引用传到panel里
目前是这么解决的,功能暂时实现了,但是不确定可有i什么问题

**Comment by befovy** [comment]
插件中的进入全屏确实是 ”跳转到一个新的页面“。

**Comment by befovy** [comment]
panelBuilder 有一个参数 FijkData ，里面可以放一些数据。
这些数据在 全屏和非全屏切换时不会销毁，是否可以实现你的需求。@pslxx
