### ISSUE TITLE
[BUG]切换全屏的过程中,会出现overflowed的情况

### ISSUE THREAD

**Issue by pslxx** [befovy/fijkplayer#215]
我这边 全屏和非全屏下 使用的是不同的Panel,然后布局有些差异
在切换全屏的过程动画中,会出现overflowed的情况
第一次切换全屏的时候,首先 原始的界面 底部会出现overflowed大概几个点左右
然后会报全屏的panel 右边会overflowed 几百个像素.
退出全屏 再进入全屏的之后,就只会报原始界面的底部,不会包panel的

初步觉得是PageRouteBuilder的动画执行过程中,界面的宽高有问题...导致的,

不知道是不是我布局的的问题,但是我自己检查了下,正常情况下,和多设备测试下都不会出现overflowed的

**Comment by befovy** [comment]
请看看插件中自带panel 是否有这个问题，如果没有的话。那很大可能是你写的panel 有问题
