### ISSUE TITLE
[BUG]当设置了 强制竖屏只会,IOS 全屏,界面就有问题了

### ISSUE THREAD

**Issue by pslxx** [befovy/fijkplayer#216]
```
//  await SystemChrome.setPreferredOrientations([
//    DeviceOrientation.portraitUp,
//    DeviceOrientation.portraitDown
//  ]);//强制竖屏
```
APP启动的时候 如果设置 强制竖屏,那么在iOS再全屏,整个布局方向就不对了`

**Comment by befovy** [comment]
你希望的"强制竖屏"调用以后，如果点击视频全屏，希望切到横屏吗？

**Comment by pslxx** [comment]
是的,首先,我不希望APP可以跟随手机进行横屏旋转,
所以我设置强制竖屏.
但是设置了强制竖屏之后,.iOS 在播放视频全屏之后,还是竖屏,
也就是全屏的这个PageRuter,显示在竖屏的分辨率下.

**Comment by whkgmz** [comment]
@pslxx 一样的问题，看了看源码，貌似作者全屏时有判断视频宽、高大小比较问题，你可以尝试一下换一个宽比高大的视频。
