### ISSUE TITLE
引入fijkplayer插件后IOS启动APP会自动暂停其他声音

### ISSUE THREAD

**Issue by pan365wang** [befovy/fijkplayer#219]
引入fijkplayer插件后IOS启动APP会自动暂停其他声音，如音乐播放器(酷狗音乐背景音乐播放)，直播等。并没有调用fijkplayer播放视频,只要yaml引入编译就会出现该BUG。IOS 13.4,IP6s，Flutter 1.12.13+hotfix.8,Dart 2.7.0,XCode11.4.1

**Comment by pan365wang** [comment]
android 正常

**Comment by befovy** [comment]
0.7.3 版本修复此问题

**Comment by pan365wang** [comment]
如果进程双击被杀启动APP确实已经修复了。但，启动APP后，进入播放视屏的界面，再次退出视屏播放进入首页，视频资源释放了 player?.release();player?.dispose();，再次按Home进入后台，播放三方声音，启动APP(还在内存中)，声音依然会被暂停。
