### ISSUE TITLE
[BUG]视频播放完成时，监听获取到的播放进度值是小于视频实际时长的。

### ISSUE THREAD

**Issue by dev-zhang** [befovy/fijkplayer#220]
**Describe the bug**
清晰描述你遇到了什么问题。
在播放器的进度监听中，当player.value.state切换到FijkState.completed时，currentPos小于player.value.duration。而且此时player.value.completed的值是false。
这会引起两个问题：
1. 部分严格依赖播放进度（player.value.currentPos)的业务逻辑无法触发
2. 视频播放完成后，在UI的进度展示上播放进度和视频时长不相等

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
有问题请自己先努力尝试解决。
尤其是一些已经在错误输出中给出了可能的解决办法的问题

我运行了仓库中的example，是同样的情况。

**To Reproduce**
问题的复现步骤
1. 添加播放器的onCurrentPosUpdateonCurrentPosUpdate监听
2. 打印并观察当player.value.state == FijkState.completed时，player.value.duration和player.value.currentPos的值

**Expected behavior**
描述清楚你希望的运行结果是什么

当播放完成时（player.value.state == FijkState.completed），player.value.duration和player.value.currentPos的值似乎应该是相等的？

**Screenshots**
如果截图有助于对此问题的理解，一定要附上截图

![image](https://user-images.githubusercontent.com/16589421/80591125-b7dd3b00-8a4f-11ea-85d8-c4b5b869278e.png)

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer
0.7.1

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
iPhone 6s、iOS 13.4.1

**Additional context**
其他有关此问题的内容

**Comment by befovy** [comment]
你好，进度这个问题是 ijkplayer 自身问题。 我会尝试进行修复。

另外，部分严格依赖播放进度（player.value.currentPos)的业务逻辑 可以举个例子吗？
真的需要严格依赖吗？

**Comment by dev-zhang** [comment]
感谢您的回复。
比如一些互动视频的场景（在观看视频的过程中会出一些跟用户互动的环节，比如界面上出现需要用户点击的选项），这种在业务上可能是给定的毫秒值，在给定的节点上做我们自己的业务处理。
在测试过程中发现onCurrentPosUpdateonCurrentPosUpdate的监听大约100~150ms回调一次，假设业务上给定的时间节点是20000ms，由于回调的时间间隔原因，并不一定存在某一次回调的currentPos.inMilliseconds等于20000ms。由于我并不懂音视频的相关知识，所以我不太清楚这是不是一个问题。

**Comment by befovy** [comment]
每一个ms更新一次进度肯定是不行的， 以视频来说，一般每秒24帧，每一帧的时间间隔都很大。不可能每一秒更新进度。
另外进度更新太频繁也影响性能。

你判断可能不能用等于号，等大于等于之类的，具体逻辑自己再想想。

当然， 播放完成时，进度不对确实是一个 bug

**Comment by dev-zhang** [comment]
非常感谢您的解答。

业务上我已经通过类似的方式解决。

另外在播放器切换到播放完成状态时，音频或视频结尾的200ms左右的片段是没有播放出来的

**Comment by befovy** [comment]
0.8.5 版本已经修复此问题
