### ISSUE TITLE
请问视频状态栏是否可以在加载时就显示呢？是否有配置用于显示状态栏，是否有回调函数用于检测状态栏的显示与隐藏呢？

### ISSUE THREAD

**Issue by ziboilihua** [befovy/fijkplayer#221]
请问视频状态栏是否可以在加载时就显示呢？是否有配置用于显示状态栏，是否有回调函数用于检测状态栏的显示与隐藏呢？

**Comment by befovy** [comment]
你好，你说的这些都可以使用自定义 UI 去实现。

默认的UI 没有在加载过程中显示一部分内容，是因为数据还没有获取到。 比如视频时长是要等到回调通知获取时长才能显示的。

**Comment by ziboilihua** [comment]
好的，非常感谢
