### ISSUE TITLE
[BUG]android播放时奔溃，没有log打印出来

### ISSUE THREAD

**Issue by yangchuang64** [befovy/fijkplayer#224]
播放时奔溃，没有log打印出来，以下是关于进程的log

05-06 11:32:02.003 D/MediaPlayerNative( 7377): [notify] : [1170] callback app listenerNotNull=1, send=1
05-06 11:32:02.006 D/MediaPlayerNative( 7377): [notify] : [1170] callback app listenerNotNull=1, send=1
05-06 11:32:02.006 V/PlayerBase( 7377): baseStop() piid=18727
05-06 11:32:02.010 I/MediaPlayer( 7377): [HSM] stayAwake false uid: 10162, pid: 7377
05-06 11:32:02.014 I/MediaProcessHandler( 2008): processOp opType: 1, uid: 10162, pid: 7377
05-06 11:32:02.017 D/MediaPlayerNative( 7377): Action:stop, CurrentState:MEDIA_PLAYER_STOPPED
05-06 11:32:02.017 V/PlayerBase( 7377): baseStop() piid=18727
05-06 11:32:02.017 D/MediaPlayerNative( 7377): Message: Unknown MediaEventType(8), ext1=0, ext2=0x0
05-06 11:32:02.017 D/MediaPlayerNative( 7377): [notify] : [1170] callback app listenerNotNull=1, send=1
05-06 11:32:02.026 I/MediaPlayer( 7377): [HSM] stayAwake false uid: 10162, pid: 7377
05-06 11:32:02.027 I/MediaProcessHandler( 2008): processOp opType: 1, uid: 10162, pid: 7377
05-06 11:32:02.027 W/MediaProcessHandler( 2008): remove target not exist, maybe the UI process: uid: 10162, pid: 7377
05-06 11:32:02.074 D/MediaPlayerNative( 7377): Action:reset_l, CurrentState:MEDIA_PLAYER_IDLE
05-06 11:32:02.075 V/MediaPlayer( 7377): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
05-06 11:32:02.075 V/MediaPlayer( 7377): cleanDrmObj: mDrmObj=null mDrmSessionId=null
05-06 11:32:02.075 V/PlayerBase( 7377): baseRelease() piid=18727 state=4
05-06 11:32:02.075 I/MediaPlayer( 7377): [HSM] stayAwake false uid: 10162, pid: 7377
05-06 11:32:02.076 I/MediaProcessHandler( 2008): processOp opType: 1, uid: 10162, pid: 7377
05-06 11:32:02.076 W/MediaProcessHandler( 2008): remove target not exist, maybe the UI process: uid: 10162, pid: 7377
05-06 11:32:02.076 V/MediaPlayer( 7377): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
05-06 11:32:02.076 V/MediaPlayer( 7377): cleanDrmObj: mDrmObj=null mDrmSessionId=null
05-06 11:32:02.076 I/MediaPlayerNative( 7377): Pid:7377 MediaPlayer destructor MediaPlayer(0x6f19811240)
05-06 11:32:02.079 I/MediaPlayer( 7377): [HSM] stayAwake false uid: 10162, pid: 7377
05-06 11:32:02.079 I/MediaProcessHandler( 2008): processOp opType: 1, uid: 10162, pid: 7377
05-06 11:32:02.079 W/MediaProcessHandler( 2008): remove target not exist, maybe the UI process: uid: 10162, pid: 7377
05-06 11:32:02.361 I/PGServer( 2211): report state:2 event type:2 pid:7377 uid:10162 pkg:null to pid: 1219
05-06 11:32:02.362 I/PGServer( 2211): report state:2 event type:2 pid:7377 uid:10162 pkg:null to pid: 2211
05-06 11:32:02.362 D/PGAudioState( 2211): audio type:out state:stop pid:7377 uid:10162
05-06 11:32:02.999 I/AudioFlinger(  646): pid(7377):mVol=1.000000, tVol=0.316229, pVol=1.000000, sVol=1.000000, scale=1.000000, output=13, mDevice=0x2, mStreamType=3
05-06 11:32:04.000 I/AudioFlinger(  646): pid(7377):mVol=1.000000, tVol=0.316229, pVol=1.000000, sVol=1.000000, scale=1.000000, output=13, mDevice=0x2, mStreamType=3
05-06 11:32:04.998 I/AudioFlinger(  646): pid(7377):mVol=1.000000, tVol=0.316229, pVol=1.000000, sVol=1.000000, scale=1.000000, output=13, mDevice=0x2, mStreamType=3
05-06 11:32:05.998 I/AudioFlinger(  646): pid(7377):mVol=1.000000, tVol=0.316229, pVol=1.000000, sVol=1.000000, scale=1.000000, output=13, mDevice=0x2, mStreamType=3
05-06 11:32:06.998 I/AudioFlinger(  646): pid(7377):mVol=1.000000, tVol=0.316229, pVol=1.000000, sVol=1.000000, scale=1.000000, output=13, mDevice=0x2, mStreamType=3
05-06 11:32:07.998 I/AudioFlinger(  646): pid(7377):mVol=1.000000, tVol=0.316229, pVol=1.000000, sVol=1.000000, scale=1.000000, output=13, mDevice=0x2, mStreamType=3
05-06 11:32:08.998 I/AudioFlinger(  646): pid(7377):mVol=1.000000, tVol=0.316229, pVol=1.000000, sVol=1.000000, scale=1.000000, output=13, mDevice=0x2, mStreamType=3
05-06 11:32:09.998 I/AudioFlinger(  646): pid(7377):mVol=1.000000, tVol=0.316229, pVol=1.000000, sVol=1.000000, scale=1.000000, output=13, mDevice=0x2, mStreamType=3
05-06 11:32:10.064 I/AppManager( 2211): remove toast view when pkg dead, pid : 7377
05-06 11:32:10.312 I/DebugKeepScreenOn( 1219): setHoldScreenLocked newHoldScreen:null currentHoldScreen:Session{816a1e9 7377:u0a10162} wakeLockState:true
05-06 11:32:10.330 I/Zygote  (  593): Process 7377 exited due to signal 9 (Killed)

**Comment by befovy** [comment]
@yangchuang64 怎么回事？
