### ISSUE TITLE
[Question]怎么缩短onCurrentPosUpdate的回调时间

### ISSUE THREAD

**Issue by hwh97** [befovy/fijkplayer#225]
监听调用 _fplayer.onCurrentPosUpdate，回调大概在130毫秒左右，有方法可以缩短这个回调时间么？谢谢

**Comment by befovy** [comment]
目前没有接口缩短 onCurrentPosUpdate 回调时间。

你是有什么需求要进一步缩短这个时间呢

**Comment by hwh97** [comment]
跟这个老哥一样也是需要精准点的时间弹出一些交互，但是现在80ms-150ms就有点奇怪 #220

**Comment by befovy** [comment]
嗯，可以增加一个选择，控制一下这个回调间隔。
有兴趣参与吗？ @hwh97

**Comment by hwh97** [comment]
我找不到在哪改😂

**Comment by befovy** [comment]
那我尽快实现吧，感谢支持

**Comment by befovy** [comment]
0.8.3 版本增加了接口，进行调整

https://fijkplayer.befovy.com/docs/zh/ijk-option.html#pos-update-interval

**Comment by befovy** [comment]
@all-contributors please add @im-ling for code
