### ISSUE TITLE
takesnapshot error -1

### ISSUE THREAD

**Issue by qq329401134** [befovy/fijkplayer#229]
代码：想获取video的SnapShot
 File video = await ImagePicker.pickVideo(source: ImageSource.gallery);

  FijkPlayer player = FijkPlayer();
  await player.setOption(FijkOption.hostCategory, "enable-snapshot", 1);
  await player.setDataSource(video.path);

  Uint8List videoImage = await player.takeSnapShot();
不知道为啥 error: -1

I/IJKMEDIA(32531): av_version_info: ff4.0--ijk0.8.25--20191031--001
I/IJKMEDIA(32531): ijk_version_info: f0.7.2
I/flutter (32531): [inf] 2020-05-11 09:57:20.243988 [fijk] create player id:4
D/mali_winsys(32531): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/flutter (32531): [inf] 2020-05-11 09:57:20.250009 [fijk] FijkPlayer{id:4} setOption k:enable-snapshot, v:1
D/FlutterView(32531): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@132b908
D/mali_winsys(32531): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/flutter (32531): [inf] 2020-05-11 09:57:20.261953 [fijk] FijkPlayer{id:4} invoke setDataSource /data/user/0/com.ygmymall.app/cache/image_picker3346656263240090628
I/flutter (32531): [inf] 2020-05-11 09:57:20.271175 [fijk] FijkPlayer{id:4} state changed to FijkState.initialized <= FijkState.idle
I/flutter (32531): [inf] 2020-05-11 09:57:20.275186 [fijk] FijkPlayer{id:4} takeSnapShot
E/IJKMEDIA(32531): ffp take snap_shot error: -1

**Comment by befovy** [comment]
@qq329401134 你调用 takesnapshot 的时候，视频首帧还没有播放出来吧

**Comment by qq329401134** [comment]
> @qq329401134 你调用 takesnapshot 的时候，视频首帧还没有播放出来吧

哈哈哈  对啊，我是只准备获取该视频的首帧图片而已只要这张照片

**Comment by befovy** [comment]
不行的。 takesnapshot 是视频播放是的截图。

**Comment by qq329401134** [comment]
> 不行的。 takesnapshot 是视频播放是的截图。

好的 谢谢了
