### ISSUE TITLE
[BUG]iOS 13.1 录音异常退出

### ISSUE THREAD

**Issue by terry8204** [befovy/fijkplayer#231]
**Describe the bug**
iOs 13.1 手机录音异常：提示
required condition is false: IsFormatSampleRateAndChannelCountValid

**What attempts have you made to resolve this error ?**
看网上说的是没权限，我设置已经给了录音权限应用，不知道是不是格式不能这样写，安卓可以。

调用格式：
new AudioController(CommonFormat.Int16, 8000, 1, true);

**Comment by befovy** [comment]
你好，这个播放器没有录音功能呀。

**Comment by terry8204** [comment]
有的，安卓都可以录音

**Comment by terry8204** [comment]
不好意思，看错了，录音是调用都另外一个开源组件，谢谢 回复。
