### ISSUE TITLE
[BUG] 播放问题

### ISSUE THREAD

**Issue by hwh97** [befovy/fijkplayer#232]
**Describe the bug**
调用了一次暂停，继续播放就会出现这个问题
`await _fplayer.pause();`
options只设置了   
` await _fplayer.applyOptions(FijkOption()..setPlayerOption('pos-update-interval', 25));`

I/IJKMEDIA( 9213): ffp_toggle_buffering: error: -5
I/IJKMEDIA( 9213): ffp_toggle_buffering: eof
E/tv.danmaku.ijk.media.player.IjkMediaPlayer( 9213): Error (-5,0,I/O error)
I/flutter ( 9213): [err] 2020-05-12 16:17:05.857247 [fijk] FijkPlayer{id:6} errorListerner: FijkException(-5, I/O error)
I/flutter ( 9213): [inf] 2020-05-12 16:17:05.859959 [fijk] FijkPlayer{id:6} state changed to FijkState.error <= FijkState.started
I/BufferQueueProducer( 9213): [SurfaceTexture-0-9213-5](this:0x72f3f22000,id:5,api:2,p:9213,c:9213) queueBuffer: slot 1 is dropped, handle=0x7329a83b80
I/BufferQueueProducer( 9213): [SurfaceTexture-0-9213-5](this:0x72f3f22000,id:5,api:2,p:9213,c:9213) queueBuffer: slot 0 is dropped, handle=0x7329a83b00

**What attempts have you made to resolve this error ?**
无

**To Reproduce**
调用了一次暂停，继续播放就会出现这个问题
`await _fplayer.pause();`

**fijkplayer version**
Which version you used.
0.8.3

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
 - Device:Meizu pro7-H
 - OS:Android7.0

**Comment by hwh97** [comment]
错误日志补充
W/GLConsumer( 9213): [SurfaceTexture-0-9213-6] bindTextureImage: clearing GL error: 0x500
E/IJKMEDIA( 9213): Invalid NAL unit size (20103 > 2258).
E/IJKMEDIA( 9213): Error splitting the input into NAL units.
W/GLConsumer( 9213): [SurfaceTexture-0-9213-6] bindTextureImage: clearing GL error: 0x500
W/GLConsumer( 9213): [SurfaceTexture-0-9213-6] bindTextureImage: clearing GL error: 0x500
I/IJKMEDIA( 9213): ffp_toggle_buffering: error: -5
I/IJKMEDIA( 9213): ffp_toggle_buffering: eof
E/tv.danmaku.ijk.media.player.IjkMediaPlayer( 9213): Error (-5,0,I/O error)
D/BufferQueueProducer( 9213): [SurfaceTexture-0-9213-6](this:0x72f3692000,id:6,api:2,p:9213,c:9213) queueBuffer: fps=29.98 dur=1034.03 max=39.01 min=25.66
I/flutter ( 9213): [err] 2020-05-12 16:25:02.336684 [fijk] FijkPlayer{id:7} errorListerner: FijkException(-5, I/O error)
I/flutter ( 9213): [inf] 2020-05-12 16:25:02.340354 [fijk] FijkPlayer{id:7} state changed to FijkState.error <= FijkState.started
I/BufferQueueProducer( 9213): [SurfaceTexture-0-9213-6](this:0x72f3692000,id:6,api:2,p:9213,c:9213) queueBuffer: slot 0 is dropped, handle=0x72f3782f00

**Comment by befovy** [comment]
pause 之后间隔多久再 play 的？ 可能是网络断开了，没有重连

**Comment by hwh97** [comment]
好像也就几分钟，阿里云oss的视频，连的wifi，有概率出现这个问题。

**Comment by befovy** [comment]
@hwh97 可以设置一些 ijk 或者 ffmpeg 支持的断网重连 option
你可以去这里看看 https://github.com/befovy/ijkplayer/issues/29

**Comment by hwh97** [comment]
好的谢谢。我查到的资料
断网自动重新连接
url前接上ijkhttphook:，如String url = "ijkhttphook:http://baobab.wdjcdn.com/14564977406580.mp4";
然后设置
`

((IjkMediaPlayer)mediaPlayer).setOnNativeInvokeListener(new IjkMediaPlayer.OnNativeInvokeListener() {
            @Override
            public boolean onNativeInvoke(int i, Bundle bundle) {
                return true;
            }
        })`
但是这个回调要回原生设置😂
