### ISSUE TITLE
[BUG] 动态切换视频源界面无法渲染

### ISSUE THREAD

**Issue by sixd** [befovy/fijkplayer#233]
RTSP视频源在播放过程中，动态切换到另一个视频源，画面定格在前一个视频源的最后一帧，当前视频源无法渲染。后台日志显示已正常开始渲染。
切换视频源过程：player.reset();player.setDataSource("...");

**Comment by befovy** [comment]
请按照issues 格式补充完整信息

**Comment by sixd** [comment]
更新版本到0.8.3已正常
