### ISSUE TITLE
Plugin should initialise native libraries on demand

### ISSUE THREAD

**Issue by ened** [befovy/fijkplayer#234]
Currently, as soon as the plugin is loaded, it will call out to load the IJK native libraries.
This is not necessary until the user has requested playback of a resource.

The plugin could keep a static flag if the native libraries have been initialised and only do it when it is not done, yet.

Will prepare a PR...

**Comment by befovy** [comment]
Plugins create native IjkMediaPlayer when flutter load plugin.
See here https://github.com/befovy/fijkplayer/blob/master/android/src/main/java/com/befovy/fijkplayer/FijkPlugin.java#L110

I found the first flutter  TextureRegistry.SurfaceTextureEntry  is always black, so I create player and setSurface when load plugin. Then when the user create player, the second and later TextureRegistry.SurfaceTextureEntry works.

**Comment by ened** [comment]
@befovy understand the workaround, thank you. We may need to revisit the reason for it.
Our app is using background services heavily, including plugins, therefore fijkplayer currently creates & releases the surface even when the App is in BG.

As a initial workaround, could you guard L110 like so:

``` java
if (registry.context() instanceof Activity) {
        final FijkPlayer player = new FijkPlayer(plugin);
        player.setupSurface();
        player.release();
}
```

Similar in https://github.com/befovy/fijkplayer/blob/master/android/src/main/java/com/befovy/fijkplayer/FijkPlugin.java#L121, although this code should just move to https://github.com/befovy/fijkplayer/blob/master/android/src/main/java/com/befovy/fijkplayer/FijkPlugin.java#L138.

**Comment by befovy** [comment]
Add new argument for FijkPlayer constructor.
Just create FijkPlayer and setSurface but dose not create IjkMediaPlayer.

**Comment by ened** [comment]
Sorry, I can't follow?

**Comment by befovy** [comment]
Actually, this line loads the native libraries.
https://github.com/befovy/fijkplayer/blob/6207026988100ebd1a3ada5723a669d15f4909d5/android/src/main/java/com/befovy/fijkplayer/FijkPlayer.java#L95
