### ISSUE TITLE
延时太大

### ISSUE THREAD

**Issue by li-fei** [befovy/fijkplayer#235]
你好，用Flutter播放rtsp视频的时候，延时好大，有好几秒钟，有什么低延时的接口吗？

**Comment by befovy** [comment]
延时涉及到的问题挺多的，协议相关、缓存相关等等。
但是和 flutter 没啥关系。
可以直接使用 ijkplayer 运行起来调试，研究下 ijkplayer 的option，尝试设置修改下。

**Comment by marcosicp** [comment]
any news? have the same issue here but only with old GPU devices.

**Comment by befovy** [comment]
> any news? have the same issue here but only with old GPU devices.

@marcosicp Please see #176，I think it will help you
