### ISSUE TITLE
iOS 环境无法兼容 Flutter_ffmpeg 插件[BUG]

### ISSUE THREAD

**Issue by SpanishOnion** [befovy/fijkplayer#246]
**Describe the bug**
iOS 环境下，同时引用 Flutter_ffmpeg 与 ijkplayer 将无法播放视频，页面直接卡死，没有闪退。

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
尝试删除 `Flutter_ffmpeg` 组件，则代码正常运行

**To Reproduce**
问题的复现步骤
1. `pubspec.yaml` 添加 `flutter_ffmpeg: 0.2.10` 及 `fijkplayer: 0.8.4`
2. 执行 `flutter run`
3. 进入视频播放页后，界面直接卡死，无法进行任何操作。
4. 报错如下：

```bash
ff_read (39): EXC_BAD_ACCESS (code=1, address=0x0)
```

**Expected behavior**

希望能够正常播放视频，或者能够提供 `flutter_ffmpeg` 的 `execute` 功能，例如：

```dart
final _ffmpeg = FlutterFFmpeg();
final result = await _ffmpeg.execute(
   '-ss $cropVideoStartTime -t $videoDuration -accurate_seek -i '
   '$path -codec copy -avoid_negative_ts 1 $generatedPath'
);
```

使用 ijkplayer 的视频 app 开发者大概率有裁剪视频、上传视频的需求，目前裁剪视频也只能使用 `flutter_ffmpege`，所以希望大佬能够修复此问题。

**Screenshots**
iOS 报错截图如下：

![ios_error](https://user-images.githubusercontent.com/27147542/83324978-518c4800-a29b-11ea-8e33-f824190d7db7.png)

**fijkplayer version**
Which version you used.
`0.8.4`

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
 - Device: [e.g. iPhone6S]
 - OS: [e.g. iOS13.5]

**Additional context**

flutter doctor:

![flutter_doctor](https://user-images.githubusercontent.com/27147542/83325187-14c15080-a29d-11ea-8a93-2dd2ede57626.png)

**Comment by befovy** [comment]
嗯，我是有这个打算的。这个工作比较大，需要时间

**Comment by SpanishOnion** [comment]
好的，谢谢大佬回复，坐等修复😁

**Comment by Gaoxichao** [comment]
> 嗯，我是有这个打算的。这个工作比较大，需要时间

大佬，修复这个插件了吗，现在项目崩溃了，很紧急，不知道咋搞。。。

**Comment by quanke** [comment]
大佬，我也需要上传视频，处理视频，坐等修复

**Comment by aytunch** [comment]
Hi @befovy :)
I just had the same error while trying to encode with ffmpeg. Is there a solution for this? Open to suggestions, thanks.

**Comment by shichunlei** [comment]
与flutter_ffmpeg兼容问题

遇到相同的问题，希望能够解决

![1603797792934](https://user-images.githubusercontent.com/7146745/97295154-e5cdfb80-1889-11eb-8295-393fcc9fd899.jpg)

**Comment by aytunch** [comment]
@shichunlei I opened an issue in ffmpeg_flutter repo and the author stated that the problem needs to be solved mostly in fijkplayer/ijkplayer side. Here is the issue: [Flutter-ffmpeg with FijkPlayer](https://github.com/tanersener/flutter-ffmpeg/issues/219) If you can experiment and understand the `SDL` stuff, please share here.

**Comment by mrvancor** [comment]
Faced with it. Maybe up ffmpeg to 4.4 solve this problem?

**Comment by 5115191** [comment]
同样的问题

**Comment by befovy** [comment]
看到有一个库，可以解决这个问题，但是我没试过。 
https://pub.dev/packages/flutter_ffmpeg_fijkplayer

**Comment by aytunch** [comment]
@befovy flutter_ffmpeg is no more being used. Instead [ffmpeg_kit](https://github.com/tanersener/ffmpeg-kit) is used.

**Comment by kartik1225** [comment]
@aytunch 
> @befovy flutter_ffmpeg is no more being used. Instead [ffmpeg_kit](https://github.com/tanersener/ffmpeg-kit) is used.

Is that solves this issue?
