### ISSUE TITLE
Bitcode for IJKPlayer

### ISSUE THREAD

**Issue by priezz** [befovy/fijkplayer#248]
@befovy , can you please include bitcode when you compile IJKPlayer? It is the only library, which prevents out app to be compiled with bitcode, so I will appreciate a lot

**Comment by befovy** [comment]
@priezz hi，you can build ijkplayer yourself.
follow this guild https://fijkplayer.befovy.com/docs/zh/replace-ijkplayer.html#gsc.tab=0
build and replace ijkplayer

**Comment by priezz** [comment]
Would it be enough to copy `IJKPlayer.framework` to `ios/frameworks` without touching Flutter and Android parts?
Btw, is there any downside of having it available with bitcode for everyone?

**Comment by befovy** [comment]
```diff

# // un comment three lines below
+   s.preserve_paths = 'Frameworks/*.framework'
+   s.vendored_frameworks = 'Frameworks/IJKPlayer.framework'
+   s.xcconfig = { 'LD_RUNPATH_SEARCH_PATHS' => '"$(PODS_ROOT)/Frameworks/"' }

-   # s.dependency 'BIJKPlayer', '~> 0.3.8'  // comment this line
```

-------

There is no downside of enable bitcode, just no enough time

**Comment by befovy** [comment]
bitcode is enabled from version 0.8.5

**Comment by priezz** [comment]
Still does not work with 0.8.5 (ijkplayer 0.7.6). Looks like it is still distributed w/o bitcode:
```
bitcode bundle could not be generated because '.../ios/Pods/BIJKPlayer/IJKMediaPlayer.framework/IJKMediaPlayer(IJKKVOController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '.../ios/Pods/BIJKPlayer/IJKMediaPlayer.framework/IJKMediaPlayer' for architecture armv7
```
(doing archival)

**Comment by befovy** [comment]
I have opened bitcode https://github.com/befovy/fijkplayer/commit/a0f1ad2e2e10a2bdb39d63bfabe4175793ccebc7.
And the github action build iOS succeed.
If you still have problems about bitcode, can you try to resolve it and then make a pr?

**Comment by sayan-futurehook** [comment]
Bitcode is still not supported for fijkplayer pub version 0.10.1
