### ISSUE TITLE
IOS项目中使用了ijkplayer，出现冲突

### ISSUE THREAD

**Issue by vishellhj** [befovy/fijkplayer#251]
在本来的IOS项目编译使用了IJKPlayer，引入flutter的时候显示冲突
于是将项目中本来的编译好的IJKPlayer干掉，直接使用POD过来的befovy/ijkplayer，结果IJKFFMoviePlayerController缺少了view，之前的项目无法运行。

请问这个可以如何解决？
这个befovy/ijkplayer能跟bilibili那个保持一致使用？

**Comment by vishellhj** [comment]
或者其实应该改个命名，使得原生的部分可以用回bilibili的那个ijkplayer

**Comment by befovy** [comment]
@vishellhj 引入两个不同的版本你不需要考虑包大小问题吗

befovy/ijkplayer 简单改下可以完全兼容 Bilibili/ijkplayer 的

**Comment by vishellhj** [comment]
考虑呀，所以我本来就是把原本原生的IJKPlayer给干掉，但是发现报错了，原生的IJKFFMoviePlayerController这个里面是有一个view的，使用befovy/ijkplayer的话就获取不到这个view了，原生这个view就是用来放视频用的，也去不掉

**Comment by vishellhj** [comment]
@befovy 缺少了view应该如何改，这个有个示例吗

**Comment by befovy** [comment]
befovy/ijkplayer 中没有编译这个文件 IJKFFMoviePlayerController.m
你可以改一下工程配置，把它加上

**Comment by befovy** [comment]
把之前 bilibili/ijkplayer 的头文件 
`#import <IJKMediaFramework/IJKMediaFramework.h>`
换成下面的就行

`#import <IJKMediaPlayer/IJKMediaPlayer.h>`

befovy/ijkplayer 编译输出的产物是兼容 bilibili/ijkplayer 0.8.8 版本的
