### ISSUE TITLE
[BUG] couldn't find "libijkffmpeg.so"

### ISSUE THREAD

**Issue by ifredom** [befovy/fijkplayer#255]
**bug 描述**

清晰描述你遇到了什么问题。
![image](https://user-images.githubusercontent.com/13759936/84477263-ef333e80-acc1-11ea-9a6a-dbe1a118e6da.png)

 试了试卸载重装，还是不行.

 fijkplayer: 0.8.4
flutter version: 1.17.2

**Comment by befovy** [comment]
你这是打包的时候遇到问题了吧， 看看 apk 解压缩后都有啥

**Comment by ifredom** [comment]
重新安装了一下插件OK了，不知缘故
