### ISSUE TITLE
希望增加横向进度手势或者将FijkSlider引入control

### ISSUE THREAD

**Issue by fangshengfy** [befovy/fijkplayer#256]

**Comment by fangshengfy** [comment]
现在的FijkSlider应该是通过callback来设置进度的，在FijkSlider外无法修改进度位置，横向手势的进度无法与FijkSlider统一

**Comment by befovy** [comment]
你是想增加左右滑动手势控制 seek 是吧，但是发现自己加的代码活动时 slider 进度不能跟随移动。

我的建议是，如果要自定义 UI， 就完全重新写 UI，可以把 panel 代码复制去修改，不要想把 panel 或者 panel2 的UI 通过接口和新的自定义 UI 融合起来，这样行不通。直接复制文件修改就好了。
