### ISSUE TITLE
[Bug]android机上，视频地址url中含有空格时，报http400

### ISSUE THREAD

**Issue by a940582450** [befovy/fijkplayer#257]
你好，我在使用的时候发现，在android机上，当视频地址url中包含空格的时候，播放的时候会报Server returned 400 Bad Request，其它的视频url可以正常播放。

I/IJKMEDIA(22487): header='HTTP/1.1 400 Bad Request'
W/IJKMEDIA(22487): HTTP error 400 Bad Request

插件版本：0.8.4
flutter版本：flutter 1.12.13+hotfix8

**Comment by befovy** [comment]
你可以先对 url 进行一次编码，去掉空格

**Comment by a940582450** [comment]
这个和对url是否进行编码没有关系吧，url的地址中本身是存在空格的，进行编码之后，总归是要解码的，目前的fijkplayer接受的path参数也是未编码的String类型的

**Comment by a940582450** [comment]
> 你可以先对 url 进行一次编码，去掉空格

这个和对url是否进行编码没有关系吧，url的地址中本身是存在空格的，进行编码之后，总归是要解码的，目前的fijkplayer接受的path参数也是未编码的String类型的

**Comment by befovy** [comment]
我是特指 url 编码，空格等特殊字符会被换掉。这种 url 编码，解码就不需要你关心了，各种 server 端都支持

**Comment by a940582450** [comment]
> 我是特指 url 编码，空格等特殊字符会被换掉。这种 url 编码，解码就不需要你关心了，各种 server 端都支持

感谢耐心的回答
不过我想我可能没有表达清楚。
比如我对“https://videos2.uwa4d.com/01\ 光线追踪简介.1584586406472.mp4” 进行url编码为“%2F%2Fvideos2.uwa4d.com%2F1-1Camera.Render%E6%80%A7%E8%83%BD%E5%BC%80%E9%94%80%E8%BF%87%E5%A4%A7.1582264568484.mp4”，但是目前的fijkplayer开发的接口并不支出传这种进行了编码的url。
代码如下：
final FijkPlayer player = FijkPlayer();
player.setDataSource('%2F%2Fvideos2.uwa4d.com%2F1-1Camera.Render%E6%80%A7%E8%83%BD%E5%BC%80%E9%94%80%E8%BF%87%E5%A4%A7.1582264568484.mp4',autoPlay: true);

这个时候就会报url invalid了。

而如果是：
final FijkPlayer player = FijkPlayer();
player.setDataSource('https://videos2.uwa4d.com/01\ 光线追踪简介.1584586406472.mp4',autoPlay: true);

这个时候就是Server returned 400 Bad Request

所以我其不太明白的是，对url进行编码之后，怎么传递给fijkplayer的接口呢？

**Comment by befovy** [comment]
你别把 http:// 都给编码了呀。
用这个先试试 https://tool.oschina.net/encode?type=4
你上面编码错了

**Comment by a940582450** [comment]
好的，我最初使用的是Uri.encodeComponent(url)来对url进行编码，出来的效果就是将整个https都进行了编码，后来换了Uri.encodeFull(url)就解决了问题。

感谢帮助！
