### ISSUE TITLE
动态更改视频流

### ISSUE THREAD

**Issue by lyh28** [befovy/fijkplayer#26]
在fluuter中，想要动态修改player中的视频流时，无法修改，有什么解决方法吗？

**Comment by befovy** [comment]
@lyh28 你好， `动态修改player中的视频流` 指的是重新 setDataSource 吗？
`setDataSource` 只在 idle 状态可用，需要先调用 `reset` 将播放器状态调整为 idel。
关于播放器状态请参考 [此链接](https://fijkplayer.befovy.com/docs/zh/fijkstate.html#%E7%8A%B6%E6%80%81%E8%BD%AC%E6%8D%A2%E5%9B%BE)

如果还有疑问请补充更多相关信息。

**Comment by lyh28** [comment]
你好是的，当我点击按钮时，调用代码
`await _player.reset();await _player.setDataSource(steam,autoPlay:true);`，画面会卡在上一个视频不动，查看_player的datasource时，依旧是上一个视频的url，对了，我的url是rtmp流。

**Comment by lyh28** [comment]
> @lyh28 你好， **动态修改player中的视频流** 指的是重新 setDataSource 吗？
> `setDataSource` 只在 idle 状态可用，需要先调用 `reset` 将播放器状态调整为 idel。
> 关于播放器状态请参考 [此链接](https://fijkplayer.befovy.com/docs/zh/fijkstate.html#%E7%8A%B6%E6%80%81%E8%BD%AC%E6%8D%A2%E5%9B%BE)
> 
> 如果还有疑问请补充更多相关信息。

**Comment by befovy** [comment]
@lyh28 我确定这是一个 bug，非常抱歉。我会尽快修复

**Comment by lyh28** [comment]
@befovy 好的谢谢。

**Comment by befovy** [comment]
@lyh28 你好，v0.0.8 已经修复。
