### ISSUE TITLE
[BUG]iOS 真机运行时 点击暂停后 退出到后台 再切换到app中 播放器黑屏

### ISSUE THREAD

**Issue by zhuanshuwx** [befovy/fijkplayer#263]
**Describe the bug**
清晰描述你遇到了什么问题。

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
有问题请自己先努力尝试解决。
尤其是一些已经在错误输出中给出了可能的解决办法的问题

**To Reproduce**
问题的复现步骤

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
如果截图有助于对此问题的理解，一定要附上截图

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer

**Smartphone (please complete the following information):**
什么手机设备和系统版本？

**Additional context**
其他有关此问题的内容

**Comment by befovy** [comment]
你用的是什么版本？

**Comment by befovy** [comment]
这个是 flutter 更新 metal 渲染后的一个 bug，在版本已经解决了。
经测试 1.17.3 存在问题。
可以更新到 flutter 最新稳定版，测试过 1.17.5 没问题

**Comment by zhuanshuwx** [comment]
fijkplyer 0.8.4. flutter 1.17.4
