### ISSUE TITLE
[BUG]拖动进度条的时候 拖动后松开 进度条会自动往后退5秒

### ISSUE THREAD

**Issue by zhuanshuwx** [befovy/fijkplayer#264]
**Describe the bug**
清晰描述你遇到了什么问题。

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
有问题请自己先努力尝试解决。
尤其是一些已经在错误输出中给出了可能的解决办法的问题

**To Reproduce**
问题的复现步骤

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
如果截图有助于对此问题的理解，一定要附上截图

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer

**Smartphone (please complete the following information):**
什么手机设备和系统版本？

**Additional context**
其他有关此问题的内容

**Comment by befovy** [comment]
播放状态还是暂停状态拖动进度条呢？ 你给的信息太少了。
但估计是因为 seek 实现是 seek 到关键帧的原因。
你可以找一下并打开精准seek 的 option。

**Comment by zhuanshuwx** [comment]
播放状态和暂停状态都会 往后退几秒的时间

**Comment by befovy** [comment]
@zhuanshuwx 还是无法复现？ 你是怎么弄的呢？
能按照 issue 格式把缺少的线索都补充一下吗？ 再加上播放源的 url。

**Comment by LsFern** [comment]
// SeekTo设置优化，某些视频在SeekTo的时候，会跳回到拖动前的位置，这是因为视频的关键帧的问题，通俗一点就是FFMPEG不 
 兼容，视频压缩过于厉害，seek只支持关键帧，出现这个情况就是原始的视频文件中i 帧比较少
    await player.setOption(
        FijkOption.playerCategory, "enable-accurate-seek", 1);
