### ISSUE TITLE
[BUG]iOS 全面屏的手机 退出全屏没旋转回来 横屏模式

### ISSUE THREAD

**Issue by zhuanshuwx** [befovy/fijkplayer#267]
**Describe the bug**
清晰描述你遇到了什么问题。

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
有问题请自己先努力尝试解决。
尤其是一些已经在错误输出中给出了可能的解决办法的问题

**To Reproduce**
问题的复现步骤

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
如果截图有助于对此问题的理解，一定要附上截图

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer

**Smartphone (please complete the following information):**
什么手机设备和系统版本？

**Additional context**
其他有关此问题的内容

**Comment by befovy** [comment]
@zhuanshuwx 你好，请补充 issue 信息
