### ISSUE TITLE
Rtsp protocol support?

### ISSUE THREAD

**Issue by mciekurs2** [befovy/fijkplayer#27]
Is there any plans of adding rtsp protocol support? Right now i'm making an app in Flutter where I need to use stream with rtsp protocol but I can't find any package that would work with Flutter.

**Comment by befovy** [comment]
Thanks for your attention. 
Add RTSP protocol support need to recompile ffmpeg which fijkplayer used. 
Could you provide a valid RTSP  test url ?
I will add RTSP support in next version which will be released in this weekend.

**Comment by mciekurs2** [comment]
In my app development I used local rtsp stream 'directly' from camera, but for testing I used: rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov

**Comment by befovy** [comment]
@mciekurs2  Hi, release 0.0.9 add rtsp support.

**Comment by mciekurs2** [comment]
@befovy Thx a lot :)
