### ISSUE TITLE
fijkplayer-0.8.4、fijkplayer-0.8.5 不支持播放 pcm 音频

### ISSUE THREAD

**Issue by patton88** [befovy/fijkplayer#273]
问题：fijkplayer-0.8.4、fijkplayer-0.8.5 不支持播放 pcm 音频

问题描述：经测试，fijkplayer-0.8.4、fijkplayer-0.8.5 播放acc等其他音频格式的视频都有声音。播放pcm音频的视频就没有声音，视频能正常播放就是没有声音

测试：曾经尝试自己重新编译，Ubuntu下重新编译 ijkplayer 使用原生Android 的java已经成功支持 pcm音频播放。这是编译成功的配置文件：
[Ubuntu下编译ikplayer-Test08-OK.zip](https://github.com/befovy/fijkplayer/files/4874975/Ubuntu.ikplayer-Test08-OK.zip)

但是 Ubuntu下重新编译 ijkplayer-befovy-Test01 遇到一些问题，还没有成功。

希望：希望大侠下一版更新能够增加对 pcm 音频播放的支持，先行谢过！

**Comment by befovy** [comment]
这种特别的需求最好还是自己能编译替换。
关于怎么编译怎么用，查看 ijkplayer 、fijkplayer 的 github action 配置文件以及文档

**Comment by patton88** [comment]
> 这种特别的需求最好还是自己能编译替换。
> 关于怎么编译怎么用，查看 ijkplayer 、fijkplayer 的 github action 配置文件以及文档

多谢及时回复，有时间再试验编译！

**Comment by befovy** [comment]
那这个 issue 我关了。如果还有什么问题可以联系我单独定制版本。
