### ISSUE TITLE
自定义控制器

### ISSUE THREAD

**Issue by JD-CP** [befovy/fijkplayer#28]
目前是不是还不支持自定义控制器，哈哈哈，自带的那个实在是不太好看...

**Comment by befovy** [comment]
@JD-CP 谢谢关注。

自定义控制器是支持的，文档正在完善中。

等不及的话可以先看看 
```
  FijkView({
    @required this.player,
    this.width,
    this.height,
    this.fit = FijkFit.contain,
    this.panelBuilder = defaultFijkPanelBuilder,
    this.color = Colors.blueGrey,
  });
```


`panelBuilder` 就是用来自定义控制器的

**Comment by befovy** [comment]
@JD-CP  文档来了  https://fijkplayer.befovy.com/docs/zh/custom-ui.html

**Comment by JD-CP** [comment]
> @JD-CP 文档来了 https://fijkplayer.befovy.com/docs/zh/custom-ui.html

哇   楼主效率好高！我也抓紧去学习学习
