### ISSUE TITLE
[BUG] 全屏输入框

### ISSUE THREAD

**Issue by SunStarJ** [befovy/fijkplayer#282]
自定义UI输入框，无法监听键盘弹出，也无法将输入框顶到键盘上方

使用stak嵌套页面，全屏后聊天布局消失，猜测可能是全屏后直接覆盖底部全部布局

可监听到键盘弹出和收回改变panelBuilder 样式

 fijkplayer 0.8.6

Android 和 iOS 都会出现

**Comment by befovy** [comment]
全屏切换后，整个 panel ui 中重新 build 了，销毁重建的。
你的自定义 UI 输入框是不是没有记录状态，重新 build panel 后就不出现了
