### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhujian1989** [befovy/fijkplayer#283]
-> Installing BIJKPlayer (0.7.6)

[!] Error installing BIJKPlayer
[!] /usr/bin/curl -f -L -o /var/folders/z8/q5ljbrss0xn0njszrxx909jr0000gn/T/d20200710-63109-7zg04g/file.tgz https://github.com/befovy/ijkplayer/releases/download/f0.7.6/IJKMediaPlayer.tar.gz --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   634  100   634    0     0    101      0  0:00:06  0:00:06 --:--:--   162
  0 60.0M    0     0    0     0      0      0 --:--:--  0:05:10 --:--:--     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

看起来是下载不了，我直接访问https://github.com/befovy/ijkplayer/releases/download/f0.7.6/IJKMediaPlayer.tar.gz也没有，是否需要更新下？

**Comment by befovy** [comment]
你的网络问题

**Comment by zhujian1989** [comment]
> 你的网络问题

https://github.com/befovy/ijkplayer/releases/download/f0.7.6/IJKMediaPlayer.tar.gz 这个地址浏览器访问也是404额

**Comment by befovy** [comment]
不是 404，可以下载的

**Comment by befovy** [comment]
可以试下 0.8.7 版本，pod install 应该会快一下
