### ISSUE TITLE
【need help】能否增加一个获取播放速度的接口

### ISSUE THREAD

**Issue by a940582450** [befovy/fijkplayer#286]
你好，
      目前使用fijkplayer时，当进入全屏幕时，panel会重新build，这个时候在UI上无法获取到当前player的播放速度，除非全局进行播放速度的设置，这样做总觉得不太合理，但是如果能够提供一个获取当前player播放速度的接口，那么整个代码层面就会比较优雅了。

**Comment by befovy** [comment]
在 panel 中可以访问 fijkdata 这个 dict，可以读写值。panel会重新build ，fijkdata 不会销毁，可以获取保存的速度
