### ISSUE TITLE
[BUG]ios 运行报缺少arm64库

### ISSUE THREAD

**Issue by didiao11300** [befovy/fijkplayer#287]
1 warning generated.
    1 warning generated.
    Undefined symbols for architecture arm64:
      "___darwin_check_fd_set_overflow", referenced from:
          _RAND_poll in IJKMediaPlayer(rand_unix.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description

pod install 和 pod update fijkplayer --verbose 正常

fijkplayer: ^0.8.7

 - Device: [iPhoneX]
 - OS: [iOS14]

**Comment by im-ling** [comment]
Xcode [11.5 (11E608c)]
Device: [iPhoneX] 
OS: [iOS 13.5.1]
fijkplayer: ^0.8.7
using new build system
运行正常

请确认是否属于以下情况：
1， 是否替换了ijkplayer， build arm64 异常
2，xcode 版本和iOS 14对应异常，https://github.com/krzyzanowskim/OpenSSL/issues/85

**Comment by didiao11300** [comment]
没有替换ijkplayer，还没有跑起来就gg了，Xcode是11.2.1 (11B500)
麻烦大佬

**Comment by didiao11300** [comment]
Installing AFNetworking (4.0.1)
Installing BIJKPlayer (0.7.8)
Installing Bugly (2.5.2)
Installing FMDB (2.7.5)

依赖的BIJKplay是0.7.8，知道是不是版本不匹配

**Comment by didiao11300** [comment]
大佬，我把flutter版本固定刀0.8.3，把ios依赖的BIJKPlayer版本固定的0.7.3而不是~>0.7.3 编译通过，0.7.8好像和flutter0.8.7匹配有点问题
