### ISSUE TITLE
[BUG]m3u8 播放器播放m3u8,只播放一段视频不再请求第二个ts流

### ISSUE THREAD

**Issue by didiao11300** [befovy/fijkplayer#288]
flutter: [I]  [15:19:33.618] cache-server#: getFileStream()...远端请求https://yhvideo.qny.uaqmsgg.cn/sp/gc/ms/u8/8316c9f5a6004b46af3df9c36ca6dd6a0.ts 当前下载速度167.3KB/s
flutter: [I]  [15:19:34.618] cache-server#: getFileStream()...远端请求https://yhvideo.qny.uaqmsgg.cn/sp/gc/ms/u8/8316c9f5a6004b46af3df9c36ca6dd6a0.ts 当前下载速度1.9MB/s
flutter: [I]  [15:19:34.828] cache-server#: getFileStream()...远端请求https://yhvideo.qny.uaqmsgg.cn/sp/gc/ms/u8/8316c9f5a6004b46af3df9c36ca6dd6a0.ts 完成:2.3MB
flutter: [I]  [15:19:34.873] FullPlayer#: not init===> update speed
flutter: [inf] 2020-07-14 15:19:34.874233 [fijk] FijkPlayer{id:3} audio rendering started
flutter: [I]  [15:19:34.879] FullPlayer#: _getVideoPlayerWidget()...player:http://127.0.0.1:14587/api/app/vid/m3u8/sp/gc/ms/u8/8316c9f5a6004b46af3df9c36ca6dd6a.m3u8 unknow status
flutter: [I]  [15:19:34.879] FullPlayer#: _getVideoUI()...player:http://127.0.0.1:14587/api/app/vid/m3u8/sp/gc/ms/u8/8316c9f5a6004b46af3df9c36ca6dd6a.m3u8 unknow status
flutter: [inf] 2020-07-14 15:19:34.894364 [fijk] FijkPlayer{id:3} prepared duration 0:01:28.959000
flutter: [inf] 2020-07-14 15:19:34.894921 [fijk] FijkPlayer{id:3} rotate degree 0
flutter: [inf] 2020-07-14 15:19:34.895019 [fijk] FijkPlayer{id:3} size changed (720, 1280)
flutter: [inf] 2020-07-14 15:19:34.895285 [fijk] FijkPlayer{id:3} state changed to FijkState.prepared <= FijkState.asyncPreparing
flutter: [I]  [15:19:34.895] FullPlayer#: isBuffing changed===>false  inited:true buffering:false  playing:false
flutter: [inf] 2020-07-14 15:19:34.895578 [fijk] FijkPlayer{id:3} state changed to FijkState.started <= FijkState.prepared
flutter: [inf] 2020-07-14 15:19:34.933613 [fijk] FijkPlayer{id:3} setupSurface
flutter: [I]  [15:19:34.935] cache-server#: getFileStream()...远端请求https://yhvideo.qny.uaqmsgg.cn/sp/gc/ms/u8/8316c9f5a6004b46af3df9c36ca6dd6a0.ts 完成time cast:107
flutter: [inf] 2020-07-14 15:19:34.937141 [fijk] FijkPlayer{id:3} size changed (720, 1280)
flutter: [inf] 2020-07-14 15:19:34.937316 [fijk] FijkPlayer{id:3} size changed (720, 1280)
flutter: [inf] 2020-07-14 15:19:34.938676 [fijk] FijkPlayer{id:3} video rendering started
flutter: [inf] 2020-07-14 15:19:34.938773 [fijk] FijkPlayer{id:3} setupSurface
flutter: [inf] 2020-07-14 15:19:34.939173 [fijk] FijkPlayer{id:3} size changed (720, 1280)
flutter: [inf] 2020-07-14 15:19:34.939344 [fijk] view setup, vid:3
flutter: [inf] 2020-07-14 15:19:34.939522 [fijk] view setup, vid:3
flutter: [I]  [15:19:35.169] splash#: 缓存图片成功image/34/b2/2t/sd/877c8f97102e49c88ea8c86aae2afdb9.png
flutter: [dbg] 2020-07-14 15:19:44.690170 [fijk] FijkPlayer{id:3} freeze start

**What attempts have you made to resolve this error ?**
架构是fijkplayer + localserver拦截播放器请求；
使用flutter_ijkplayer + localserver 可以正常播放和请求后面的ts流；
 使用fijkplayer + localserver 只能播放一小段和后面的ts流并没有请求；

fijkplayer:0.8.3  依赖 iosBIJKPlayer 0.7.3
android和ios均会出现；

**Comment by didiao11300** [comment]
已解决

**Comment by befovy** [comment]
@didiao11300 怎么解决的呢

**Comment by didiao11300** [comment]
ijkplayer 内部请求，header需要包含contentlength字段，播放器才能判断接收完成，继续第二个ts;

**Comment by didiao11300** [comment]
flutter_ijkplayer内部做了处理，可能不依赖返回的contentlength字段
