### ISSUE TITLE
[BUG]0.8.7版本ios arm64库缺失

### ISSUE THREAD

**Issue by didiao11300** [befovy/fijkplayer#290]
**Describe the bug**
使用你的demo把地址改成远程的0.8.7
如下：
fijkplayer:
    ^0.8.7
    # path: ../

**What attempts have you made to resolve this error ?**
使用0.8.3 并把ios pod依赖的BIJKPlayer强制依赖成0.7.3
没有播放问题

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
ios依赖的BIJKPlayer0.7.8缺少某个arm64的库，日志如下
  Undefined symbols for architecture arm64:
      "___darwin_check_fd_set_overflow", referenced from:
          _RAND_poll in IJKMediaPlayer(rand_unix.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
编译报错，所有版本
Xcode Version 11.2.1 (11B500)

**Comment by didiao11300** [comment]
0.8.7依赖的BIJKPlayer   s.dependency 'BIJKPlayer', '0.7.6' 也有这个问题

**Comment by didiao11300** [comment]
试了裴ijkplayer0.8.3-0.8.7，所依赖的BIJKPlayer0.7.3,0.7.6,0.7.8 除了0.7.3以外都缺少arm64的库

**Comment by befovy** [comment]
谢谢反馈，争取周末搞定

**Comment by befovy** [comment]
@all-contributors please add @didiao11300  for bugs

**Comment by zhouzongfu** [comment]
Undefined symbols for architecture armv7:
      "___darwin_check_fd_set_overflow", referenced from:
          _RAND_poll in IJKMediaPlayer(rand_unix.o)
          _RAND_poll in IJKMediaPlayer(rand_unix.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description

我这也出现了，不过是armv7，是不是同样的原因？

**Comment by im-ling** [comment]
### 1. 个人认为0.8.7 引用的0.7.8 Bijk正常，包含_RAND_poll符号
#### 1.1. 此环境下运行正常
mac环境：
Xcode [11.5 (11E608c)]
macOS Catalina: 10.15.5 (19F101)
手机
Device: [iPhoneX]
OS: [iOS 13.5.1]
fijkplayer: ^0.8.7
Bijk: ^0.7.8
using new build system


#### 1.2.    Bijk 0.7.8 信息：
shasum 249cd44e89ab4a194761160c29afc989e09d12e0
![image](https://user-images.githubusercontent.com/14890206/87844804-5fa62e80-c904-11ea-8144-0a321a40eb09.png)

使用`nm -gUm -arch arm64 IJKMediaPlayer.framework/IJKMediaPlayer`查看实现的符号表，能找到_RAND_poll
![image](https://user-images.githubusercontent.com/14890206/87844932-7305c980-c905-11ea-85ef-6da4e5c9e452.png)

### 2. 建议
使用nm -gUm -arch arm64 IJKMediaPlayer.framework/IJKMediaPlayer查看实现的符号表，看是否能够查到：
若能查到，则大概率项目工程环境异常
若不能查到，可能xcode/OSX系统 版本有关，参考相关链接：
https://openradar.appspot.com/FB7647406,
https://github.com/curl/curl/issues/5210, 
krzyzanowskim/OpenSSL#85,
https://github.com/mono/mono/issues/19393#issuecomment-613639641

**Comment by Gaoxichao** [comment]
> 谢谢反馈，争取周末搞定

请问这个问题解决了吗？我也遇到这个问题，比较严重，无法编译，不兼容

**Comment by befovy** [comment]
@Gaoxichao 你是什么环境呢？ 看上面 liling 说的，没有问题呀

**Comment by MichaelPei** [comment]
@didiao11300 我跟你一样的 Xcode 版本，遇到一样的问题，现在更新到了11.6 就好了。感觉可能是 Xcode 的 bug，你更新一下 Xcode 试试。
@Gaoxichao 如果你也是跟他一样的 Xcode 版本，也可以试试更新一下 Xcode

**Comment by didiao11300** [comment]
更新xcode到11.6问题解决，关闭问题

**Comment by workwing** [comment]
Mac环境：Mac OS Big Sur 1.0.1 (20B29)
Xcode: Version 11.6 (11E708)macOS Catalina: 10.15.5 (19F101)
手机
Device: [iPhoneX]
OS: [iOS 14]
fijkplayer: 0.8.7

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
      objc-class-ref in fijkplayer(FijkPlayer.o)
      objc-class-ref in fijkplayer(FijkPlugin.o)
  "_OBJC_CLASS_$_IJKFFMediaPlayer", referenced from:
      objc-class-ref in fijkplayer(FijkPlayer.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
