### ISSUE TITLE
When seeking video, frames are not changing

### ISSUE THREAD

**Issue by nofaceanime** [befovy/fijkplayer#294]
i am trying to seek the video but when i seek, video frames in player does not change and only changes when i finish seeking video. How can i achieve seeking video along with frame change ?

What i mean you can see a javascript version of player here.
http://jsfiddle.net/Z6FM2/2/

I wanna achieve that frame seeking. How to do that in flutter using fijkplayer ?

**Comment by befovy** [comment]
https://github.com/befovy/fijkplayer/blob/86be12fcefb457a4eb8674dc43876dc73e2726ba/lib/ui/panel2.dart#L359

Seek happened after slider gesture `onChangeEnd`。You can build your own panel and change this behavior.

**Comment by nofaceanime** [comment]
Thanks i will try that now.
