### ISSUE TITLE
[BUG] iOS中报错 <IJKPlayer/IJKPlayer.h>头文件未找到

### ISSUE THREAD

**Issue by raphaelsoul** [befovy/fijkplayer#308]
**Describe the bug**
在安卓中集成fijkplayer都正常。 在ios模拟器中启动应用时无法启动 报错
```
In file included from /Users/raphaelsoul/.pub-cache/hosted/pub.flutter-io.cn/fijkplayer-0.8.4/ios/Classes/FijkPlayer.m:23:
    /Users/raphaelsoul/.pub-cache/hosted/pub.flutter-io.cn/fijkplayer-0.8.4/ios/Classes/FijkPlayer.h:24:9: fatal error: 'IJKPlayer/IJKPlayer.h' file not found
    #import <IJKPlayer/IJKPlayer.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
搜了一下关键词 没找到相关的issue 
尝试了一下flutter pub cache repair也无效

**To Reproduce**
相关版本
fijkplayer 0.8.4
flutter Channel stable, v1.17.4, on Mac OS X 10.15.6 19G2021, locale en-CN

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
如果截图有助于对此问题的理解，一定要附上截图

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
iOS simulator (on iPhone 11 Pro Max)

**Comment by befovy** [comment]
运行 pod install 的时候，实际安装的 BIJKPlayer 是什么版本？

这块没处理好，  BIJKPlayer 有个版本头文件变了。 版本号只升级了最后一位。

**Comment by befovy** [comment]
可以再 App 的 Podfile 中对 BIJKPlayer 进行版本限制，加上 `pod 'BIJKPlayer', '0.7.3'`。
当然也可以升级 fijkplayer 到最新版本解决此问题。
