### ISSUE TITLE
[BUG]在mac下调试错误

### ISSUE THREAD

**Issue by iperfectapp** [befovy/fijkplayer#31]
MacBook-Air:ios$ pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `fijkplayer` from `.symlinks/plugins/fijkplayer/ios`
Downloading dependencies
Installing FIJKPlayer (0.3.5)

一直卡在这里

**Comment by befovy** [comment]
在 example/ios 目录下，运行 `pod install --verbose` ，需要从 github 下载 cocodpods 依赖，大约60M

**Comment by iperfectapp** [comment]
谢谢，这个问题已经解决，问题又来啦

![image](https://user-images.githubusercontent.com/3021764/63739452-d044f680-c8bf-11e9-8ce0-43484e850d94.png)

播放途中会崩溃

**Comment by befovy** [comment]
@iperfectapp 这个gpu中的崩溃我曾经遇到过，看来是没有解决彻底。
能提供一下你是用的视频地址吗？

**Comment by iperfectapp** [comment]
http://biezhi360.cn:99/ngys.aspx?vod_id=67181&vod_key=20190821%e6%9c%9f




| |
123
邮箱：newton520@163.com
|

签名由 网易邮箱大师 定制

在2019年08月27日 11:52，befovy 写道：

@iperfectapp 这个gpu中的崩溃我曾经遇到过，看来是没有解决彻底。
能提供一下你是用的视频地址吗？

**Comment by befovy** [comment]
我用这个url收流，一直没出现问题，用的是 iphone SE，12.3.1 系统。
你那边怎么能复现概率高一些，就是一直收流吗？ 是否调用其他接口？
有没有别的操作，测试设备的系统版本是什么？
@iperfectapp

**Comment by iperfectapp** [comment]
没有别的操作，我再多测试测试，你有qq吗？邮箱不能发图片




| |
123
邮箱：newton520@163.com
|

签名由 网易邮箱大师 定制

在2019年08月27日 14:48，befovy 写道：

我用这个url收流，一直没出现问题，用的是 iphone SE，12.3.1 系统。
你那边怎么能复现概率高一些，就是一直收流吗？ 是否调用其他接口？
有没有别的操作，测试设备的系统版本是什么？
@iperfectapp

**Comment by befovy** [comment]
add  atomic barrier when swap pixelbuffer , see 1e022ef

**Comment by befovy** [comment]
@iperfectapp Have you tried  branch `bugfix-issue31` ? Is there still the crash？

**Comment by iperfectapp** [comment]
![image](https://user-images.githubusercontent.com/3021764/64181883-dfb4d880-ce99-11e9-80ee-0b94e89e151d.png)
为什么升级到最新版本会出现其他的sdk？

**Comment by befovy** [comment]
这不是最新版出现的其他 sdk， 所有版本都有这个 cocoapods 上发布的sdk， android 也有 jcenter 上发布的sdk。
要不 ijkplayer 哪来呢？ 光只有这几行 dart 代码可做不成一个播放器

**Comment by iperfectapp** [comment]
我在外地网络不好，一直卡在 FIJKPlayer ，有办法吗？

**Comment by befovy** [comment]
FIJKPlayer 的二进制包放在 github 上，没啥好办法。
在 ios 文件夹 运行 `pod install --verbose` 看着下载百分比一点点上涨可能从心理上会好点。

**Comment by iperfectapp** [comment]
我手动下载下来后，能融合到项目中不？




| |
123
邮箱：newton520@163.com
|

签名由 网易邮箱大师 定制

在2019年09月03日 22:56，befovy 写道：

FIJKPlayer 的二进制包放在 github 上，没啥好办法。
在 ios 文件夹 运行 pod install --verbose 看着下载百分比一点点上涨可能从心理上会好点。

**Comment by befovy** [comment]
这个你查  cocoapods 的缓存文件夹相关内容吧，我不太了解

**Comment by befovy** [comment]
released in version 0.1.3
