### ISSUE TITLE
关于全屏

### ISSUE THREAD

**Issue by criusKer** [befovy/fijkplayer#318]
需求是点击列表中的某一项后，视频全屏播放，点击返回返回列表。所以想问下有没有只有全屏的模式，目前试了下只能列表跳到小窗口播放下全屏，再从全屏返回小窗口播放再返回列表

**Comment by befovy** [comment]
UI 方面可以根据自己需求随便用哈，不要被局限了

**Comment by befovy** [comment]
但是插件不提供这个功能
