### ISSUE TITLE
怎么加载本地视频资源

### ISSUE THREAD

**Issue by RainSnowSnow** [befovy/fijkplayer#32]
assets/videos/video.mp4: No such file or directory

**Comment by RainSnowSnow** [comment]
@befovy E/IJKMEDIA(22698): asset:///assets/video.mp4: Protocol not found      提示这个错误是啥意思

**Comment by befovy** [comment]
@RainSnowSnow 是用的 0.1.0 版本吗？

**Comment by RainSnowSnow** [comment]
@befovy  不是，用的 ^0.0.9

**Comment by befovy** [comment]
这个在 0.1.0 才支持

**Comment by RainSnowSnow** [comment]
@befovy 
![image](https://user-images.githubusercontent.com/23568119/63751598-422e3780-c8e2-11e9-83d1-34b1b0196547.png)
0.1.0的flutter run 报错

**Comment by befovy** [comment]
implementation 'com.android.support:support-annotations:28.0.0'
有一个 dependencies  没安装。

gradle sync 跑一下试试

**Comment by RainSnowSnow** [comment]
@befovy 
![image](https://user-images.githubusercontent.com/23568119/63752496-f086ac80-c8e3-11e9-9e59-6c5577c0ebe2.png)
乱码的我也不大清楚，会不会是因为flutter sdk的版本低了

**Comment by befovy** [comment]
不好意思 ， `gradle sync`  不是终端命令。
在 android studio 上有个图标，作用是 gradle sync.
windows 命令行的话，应该是运行项目android 文件夹中的  `gradlew.bat`

**Comment by RainSnowSnow** [comment]
@befovy 
![image](https://user-images.githubusercontent.com/23568119/63753700-2cbb0c80-c8e6-11e9-8505-030e7fcfce6c.png)是哪个啊

**Comment by befovy** [comment]
我刚才试了一下，需要引入 androidx

gradle.properties文件里添加配置：
```
android.useAndroidX=true
android.enableJetifier=true
```
在android studio 编辑器中打开一个 android 目录下的文件，就会出现
![image](https://user-images.githubusercontent.com/51129600/63754046-c682b980-c8e6-11e9-9b28-bd1690baf63b.png)

**Comment by RainSnowSnow** [comment]
@befovy 
![image](https://user-images.githubusercontent.com/23568119/63755458-490c7880-c8e9-11e9-869f-876403ea086d.png)
还是相同的错误

**Comment by befovy** [comment]
是修改 gradle.properties ，不是 gradle-wrapper.properties

**Comment by RainSnowSnow** [comment]
@befovy 
![image](https://user-images.githubusercontent.com/23568119/63756465-0481dc80-c8eb-11e9-97cf-db86369923c5.png)
视频出来了，但是只要对视频进行操作就报了错

**Comment by befovy** [comment]
好的，这个是 UI 上的问题。能提供一下视频吗？ 我修改一下。

**Comment by RainSnowSnow** [comment]
[4faa8fb6ef849f8333372624a4016dd5.ZIP](https://github.com/befovy/fijkplayer/files/3545203/4faa8fb6ef849f8333372624a4016dd5.ZIP你看下行不行，顺便问下多久能好，因为项目着急，如果短时间不能好，我这次先换其他的

**Comment by RainSnowSnow** [comment]
@befovy

**Comment by RainSnowSnow** [comment]
是出现问题的视频么

------------------ 原始邮件 ------------------
发件人: "befovy"<notifications@github.com>;
发送时间: 2019年8月27日(星期二) 下午4:56
收件人: "befovy/fijkplayer"<fijkplayer@noreply.github.com>;
抄送: "酱子"<1519423369@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [befovy/fijkplayer] 怎么加载本地视频资源 (#32)




好的，这个是 UI 上的问题。能提供一下视频吗？ 我修改一下。

**Comment by befovy** [comment]
那个压缩包用不了，能提供出现问题的视频吗 @RainSnowSnow

**Comment by RainSnowSnow** [comment]
@befovy 
![image](https://user-images.githubusercontent.com/23568119/63760570-27fc5580-c8f2-11e9-858f-59a2a914bda2.png)

请查收下邮箱，因为文件有上传格式限制，我发邮箱了

**Comment by befovy** [comment]
发到我邮箱  befovy@gmail.com 吧，谢谢 @

**Comment by RainSnowSnow** [comment]
@请注意查收

**Comment by befovy** [comment]
@RainSnowSnow  please upgrade to version 0.1.1  
slide value out of range is fixed.

**Comment by RainSnowSnow** [comment]
@befovy 在ios上展示的效果和安卓上一样么，因为我这边开发过程中暂时无法测试ios

**Comment by befovy** [comment]
@RainSnowSnow 我测试过比较基础的内容，效果是一样的。但我无法帮你做更多的测试。
iOS可以使用模拟器测试，但是实际视频会显示为黑屏

**Comment by RainSnowSnow** [comment]
@befovy 
![image](https://user-images.githubusercontent.com/23568119/63902961-5f781880-ca3e-11e9-83f8-6fcc85d0e3eb.png),
当设置为非自动播放状态时，视频会一直处于加载状态，这属于正常的么

**Comment by befovy** [comment]
建议使用 自定义 UI ，重写一个播放器控制面板
https://fijkplayer.befovy.com/docs/zh/custom-ui.html
默认的控制面板确实是这样的

**Comment by befovy** [comment]
@RainSnowSnow 如果还有其他问题，请另开新的 issue， 这个我就先关了

**Comment by RainSnowSnow** [comment]
@befovy 自定义ui有截取视频开头画面作为播放封面图的效果么，还是说要自己找个封面图
