### ISSUE TITLE
ios setDataSource(widget.url, autoPlay: false)，播放mp3的url，autoPlay不起作用，仍然会自动播放

### ISSUE THREAD

**Issue by sogreater** [befovy/fijkplayer#320]
ios setDataSource(widget.url, autoPlay: false)，播放mp3的url，autoPlay不起作用，仍然会自动播放。Android方面正常

**Comment by befovy** [comment]
你好。iOS 设备播放 mp3 url 时 autoPlay 不起作用是吗？ 你使用模拟器吗？ 可否提供个 mp3 播放地址？

**Comment by sogreater** [comment]
是的，我们使用的是真机，不是模拟器，例如：http://mp3.9ku.com/hot/2009/08-27/186947.mp3

**Comment by sogreater** [comment]
怎么样？有结果吗？

**Comment by befovy** [comment]
@sogreater  你好，这边测试没发现在 iOS 手机上设置 autoPlay 不起作用。

倒是发现另外一个问题（设置 autoPlay 之后，play 按钮不起作用）。感谢反馈
