### ISSUE TITLE
如何为播放器添加http-head呢

### ISSUE THREAD

**Issue by 2803404074** [befovy/fijkplayer#322]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by befovy** [comment]
请去看文档，faq 中有。
https://fijkplayer.befovy.com/docs/zh/faq.html#gsc.tab=0

**Comment by kevin406972552** [comment]
上面的链接打不开，谢谢
