### ISSUE TITLE
编译 Android 报错

### ISSUE THREAD

**Issue by ZeroJian** [befovy/fijkplayer#33]
iOS 正常
编译 Android 模拟器报错
/.../flutter/.pub-cache/hosted/pub.flutter-io.cn/fijkplayer-0.1.0/android/src/main/java/com/befovy/fijkplayer/FijkPlayer.java:11: 错误: 找不到符号
import androidx.annotation.NonNull;
                          ^
  符号:   类 NonNull
  位置: 程序包 androidx.annotation
/Users/zerojian/Code/Framework/flutter/.pub-cache/hosted/pub.flutter-io.cn/fijkplayer-0.1.0/android/src/main/java/com/befovy/fijkplayer/FijkPlayer.java:223: 错误: 找不到符号
    public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                              ^
  符号:   类 NonNull
  位置: 类 FijkPlayer
/Users/zerojian/Code/Framework/flutter/.pub-cache/hosted/pub.flutter-io.cn/fijkplayer-0.1.0/android/src/main/java/com/befovy/fijkplayer/FijkPlayer.java:223: 错误: 找不到符号
    public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
                                                        ^
  符号:   类 NonNull
  位置: 类 FijkPlayer
3 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fijkplayer:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by ZeroJian** [comment]
已经修复 androidx 兼容问题, 不是 sdk 问题

**Comment by befovy** [comment]
已在文档中补充相关内容。
https://fijkplayer.befovy.com/docs/zh/install.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
