### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lanhaoo** [befovy/fijkplayer#332]
**Describe the bug**
清晰描述你遇到了什么问题。
iOS 运行项目报错

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
有问题请自己先努力尝试解决。
尤其是一些已经在错误输出中给出了可能的解决办法的问题

**To Reproduce**
问题的复现步骤

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
如果截图有助于对此问题的理解，一定要附上截图
编译报错:
Xcode's output:
↳
    Undefined symbols for architecture arm64:
      "___darwin_check_fd_set_overflow", referenced from:
          _RAND_poll in IJKMediaPlayer(rand_unix.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

Error launching application on iphone.

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer
0.8.7

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
iOS 12.1.4
**Additional context**
其他有关此问题的内容

**Comment by befovy** [comment]
update your xcode. 
Or just google  `___darwin_check_fd_set_overflow`
