### ISSUE TITLE
[BUG] panelBuilder传入的Size应该是FijkView的Size而不应该是视频画面的size

### ISSUE THREAD

**Issue by siyukok** [befovy/fijkplayer#340]
**Is your feature request related to a problem? Please describe.**
使用默认的FijkFit.contain，当视频为竖屏类型视频时，panel的最大显示区域不是FijkView的最大Size，而是视频画面的最大Size

**Describe the solution you'd like**
panelBuilder传入的Size应该是FijkView的Size而不应该是视频画面的size

**Describe alternatives you've considered**

**Additional context**
图片如下，目前使用的是sdk自带的fijkPanel2Builder()

![image](https://user-images.githubusercontent.com/21030561/97660454-9287c300-1aac-11eb-92a3-6e01046dff3e.png)

**Comment by befovy** [comment]
@siyukok panel 就是这样设计的。 你可以修改一下 fijkPanel2Builder 的 fill 参数，就可以实现你想要的效果。
