### ISSUE TITLE
[QA]如何向panelBuilder注入自定义数据

### ISSUE THREAD

**Issue by bedlate** [befovy/fijkplayer#343]
现在直接复制出`defaultFijkPanelBuilder`，改写了UI，在不自己实现`fijkview`的情况下如何注入自定义数据，比如视频ID、清晰度等信息。

我观察到`fijkview`中调用`panelBuilder`使用了`FijkData data`参数，是否可以在外部动态注入数据到`data`呢。

https://github.com/befovy/fijkplayer/blob/eb1107691fa9aeb2095742e5b87a4736491a37ea/lib/core/fijkview.dart#L562

**Comment by befovy** [comment]
这个用个高阶函数就可以实现了。不需要注入数据。
参考 `fijkPanel2Builder`
