### ISSUE TITLE
支持多音轨字幕选择吗？

### ISSUE THREAD

**Issue by zengkid** [befovy/fijkplayer#344]
**Is your feature request related to a problem? Please describe.**
现在播放一个带有多音轨和字幕的视频，默认没有声音和字幕，api文档没有找到相关的音轨和字幕控制？
可以添加这多音轨多字幕选择吗？

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by befovy** [comment]
因为 ijkplayer 对 stream 切换支持不是很好。 切换音频会卡顿。
fijkplayer 没有公开切换音频功能。另外，不支持字幕。

目前可用时间太少，无法支持这些功能。如果有兴趣的话，欢迎贡献PR
