### ISSUE TITLE
非自动播放的时候，希望预览视频封面图

### ISSUE THREAD

**Issue by RainSnowSnow** [befovy/fijkplayer#35]
预览的视频封面图可以截取视频的画面么？

**Comment by befovy** [comment]
这个可以使用自定义UI的接口，在FijkView 之上绘制一个 ImageView。在调用 start 的时候移除 ImageView。
另外在播放器内部可以实现为播放视频第一帧之后进入暂停状态。 不过这个需求需要时间开发。 可以先用上一个方法代替。

**Comment by RainSnowSnow** [comment]
@befovy 

监听的数据：value.duration.inSeconds
用addListener只能监听到最后一帧

**Comment by befovy** [comment]
@RainSnowSnow 没太明白你的意思

**Comment by RainSnowSnow** [comment]
@befovy 
视频播放后，只是监听到了最后的总时长，有啥办法获取到第一帧

**Comment by befovy** [comment]
ok, understood .  You need a notification when first video frame rendered. 
I will add this in next version.

**Comment by RainSnowSnow** [comment]
谢谢

**Comment by befovy** [comment]
@RainSnowSnow release 0.1.2 add this notification.
Please see `audioRenderStart` , `videoRenderStart` in `FijkValue`.

https://fijkplayer.befovy.com/docs/zh/fijkplayer-api.html#fijkvalue
