### ISSUE TITLE
iOS 黑屏

### ISSUE THREAD

**Issue by heqikang** [befovy/fijkplayer#351]
**Describe the bug**
Android运行正常,iOS运行黑屏,有声音。

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
尝试使用不同模拟器还是一样

**To Reproduce**
问题的复现步骤

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
![859](https://user-images.githubusercontent.com/20039536/100203054-119dd900-2f3d-11eb-9924-0197212ad5df.png)
![85999](https://user-images.githubusercontent.com/20039536/100203068-16fb2380-2f3d-11eb-9971-b52b3ab14eb2.png)
![859787](https://user-images.githubusercontent.com/20039536/100203071-19f61400-2f3d-11eb-98d6-7475ce1f00c2.png)

**fijkplayer version**
Which version you used.
fijkplayer: ^0.8.7

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
 - Device: iPhone 11 Pro max
 - OS: iOS 13.6

**Additional context**
其他有关此问题的内容

**Comment by heqikang** [comment]
网络访问权限已开启
![we11](https://user-images.githubusercontent.com/20039536/100204217-92110980-2f3e-11eb-90e8-bd9e708c1761.png)

**Comment by befovy** [comment]
请仔细看readme 这个不支持模拟器
