### ISSUE TITLE
[BUG]关于切换播放源问题

### ISSUE THREAD

**Issue by zrodo** [befovy/fijkplayer#352]
FijkPlayer player = map['vc'];
player.reset();

  String url = '';
  if (action.payload['type'] == 0) {
    url = map['hls'];
  } else {
    url = map['hlsHd'];
  }
  player.setVolume(0);
  player.setDataSource(url, autoPlay: true);
断点看到player的datasource还是之前的地址，不是后来新的地址

**Comment by befovy** [comment]
player 有很多层封装，你说哪里的 datasource 还是原来的呢

**Comment by zrodo** [comment]
> player 有很多层封装，你说哪里的 datasource 还是原来的呢

FijkPlayer player = map['vc'];
这个时候的player.datasource的地址比如说是a，
然后我reset（），
player.setDataSource(‘新地址’, autoPlay: true);
我断点看，player.datasource里面的地址还是a这个地址，
这个方法能做到重新加载新地址吗？

**Comment by MadeBugs** [comment]
都是异步的
可以试试这样
await player.reset();
await player.setDataSource();

**Comment by zrodo** [comment]
> 都是异步的
> 可以试试这样
> await player.reset();
> await player.setDataSource();

好的。谢谢

**Comment by LsFern** [comment]
> 都是异步的
> 可以试试这样
> await player.reset();
> await player.setDataSource();

切换视频源的时候，第一帧永远都是切换前的那个视频的最后播放帧。咋处理

**Comment by Spencer231** [comment]
> > 都是异步的
> > 可以试试这样
> > await player.reset();
> > await player.setDataSource();
> 
> 切换视频源的时候，第一帧永远都是切换前的那个视频的最后播放帧。咋处理

我这边也是这样，请问你是如何处理的？
