### ISSUE TITLE
全屏播放时遇到两个手机录制的mp4格式的视频全屏后还是竖屏模式播放的,其余的视频都正常

### ISSUE THREAD

**Issue by PillarChen** [befovy/fijkplayer#353]
我这边全屏播放时遇到两个视频(手机录制的mp4格式的视频),点击全屏时仍然是竖屏播放的,其他的视频都正常,这个是什么原因呢(感觉与视频有关系)
全屏异常视频宽高:358*768    正常的视频宽高:640*360 
如何让视频上传的宽<高时,强制让视频跟正常视频一样全屏时进入正常的全屏模式呢

**Comment by befovy** [comment]
代码中根据视频宽高比例以及屏幕宽高比例进行判断决定是否全屏的。
可以自己重新实现全屏的逻辑
