### ISSUE TITLE
[BUG] Iphone7 die when Run application 

### ISSUE THREAD

**Issue by yoonjiyong** [befovy/fijkplayer#356]
**Describe the bug**
I press run button app dies 
i phone 6 ,7 both 

**What attempts have you made to resolve this error ?**
nothing 
just die before do something 

**To Reproduce**
1. Press 'Run' button
2. App dies 

**Expected behavior**
not die

**fijkplayer version**
fijkplayer ^0.8.7

**Smartphone (please complete the following information):**
 - Device: iphone7 
 - OS: iOS 14.2

** Logs before lost connection ** 
flutter: [inf] 2020-12-14 10:00:17.620826 [fijk] FijkPlayer{id:1} state changed to FijkState.initialized <= FijkState.idle
flutter: [inf] 2020-12-14 10:00:17.624 [fijk] FijkPlayer{id:1} invoke prepareAsync and start #1
flutter: [inf] 2020-12-14 10:00:17.624845 [fijk] FijkPlayer{id:1} setOption k:start-on-prepared, v:1
flutter: [inf] 2020-12-14 10:00:17.628363 [fijk] FijkPlayer{id:1} state changed to FijkState.asyncPreparing <= FijkState.initialized
flutter: [inf] 2020-12-14 10:00:17.628796 [fijk] FijkPlayer{id:1} invoke prepareAsync and start #1 -> done
flutter: [inf] 2020-12-14 10:00:17.629015 [fijk] FijkPlayer{id:1} state changed to FijkState.initialized <= FijkState.idle
flutter: [inf] 2020-12-14 10:00:17.629210 [fijk] FijkPlayer{id:1} state changed to FijkState.asyncPreparing <= FijkState.initialized
Lost connection to device.
Failed to send request: {"jsonrpc":"2.0","id":"544","method":"getMemoryUsage","params":{"isolateId":"isolates/842835189009727"}}

**Comment by rahulkapoor1** [comment]
Hi, any update on this crash? I am facing the same on my iPhone 7.
