### ISSUE TITLE
[BUG]0.8.7版本ios arm64库缺失

### ISSUE THREAD

**Issue by workwing** [befovy/fijkplayer#359]
Mac环境：Mac OS Big Sur 1.0.1 (20B29)
Xcode: Version 11.6 (11E708)macOS Catalina: 10.15.5 (19F101)
手机
Device: [iPhoneX]
OS: [iOS 14]
fijkplayer: 0.8.7

flutter build  ios-framework --release后，运行主项目

Undefined symbols for architecture arm64:
"OBJC_CLASS$_IJKFFMoviePlayerController", referenced from:
objc-class-ref in fijkplayer(FijkPlayer.o)
objc-class-ref in fijkplayer(FijkPlugin.o)
"OBJC_CLASS$_IJKFFMediaPlayer", referenced from:
objc-class-ref in fijkplayer(FijkPlayer.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by befovy** [comment]
这个是因为你把 m1 模拟器的 arm64 和真机 arm64 弄混了吧
