### ISSUE TITLE
请问视频全屏和退出全屏的实现思路是啥

### ISSUE THREAD

**Issue by RainSnowSnow** [befovy/fijkplayer#36]

**Comment by befovy** [comment]
可以看 fijkview 中的源代码
`_pushFullScreenWidget`

**Comment by RainSnowSnow** [comment]
@befovy  

_pushFullScreenWidget方法 实现横屏切换在ios中也适配么

**Comment by befovy** [comment]
![image](https://user-images.githubusercontent.com/51129600/63993366-c242e000-cb22-11e9-8cbd-0ad42c4c38b2.png)

适配过 iOS 的，跟app 这个配置有关系，你可以测试一下， 真机或模拟器都行

**Comment by RainSnowSnow** [comment]
@befovy   

![image](https://user-images.githubusercontent.com/23568119/64006286-99334700-cb44-11e9-9f3a-4866fbef0179.png)
我只是旋转了屏幕，但是怎么让他脱离内容，撑满屏幕啊？能不能给点提示啊

**Comment by befovy** [comment]
代码你都可以看见
```
  Future<dynamic> _pushFullScreenWidget(BuildContext context) async {
    final TransitionRoute<Null> route = PageRouteBuilder<Null>(
      settings: RouteSettings(isInitialRoute: false),
      pageBuilder: _fullScreenRoutePageBuilder,
    );

    await SystemChrome.setEnabledSystemUIOverlays([]);
    await FijkPlugin.setOrientationLandscape();
    await Navigator.of(context).push(route);
    _fullScreen = false;
    widget.player.exitFullScreen();
    await SystemChrome.setEnabledSystemUIOverlays(
        [SystemUiOverlay.top, SystemUiOverlay.bottom]);
    await FijkPlugin.setOrientationPortrait();
  }

```
 
就是点击按钮后 push 一个全屏的screen， 显示播放器。
从全屏页面退出后，再把屏幕选装调整回来。

**Comment by RainSnowSnow** [comment]
@befovy 
那是怎么确定全屏和非全屏状态的播放是同步的啊

**Comment by befovy** [comment]
全屏变换完全不涉及 FijkPlayer 的接口，都是 Flutter UI 上的操作， 播放器就没有变化。
