### ISSUE TITLE
[BUG][iOS] await FijkPlayer.setLoop() function will never return anything on iOS.

### ISSUE THREAD

**Issue by GrayLand119** [befovy/fijkplayer#366]
```dart
Future<bool> prepareVideo([String url]) async {
    log.i('1');
    await _videoPlayer?.stop();
    log.i('2');
    await _videoPlayer?.release();
    log.i('3');
    _videoPlayer = FijkPlayer();
    log.i('4');
    await _videoPlayer.setLoop(0);
    log.i('5');
}
```
this codes will print: 

```
1
2
3
4
// 5 is missing!
```
program will always waiting `.setLoop()` Future done, but it never done in iOS.
Android is Fine, it only appear on iOS.

**fijkplayer version**
fijkplayer: ^0.8.7

**Smartphone (please complete the following information):**
什么手机设备和系统版本？
 - Device: [e.g. iPhone8 plus]
 - OS: [e.g. iOS13.2]

**Comment by befovy** [comment]
0.8.8 released
