### ISSUE TITLE
当播放器状态为FijkState.paused或者FijkState.started，切换视频报错

### ISSUE THREAD

**Issue by iperfectapp** [befovy/fijkplayer#37]
Unhandled Exception: Bad state: setDataSource on invalid state FijkState.started OR FijkState.paused

请问如何切换到下一个视频？

**Comment by befovy** [comment]
根据 播放器状态的文档 https://fijkplayer.befovy.com/docs/zh/fijkstate.html
切换视频需要 setDataSource。 
setDataSource 只能在 idle 状态下调用，想要回到 idle 状态需要调用 reset。

或者直接 new 另外一个 FijkPlayer

**Comment by iperfectapp** [comment]
切换视频代码：
      player.reset();
      player.setDataSource(url, autoPlay: true);

控制台打印：
new: FijkState.idle <= old: FijkState.started

出现状况：
第一集 不能播放
第二集 可以播放
第三集 不能播放
第四季 可以播放
...

**Comment by befovy** [comment]
控制台就这一行吗？  @iperfectapp 
```
new: FijkState.idle <= old: FijkState.started
```

**Comment by iperfectapp** [comment]
D/IJKMEDIA( 3748): IjkMediaPlayer_reset
D/IJKMEDIA( 3748): ijkmp_reset()
I/IJKMEDIA( 3748): SDL_JNI_DetachThreadEnv: [8718]
E/flutter ( 3748): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: setDataSource on invalid state FijkState.started
E/flutter ( 3748): null
I/IJKMEDIA( 3748): SDL_JNI_DetachThreadEnv: [8717]
I/HostConnection( 3748): HostConnection::~HostConnection, pid=3748, tid=8717, this=0x91130ba0, m_stream=0x95862000
I/        ( 3748): fastpipe: close connect
I/IJKMEDIA( 3748): SDL_JNI_DetachThreadEnv: [8722]
I/IJKMEDIA( 3748): SDL_JNI_DetachThreadEnv: [8721]
I/IJKMEDIA( 3748): convert image convert_frame_count = 0
I/IJKMEDIA( 3748): SDL_JNI_DetachThreadEnv: [8726]
E/IJKMEDIA( 3748): SDL_Overlay(ffmpeg): overlay_free_l(0x93be3980)
E/IJKMEDIA( 3748): SDL_Overlay(ffmpeg): overlay_free_l(0x93be39c0)
E/IJKMEDIA( 3748): SDL_Overlay(ffmpeg): overlay_free_l(0x93be3a00)
D/IJKMEDIA( 3748): ijkmp_reset()=0
I/flutter ( 3748): state_change: new: FijkState.idle <= old: FijkState.started
I/flutter ( 3748): state_change: new: FijkState.idle <= old: FijkState.started

**Comment by befovy** [comment]
接口调用是否加上了 await .

https://fijkplayer.befovy.com/docs/zh/fijkplayer-api.html

摘抄文档内容
>播放器状态控制接口都是 async 异步接口。如果需要连续调用多个播放器控制接口，需要使用 await 或者 Future.then() 等待异步完成。 不等待前一个调用完成就直接调用后一个方法可能会出现状态错误问题。

**Comment by iperfectapp** [comment]
非常感谢，已经解决

**Comment by befovy** [comment]
文档中这段内容是不是不够醒目？ @iperfectapp

**Comment by iperfectapp** [comment]
我是查看的这个文档
https://fijkplayer.befovy.com/docs/zh/fijkstate.html

没有找到相关方法

**Comment by befovy** [comment]
文档我再整理整理
