### ISSUE TITLE
IOS 12Pro Max 模拟器，播放视频没有图像

### ISSUE THREAD

**Issue by Smithjoppa** [befovy/fijkplayer#374]
我尝试拉去master 分支和 0.8.7版本的代码，但是在ios 12 Pro Max 上无法播放视频，但是有声音的输出

使用Android 可以正常播放的

IOS中是否需要修改配置

**Comment by zhuzhazhu** [comment]
IOS SE模拟器，播放视频没有图像只有声音+1

**Comment by befovy** [comment]
flutter 不支持 ios 模拟器显示纹理
