### ISSUE TITLE
能否集成一下系统音量的获取和设置？

### ISSUE THREAD

**Issue by 3067200952** [befovy/fijkplayer#38]

**Comment by befovy** [comment]
我考虑一下这个需求。
系统的音量也有好几种，比如媒体音量、通话音量。
是否还应该考虑不行的系统音量类型？ 
@3067200952 请说一下你的看法

**Comment by 3067200952** [comment]
媒体音量吧，主要就用来调节视频的音量。我好像还发现一个问题，当播放器处于暂停状态时，进行进度的跳转过后，当前播放进度的流没有被触发，继续播放才恢复正常

**Comment by befovy** [comment]
> 当前播放进度的流没有被触发

这句没太明白 @3067200952

**Comment by befovy** [comment]
调节系统音量还涉及到系统的音量变化弹出框的问题。 
系统弹出的音量变化UI可能会遮挡当前播放内容。
是否将系统音量变化弹出框隐藏？
是否实现新的反应音量变化的UI？
这些我都考虑考虑。大家也都可以给些建议。

**Comment by 3067200952** [comment]
就是我监听了onCurrentPosUpdate，当播放器处于暂停状态时，进行进度的跳转过后，时间应该要改变的，但是回调没有被触发。

**Comment by befovy** [comment]
onCurrentPosUpdate 只在播放状态更新，表示视频、音频实际的播放进度。
paused 状态下 seek 不改变视频、音频实际播放进度，但会改变继续播放时的起始位置。

**Comment by 3067200952** [comment]
了解了，UI的话，可通过参数确定是否显示系统UI，或者额外的api来显示、隐藏系统UI

**Comment by 3067200952** [comment]
你可以看看要不要集成一下screen插件调节亮度

**Comment by befovy** [comment]
@3067200952 感谢关注，对于一些播放器核心逻辑之外的功率，fijkplayer 会慎重考虑。
作为一个 Flutter 插件，我认为应该尽量不要引入别的插件作为依赖。否则以后一切依赖冲突、甚至像 npm 依赖包那样的依赖黑洞都会是很麻烦的是。

**Comment by befovy** [comment]
0.1.5 版本提供支持
