### ISSUE TITLE
[BUG]视频画面和声音不同步

### ISSUE THREAD

**Issue by iperfectapp** [befovy/fijkplayer#39]
![image](https://user-images.githubusercontent.com/3021764/64076648-00dec300-ccfa-11e9-9eee-8ad14e33e06c.png)
此画面是没有声音的，音频先于视频播放

播放链接：
https://pl.dogecloud.com/vcloud/hls/m3u8/112519?tm=1567342291&vtype=98&uid=7&sign=e5ee391e6b4b095f0b615866d38d31c9&icp=0&durlimit=0&server=s3&vkey=696BAC9C70A77DE9F8133E8849FF7BFA8FCBFDAC6C536BD17936EEAEB07105E22E322A1A11C04DFABCBD152014E1401806F2B1CC1AD03F19F9A0E4BC55585065512E63991DFC54BF8B08EA6CC58E2437F54216269211666DC4A139F528C8E0C370E9D7BBD63A28D4936B9DC86768F2EACCC4F5DE526F20CEAE13450A3CC791E4879D01DE36818389921ECFC773A323F7&token=75a1ad982131cdd436b60232a8415ac0&ext=.m3u8

**Comment by iperfectapp** [comment]
模拟器会出现这个问题，真机测试没有问题，可以不用管了

**Comment by iperfectapp** [comment]
点击全屏按钮，进入全屏播放，播放按钮状态不正常，并且无法点击
日志如下：
E/flutter (23651): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: call start on invalid state FijkState.started
E/flutter (23651): null

**Comment by befovy** [comment]
看截图这应该是使用了自定义 UI，切换全屏后是否正确获取当前播放器状态并控制UI显示了？
@iperfectapp
