### ISSUE TITLE
[BUG] Bintray is going away - so is the fijkplayer on iOS?

### ISSUE THREAD

**Issue by b055man** [befovy/fijkplayer#391]
With Bintray going away in a few days ([May 1st](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)), building an app for iOS with fijkplayer won't be possible anymore.

Today is the last planned brown-out period and currently it is not possible to build the app as the bintray repo, containing the pre-built IJKPlayer, is not available
``` 
[!] Error installing BIJKPlayer
[!] /usr/local/opt/curl/bin/curl -f -L -o /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20210426-6876-y0w14n/file.tgz https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'
curl: (22) The requested URL returned error: 403
```

Any plans for keeping the player alive?

**Comment by AAEvstefeev** [comment]
` -> Installing BIJKPlayer (0.7.8)
     > Http download
       $ /usr/bin/curl -f -L -o /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20210504-3187-tnau5o/file.tgz https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'
    [!] Error installing BIJKPlayer
    [!] /usr/bin/curl -f -L -o /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/d20210504-3187-tnau5o/file.tgz https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    curl: (22) The requested URL returned error: 403 Forbidden
`

**Comment by ened** [comment]
@befovy any idea/plan?

**Comment by Michael24884** [comment]
You'll have to manually build the FIJK player for iOS(unless you have it prebuilt), instructions are provided on the docs(you might have to use a translator) and refer the path in the iOS/podfile

**Comment by dmlzj** [comment]
see here https://github.com/befovy/fijkplayer/issues/392#issuecomment-835817152

**Comment by befovy** [comment]
BIJKPlayer 0.7.10 released, replace bintray with github release
