### ISSUE TITLE
[BUG]iOS不能https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz访问这个导致编译失败

### ISSUE THREAD

**Issue by 1342081703** [befovy/fijkplayer#392]
Downloading dependencies

    -> Installing BIJKPlayer (0.7.8)
     > Http download
       $ /usr/bin/curl -f -L -o /var/folders/3v/d9f98q095rj322r9s4z_t47m0000gn/T/d20210508-21902-168uk9r/file.tgz https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

    [!] Error installing BIJKPlayer
    [!] /usr/bin/curl -f -L -o /var/folders/3v/d9f98q095rj322r9s4z_t47m0000gn/T/d20210508-21902-168uk9r/file.tgz https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.1 cocoapods-downloader/1.4.0'

**Comment by NSLogZfRee** [comment]
same issue

**Comment by yanqiuLove** [comment]
same issue
[!] Error installing BIJKPlayer
[!] /usr/bin/curl -f -L -o /var/folders/bd/t20bxwm91p9fy3dx5sbv4ffr0000gn/T/d20210508-11900-hk7f0u/file.tgz https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden

**Comment by randomjoho** [comment]
I'm fork and change 
  s.dependency 'BIJKPlayer', '0.7.8'
to
  s.dependency 'BIJKPlayerFork', '0.0.1'

BIJKPlayerFork change the
  'https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz ' 
to
'https://raw.githubusercontent.com/randomjoho/BijkplayerFork/main/IJKMediaPlayer.tar.gz'





 fijkplayer:
    git:
      url: https://github.com/randomjoho/fijkplayer.git

**Comment by squallml** [comment]
> I'm fork and change
> s.dependency 'BIJKPlayer', '0.7.8'
> to
> s.dependency 'BIJKPlayerFork', '0.0.1'
> 
> BIJKPlayerFork change the
> 'https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz '
> to
> 'https://raw.githubusercontent.com/randomjoho/BijkplayerFork/main/IJKMediaPlayer.tar.gz'
> 
> fijkplayer:
> git:
> url: https://github.com/randomjoho/fijkplayer.git

It's ok, Thinks~

**Comment by MinhCuongIT** [comment]
> I'm fork and change
> s.dependency 'BIJKPlayer', '0.7.8'
> to
> s.dependency 'BIJKPlayerFork', '0.0.1'
> 
> BIJKPlayerFork change the
> 'https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz '
> to
> 'https://raw.githubusercontent.com/randomjoho/BijkplayerFork/main/IJKMediaPlayer.tar.gz'
> 
> fijkplayer:
> git:
> url: https://github.com/randomjoho/fijkplayer.git

It's work for me. Thanks for your help.

**Comment by Exclusive-gfj** [comment]
excuse me, how did you solve this problem ?

**Comment by MinhCuongIT** [comment]
> excuse me, how did you solve this problem ?

Yes. I solved it!

**Comment by Tonigt** [comment]
> I'm fork and change
> s.dependency 'BIJKPlayer', '0.7.8'
> to
> s.dependency 'BIJKPlayerFork', '0.0.1'
> 
> BIJKPlayerFork change the
> 'https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz '
> to
> 'https://raw.githubusercontent.com/randomjoho/BijkplayerFork/main/IJKMediaPlayer.tar.gz'
> 
> fijkplayer:
> git:
> url: https://github.com/randomjoho/fijkplayer.git
It's work for me. Thanks for your help.

**Comment by oshiwei** [comment]
一样的问题，403 Forbidden

**Comment by befovy** [comment]
BIJKPlayer 0.7.10  released,  replace bintray with github release

**Comment by gwsh** [comment]
> I'm fork and change
> s.dependency 'BIJKPlayer', '0.7.8'
> to
> s.dependency 'BIJKPlayerFork', '0.0.1'
> 
> BIJKPlayerFork change the
> 'https://dl.bintray.com/befovytray/bijkplayer/f0.7.8/IJKMediaPlayer.tar.gz '
> to
> 'https://raw.githubusercontent.com/randomjoho/BijkplayerFork/main/IJKMediaPlayer.tar.gz'
> 
> fijkplayer:
> git:
> url: https://github.com/randomjoho/fijkplayer.git

Thinks , This keeps me on track.
