### ISSUE TITLE
IOS 不显示播放画面

### ISSUE THREAD

**Issue by yuan1809** [befovy/fijkplayer#395]
IOS 不显示播放画面

`+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
    FlutterMethodChannel *channel =
        [FlutterMethodChannel methodChannelWithName:@"befovy.com/fijk"
                                    binaryMessenger:[registrar messenger]];
    FijkPlugin *instance = [[FijkPlugin alloc] initWithRegistrar:registrar];
    _instance = instance;
    [registrar addMethodCallDelegate:instance channel:channel];

    FijkPlayer *player = [[FijkPlayer alloc] initJustTexture];
    int64_t vid = [[registrar textures] registerTexture:player];
    // modify by yuanye bug修复：初始化就释放，导致视频不显示
  //  [player shutdown];
  //  [[registrar textures] unregisterTexture:vid];
}`

**Comment by befovy** [comment]
使用的模拟器吗？  flutter 不支持在 iOS 模拟器是渲染 Texture
