### ISSUE TITLE
ERROR: Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. 

### ISSUE THREAD

**Issue by HQiang** [befovy/fijkplayer#40]
在播放直播流媒体视频时，dispose方法中执行player.release();页面退出后视频仍然在播放，且控制台一直打印
W/FlutterJNI(18808): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: befovy.com/fijkplayer/event/2. Response ID: 0
V/DartMessenger(18808): Sending message with callback over channel 'befovy.com/fijkplayer/event/3'
W/FlutterJNI(18808): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: befovy.com/fijkplayer/event/3. Response ID: 0
V/DartMessenger(18808): Sending message with callback over channel 'befovy.com/fijkplayer/event/2'
不停的循环打印这两段日志信息

**Comment by befovy** [comment]
这应该是你的开发环境有什么问题

**Comment by HQiang** [comment]
我调试了下代码，发现退出播放页面，没有执行dispose()方法，我还在找原因，很可能不是你的问题。但是我也纳闷，dispose是生命周期方法，不存在不会执行的情况呀。
你可以试试player.setDataSource("http://ivi.bupt.edu.cn/hls/cctv1hd.m3u8", autoPlay: true);
在你的Demo中，退出页面能够停止播放吗，很诡异

**Comment by befovy** [comment]
我试了，可以停止播放 @HQiang

**Comment by HQiang** [comment]
Ok, That's my problem
