### ISSUE TITLE
如何获取 fijkplayer 的音量？

### ISSUE THREAD

**Issue by iperfectapp** [befovy/fijkplayer#41]
是不是只能获取系统的音量？

**Comment by befovy** [comment]
不支持获取媒体中的音量，并且不在近期版本计划中。

**Comment by befovy** [comment]
@iperfectapp  如果指的是通过接口  setVolume 修改的音轨音量
https://pub.dev/documentation/fijkplayer/latest/fijkplayer/FijkPlayer/setVolume.html

setVolume接口设置音量的默认值是1，即不调用此接口是音量是1，调用后音量就是接口中的参数值。

**Comment by iperfectapp** [comment]
如果用播放自带的接口，声音只能设置为比当前音量更小，可以这样理解吗？

**Comment by befovy** [comment]
setVolume 可以设置大于1的值，但具体表现依赖于android 或 iOS sdk


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by iperfectapp** [comment]
非常感谢
