### ISSUE TITLE
.MOV格式无法播放

### ISSUE THREAD

**Issue by jianleepb** [befovy/fijkplayer#419]
ios 选择的视频很多都是mov格式的
例如本地路径：file:///var/mobile/Media/DCIM/124APPLE/IMG_4113.MOV
使用video_player可以播放，但是fijkplayer就会报错：
版本：fijkplayer:^0.8.8 
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (7 months ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Comment by jianleepb** [comment]
不仅仅是mov 估计是和flutter_ffmpeg 冲突这个问题还没解决

**Comment by wengxianxun** [comment]
解决了吗，
