### ISSUE TITLE
假如视频无法播放，fijkplayer是否有相应的接口反馈？

### ISSUE THREAD

**Issue by iperfectapp** [befovy/fijkplayer#42]
是否只能根据播放器状态结合Timer来判断呢？

**Comment by befovy** [comment]
无法播放的视频应该会进入 error 状态。
https://fijkplayer.befovy.com/docs/zh/error-exception.html

**Comment by iperfectapp** [comment]
谢谢， FijkPlayer.value.exception.code 不等于0，就表示不能播放吗？

**Comment by befovy** [comment]
出错（FijkPlayer.value.exception.code ！= 0）肯定是不能播放的，每种错误都有对应的message
