### ISSUE TITLE
[BUG] 加载视频时，设置视频默认的进度。

### ISSUE THREAD

**Issue by lytian** [befovy/fijkplayer#431]
**Describe the bug**
```dart
await _fijkPlayer.setDataSource(url, autoPlay: true);
await _fijkPlayer.seekTo(120 * 1000);
```
我在setDataSource之后，立即seekTo，日志报错：```[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: Non playable state FijkState.asyncPreparing```

**What attempts have you made to resolve this error ?**
我尝试了延时设置进度，时间设置比较长的话，是可以正常设置播放进度的，但是我觉得这样不合理。

**Expected behavior**
希望能够简单、有效的设置默认的进度（打开视频的时候加载到上次播放的进度）

**fijkplayer version**
用了0.10.0版本的 fijkplayer

**Comment by xiaoyaoking** [comment]
不看文档吗？只能在可播放状态下调用此接口

进度跳转
dart api seekTo
Future<void> seekTo() async
// usage
fplayer.seekTo(3000);
控制播放器进行播放进度，参数以毫秒为单位。**只能在可播放状态下调用此接口**，参考 可播放状态

**Comment by lytian** [comment]
看了文档。设置url后，只能监听播放器变化得到**可播放状态下**，没有找到其他的方法

**Comment by xiaoyaoking** [comment]
是啊。。。 我也是这么搞的。。。。 没找到其他办法。
if (value.state == FijkState.started) {
   
}

**Comment by lytian** [comment]
好吧

**Comment by lytian** [comment]
在```setDataSource```有个initializePosition选项就好了，加载视频的时候，就从指定的位置开始加载。

**Comment by lytian** [comment]
可以通过设置option来解决，```await _fijkPlayer.setOption(FijkOption.playerCategory, 'seek-at-start', playPosition);```
