### ISSUE TITLE
视频太大播放卡顿

### ISSUE THREAD

**Issue by qlaiqyc** [befovy/fijkplayer#44]
大哥 你好，非常感谢你提供这个分享

主要使用问题： 我在播放 腾讯的视频流的时候  非常卡顿

       [`流`]https://ltsws.qq.com/uwMROfz2r5zAoaQXGdGnC2df644E7D3uP8M8pmtgwsRK9nEL/5UyykS86KVQ2mlAI0UveLqXs7Yf8Sn5QSEAO1T7Tltr7XIBIawTmdGfMcfVw_DZDdAMFbwqQEoXh0peMsleyGDOFNV_BRovI0GSdDbYY_w1Ci7t3BT13cQWWD-Sf_8evM7GCMYnxdLuedkXErucUqUxoxbx_qlGufkBKckZhPiA/e003281huvn.321002.ts.m3u8?ver=4",

**Comment by befovy** [comment]
网络卡还是播放器性能不足引起卡？ 我这电脑上播放这个 url 网络特别卡。 @qlaiqyc

**Comment by befovy** [comment]
Closed. Tagged `need more info`, but no response for a long time.
