### ISSUE TITLE
部分视频无法播放

### ISSUE THREAD

**Issue by iperfectapp** [befovy/fijkplayer#45]
http://jiasu-33.ivneu.cn/20190702/%E5%88%9D%E6%81%8B%E6%9C%AA%E6%BB%A1/2000kb/hls/index.m3u8

控制台显示如下：
I/IJKMEDIA(15880): SDL_JNI_DetachThreadEnv: [16315]
D/IJKMEDIA(15880): FFP_MSG_ERROR: -1094995529
E/tv.danmaku.ijk.media.player.IjkMediaPlayer(15880): Error (-1094995529,0,Invalid data found when processing input)
I/flutter (15880): errorListerner: PlatformException(-1094995529, Invalid data found when processing input, 0), FijkException(-1094995529, Invalid data found when processing input)
I/flutter (15880): state_change: new: FijkState.error <= old: FijkState.asyncPreparing

**Comment by iperfectapp** [comment]
https://meiju9.whetyy.com/20190903/Pq8VDBIu/index.m3u8

这个也不能播放

**Comment by befovy** [comment]
目前编译的 ffmpeg 不支持这个，后面会加上

**Comment by iperfectapp** [comment]
我自己能做什么吗？

**Comment by befovy** [comment]
编译还有配置 ffmpeg 部分暂时没有写文档， 但是可以搜索ijkplayer 相关内容。
这样修改 fijkplayer 就不能通过 dart pub 引入了， 需要在本地修改以相对路径方式引入

**Comment by befovy** [comment]
@iperfectapp 或者你帮忙验证一下 issue 31 的问题


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by iperfectapp** [comment]
好的 我有时候看看




| |
123
邮箱：newton520@163.com
|

签名由 网易邮箱大师 定制

在2019年09月03日 18:39，befovy 写道：

@iperfectapp 或者你帮忙验证一下 issue 31 的问题

From gitme iOS

**Comment by iperfectapp** [comment]
你手机上是用的什么软件？




| |
123
邮箱：newton520@163.com
|

签名由 网易邮箱大师 定制

在2019年09月03日 18:43，Newton 写道：
好的 我有时候看看




| |
123
邮箱：newton520@163.com
|

签名由 网易邮箱大师 定制

在2019年09月03日 18:39，befovy 写道：

@iperfectapp 或者你帮忙验证一下 issue 31 的问题

From gitme iOS

**Comment by befovy** [comment]
![image](https://user-images.githubusercontent.com/51129600/64177953-163b2500-ce93-11e9-9264-a6d8d0611df2.png)

这个链接都可以打开的，你那显示不出来吗

**Comment by befovy** [comment]
bugfix-issue31 和 develop 已经增加对这种视频的播放支持

**Comment by befovy** [comment]
released in version 0.1.3

**Comment by befovy** [comment]
@all-contributors please add @iperfectapp for userTesting

**Comment by befovy** [comment]
@all-contributors please add @iperfectapp for userTesting

**Comment by befovy** [comment]
@all-contributors please add @iperfectapp for userTesting

**Comment by befovy** [comment]
@all-contributors please add iperfectapp for userTesting

**Comment by befovy** [comment]
@all-contributors please add @iperfectapp  for userTesting

**Comment by yang-he** [comment]
播放加密的 m3u8 视频会出现 “Invalid data found when processing input”，请问这个问题解决了吗？

**Comment by befovy** [comment]
加密视频需要设置解密key

**Comment by yang-he** [comment]
> 加密视频需要设置解密key

能请您指导一下如何设置解密key吗？我请求的 m3u8 视频地址是这样：

`https://vod.example.com/vod/abf30d2bc85741ed8ea4d59d969f983d/act-ss-m3u8-hd/video.m3u8?MtsHlsUriToken=vjdEYcvf8LEWKwEIBDfeGYfY-2Hjhmzw`

这个 MtsHlsUriToken 我需要在代码中做什么特别的设置吗？

**Comment by hpp0hpp** [comment]
请问下如何设置key,能否单独设置解密key
