### ISSUE TITLE
[BUG] Codec support for MP2 

### ISSUE THREAD

**Issue by dimityrivanov** [befovy/fijkplayer#483]
Hello I have a video file that ships with MP2 audio and I am unable to activate it for the fijkplayer is it supported, is there anything I can do to enable it ?

**Comment by riskiadi** [comment]
THIS IS THE BEST LIBRARY I'VE EVER SEEN!

**Comment by befovy** [comment]
@dimityrivanov To use some new codec or format that supported by ffmpeg, you should rebuild ffmpeg. And then replace the ffmpeg used in fijkplayer.
Follow the guide in https://fijkplayer.befovy.com/docs/zh/replace-ijkplayer.html#gsc.tab=0
