### ISSUE TITLE
No http header option

### ISSUE THREAD

**Issue by Nwoko-Repo** [befovy/fijkplayer#485]
Why is this library not have option to add http headers for network datasource

**Comment by befovy** [comment]
There's a option for http header.

https://fijkplayer.befovy.com/docs/zh/faq.html#%E8%AE%BE%E7%BD%AE-http-%E8%AF%B7%E6%B1%82%E5%A4%B4

**Comment by Nwoko-Repo** [comment]
Ok..thanks you

**Comment by ngominhtrungit** [comment]
> There's a option for http header.

Hi. I'm try with option headers above. but it not working, Error 'Authen 404'

pls help me. tks all
