### ISSUE TITLE
在iOS上运行不起来

### ISSUE THREAD

**Issue by bear-zyy** [befovy/fijkplayer#51]
[!] CocoaPods could not find compatible versions for pod "FIJKPlayer":
  In Podfile:
    fijkplayer (from `.symlinks/plugins/fijkplayer/ios`) was resolved to 0.1.3, which depends on
      FIJKPlayer (~> 0.3.7)

None of your spec sources contain a spec satisfying the dependency: `FIJKPlayer (~> 0.3.7)`.

**Comment by bear-zyy** [comment]
已解决

**Comment by befovy** [comment]
@bear-zyy 怎么解决的呢？ 谢谢
