### ISSUE TITLE
有图像，没有声音[BUG]

### ISSUE THREAD

**Issue by lifenglsf** [befovy/fijkplayer#530]
**Describe the bug**
有图像没有声音

**Expected behavior**
声音正常

**Screenshots**
发现一些日志，好像是没有解码成功
I/IJKMEDIA( 6891): Input #0, hls,applehttp, from 'http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221226192/index.m3u8':
I/IJKMEDIA( 6891):   Duration: 
I/IJKMEDIA( 6891): N/A
I/IJKMEDIA( 6891): , start: 
I/IJKMEDIA( 6891): 38075.766667
I/IJKMEDIA( 6891): , bitrate: 
I/IJKMEDIA( 6891): N/A
I/IJKMEDIA( 6891): 
I/IJKMEDIA( 6891):   Program 0 
I/IJKMEDIA( 6891):     Metadata:
I/IJKMEDIA( 6891):       variant_bitrate : 
I/IJKMEDIA( 6891): 0
I/IJKMEDIA( 6891): 
D/IJKMEDIA( 6891): FFP_MSG_FIND_STREAM_INFO:
I/IJKMEDIA( 6891):     Stream #0:0
I/IJKMEDIA( 6891): : Video: h264 ([27][0][0][0] / 0x001B), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9]
I/IJKMEDIA( 6891): , 
I/IJKMEDIA( 6891): 25 fps, 
I/IJKMEDIA( 6891): 25 tbr, 
I/IJKMEDIA( 6891): 90k tbn, 
I/IJKMEDIA( 6891): 50 tbc
I/IJKMEDIA( 6891): 
I/IJKMEDIA( 6891):     Metadata:
I/IJKMEDIA( 6891):       variant_bitrate : 
I/IJKMEDIA( 6891): 0
I/IJKMEDIA( 6891): 
I/IJKMEDIA( 6891):     Stream #0:1
I/IJKMEDIA( 6891): : Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, 2 channels, 64 kb/s
I/IJKMEDIA( 6891): 
I/IJKMEDIA( 6891):     Metadata:
I/IJKMEDIA( 6891):       variant_bitrate : 
I/IJKMEDIA( 6891): 0
I/IJKMEDIA( 6891): 
W/IJKMEDIA( 6891): No codec could be found with id 86016

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer
0.10.1
**Smartphone (please complete the following information):**
什么手机设备和系统版本？
 macosx 模拟器 31的tv api

ps:flutter 的vlc同样的地址可以解码成功的，有图像有声音

**Comment by 5115191** [comment]
ios遇到同样的问题

**Comment by lifenglsf** [comment]
最近用ffprobe发现有图像没有声音的的m3u8是mp2的视频，应该是ijkplayer编译的版本没有加mp2的支持。对java是小白级别的，等有时间按照官方的文档编译一个支持mp2的ijkplayer看看是不是还有有问题

**Comment by lifenglsf** [comment]
花费了周末的两天时间折腾重新编译，基于befovy/ijkplayer的ijkplayer。在module.sh中加上
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2"`
或者你使用的module.sh文件中添加，然后重新编译ffmpeg和ijkplayer，替换ijkplayer的方法参考[点击这里查看如何替换ijkplayer](https://fijkplayer.befovy.com/docs/zh/replace-ijkplayer.html).我是在befovy/fijkplayer的example项目中使用新的ijkplayer的。自己的项目引用新的ijkplayer一直提示找不到aar文件，不清楚是哪里配置的有问题。使用befovy/fijkplayer的example把新编译的aar文件放到example项目下的Android/aars目录下.

**Comment by z1047549075** [comment]
你好，我这边遇到同样问题了，但是完全不知如何解决，请问该如何处理，看了你上面的描述，module.sh是在哪里的啊

**Comment by lifenglsf** [comment]
> 你好，我这边遇到同样问题了，但是完全不知如何解决，请问该如何处理，看了你上面的描述，module.sh是在哪里的啊

重新编译了下，加了mp2的支持,在module-lite.sh文件中添加export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2"并重新编译

**Comment by shubham-jain2** [comment]
> Recently, I used ffprobe to compare the difference between m3u8 that can play normally and m3u8 that has images but no sound. Those with images but no sound are all mp2 videos. It should be that the version compiled by ijkplayer does not have mp2 support. I am a novice on Java. When I have time, I will compile an ijkplayer that supports MP2 according to the official documentation and see if there are still any problems.

Hi @lifenglsf , thanks for sharing valuable insight on this issue. I am working on a similar video source and facing the exact same issue. Is it at all possible for you to share the .aar file that you compiled. I will check it to make sure this is all worth doing and if yes then I will move on to iOS. Thanks

**Comment by lifenglsf** [comment]
[aar file](https://raw.githubusercontent.com/lifenglsf/sample_tv/main/android/aars/fijkplayer-full-release.aar?token=GHSAT0AAAAAACNG7YPVWWOHRXZVFFRL2HTMZQDP4SA)

**Comment by lifenglsf** [comment]
[aar file](https://drive.google.com/file/d/1XwQf2-uytZR9RFAJFor8X1xEGkF-GzV8/view)

**Comment by shubham-jain2** [comment]
> [aar file](https://drive.google.com/file/d/1XwQf2-uytZR9RFAJFor8X1xEGkF-GzV8/view)

Is it working for you? Are you able to play video with MP2 audio?

**Comment by shubham-jain2** [comment]
> I spent two days on the weekend recompiling ijkplayer based on befovy/ijkplayer. Add it to module.sh `export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2"` or the module.sh file you use, then recompile ffmpeg and ijkplayer. For the method of replacing ijkplayer, [click here to see how to replace ijkplayer](https://fijkplayer.befovy.com/docs/zh/replace-ijkplayer.html) . I am using the new one in the example project of befovy/fijkplayer ijkplayer. My own project references the new ijkplayer and keeps saying that the aar file cannot be found. I don't know where the configuration problem is. Use the example of befovy/fijkplayer to place the newly compiled aar file in the Android/aars directory under the example project.

@lifenglsf https://github.com/brim-borium/spotify_sdk/issues/99#issuecomment-878910598 I have made it work with the aar file you provided and the audio is now playing fine. Follow the link and let me know if still need help.

**Comment by lifenglsf** [comment]
> > [aar file](https://drive.google.com/file/d/1XwQf2-uytZR9RFAJFor8X1xEGkF-GzV8/view)
> 
> Is it working for you? Are you able to play video with MP2 audio?

我的问题是解决了的，文件就是我编译出来的

**Comment by lifenglsf** [comment]
> > I spent two days on the weekend recompiling ijkplayer based on befovy/ijkplayer. Add it to module.sh `export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2"` or the module.sh file you use, then recompile ffmpeg and ijkplayer. For the method of replacing ijkplayer, [click here to see how to replace ijkplayer](https://fijkplayer.befovy.com/docs/zh/replace-ijkplayer.html) . I am using the new one in the example project of befovy/fijkplayer ijkplayer. My own project references the new ijkplayer and keeps saying that the aar file cannot be found. I don't know where the configuration problem is. Use the example of befovy/fijkplayer to place the newly compiled aar file in the Android/aars directory under the example project.
> 
> @lifenglsf [brim-borium/spotify_sdk#99 (comment)](https://github.com/brim-borium/spotify_sdk/issues/99#issuecomment-878910598) I have made it work with the aar file you provided and the audio is now playing fine. Follow the link and let me know if still need help.

不明白你那边是有什么问题？
