### ISSUE TITLE
默认UI中，如果设置 autoPlay false， 就一直转圈，没有 start 按钮

### ISSUE THREAD

**Issue by zxj17815** [befovy/fijkplayer#57]
**遇到的情况是在进入页面的时候直接开始播放，会太突然**

**建议增加一个点击了再播放的状态**
可以在进入的时候还是异步加载，然后不播放，或者直接暂停在第一帧

**Comment by befovy** [comment]
如果在 prepareAsync 接口中参数 autoPlay 是 false。
在 UI 中点击播放按钮应该是能够播放成功的。 

请提供运行日志

**Comment by zxj17815** [comment]
D/IJKMEDIA( 2855): ffpipeline_set_mediacodec_select_callback
D/IJKMEDIA( 2855): ijkmp_android_set_mediacodec_select_callback()=void
D/IJKMEDIA( 2855): IjkMediaPlayer_native_setLogLevel(4)
D/IJKMEDIA( 2855): moncleanup
D/tv.danmaku.ijk.media.player.IjkMediaPlayer( 2855): Couldn't open file on client side, trying server side
D/IJKMEDIA( 2855): IjkMediaPlayer_setDataSourceAndHeaders
V/IJKMEDIA( 2855): setDataSource: path https://stance.oss-cn-hangzhou.aliyuncs.com/videos/about.mp4
D/IJKMEDIA( 2855): ijkmp_set_data_source(url="https://stance.oss-cn-hangzhou.aliyuncs.com/videos/about.mp4")
D/IJKMEDIA( 2855): ijkmp_set_data_source(url="https://stance.oss-cn-hangzhou.aliyuncs.com/videos/about.mp4")=0
D/IJKMEDIA( 2855): IjkMediaPlayer_setVideoSurface
D/IJKMEDIA( 2855): ijkmp_set_android_surface(surface=0x7ffcf3c5d208)
D/IJKMEDIA( 2855): ffpipeline_set_surface()
D/IJKMEDIA( 2855): ijkmp_set_android_surface(surface=0x7ffcf3c5d208)=void
I/flutter ( 2855): state_change: new: FijkState.initialized <= old: FijkState.idle
I/flutter ( 2855): view setup, vid:61

**Comment by befovy** [comment]
setDataSource 接口中参数 autoPlay 是 false 的情况袭，
需要调用  start 接口。
更多请参考 https://fijkplayer.befovy.com/docs/zh/fijkstate.html 文档内容
https://fijkplayer.befovy.com/docs/zh/fijkplayer-api.html

**Comment by befovy** [comment]
@all-contributors please add @zxj17815 for bug

**Comment by befovy** [comment]
默认 fijkpanel UI 上的问题，如果使用自定义UI 不受此影响。 

Custom UI is recommended in any product.

**Comment by zxj17815** [comment]
是这样的，谢谢

**Comment by befovy** [comment]
"start-on-prepared" 默认值下个版本改成0， 避免接口调用的表现和文档描述不一致

**Comment by befovy** [comment]
start-on-prepared defaut value has been set to 0 in version 0.1.5
