### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eyinfo** [befovy/fijkplayer#574]
**Describe the bug**
清晰描述你遇到了什么问题。
flutter 3.10.1报fijkView.dart里的await SystemChrome.setEnabledSystemUIOverlays([]);未找到，应该在flutter 3.10.1这个方法被移除了

**To Reproduce**
问题的复现步骤

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
<img width="1659" alt="image" src="https://github.com/befovy/fijkplayer/assets/95947736/3d6d666c-cee5-4918-be9a-294f4bfbbfe6">

**fijkplayer version**
Which version you used.
引用版本fijkplayer 0.10.1 

**Smartphone (please complete the following information):**
和手机设备没关系，与flutter版本有关系

**Comment by fanpener** [comment]
Rollback flutter version or use local dependencies and fix it yourself

**Comment by befovy** [comment]
fijkplayer version 0.11.0 released, this bug has been fixed
