### ISSUE TITLE
[BUG] [!] No podspec found for `fijkplayer_new` in `.symlinks/plugins/fijkplayer_new/ios`

### ISSUE THREAD

**Issue by FLEasy** [befovy/fijkplayer#580]
**Describe the bug**

When I was using fijkplayer_new: ^0.10.2, I encountered [!] No podspec found for `fijkplayer_new` in `.symlinks/plugins/fijkplayer_new/ios` using pod install

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
有问题请自己先努力尝试解决。
尤其是一些已经在错误输出中给出了可能的解决办法的问题

**To Reproduce**
问题的复现步骤

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
如果截图有助于对此问题的理解，一定要附上截图

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer

**Smartphone (please complete the following information):**
什么手机设备和系统版本？

**Additional context**
其他有关此问题的内容

**Comment by befovy** [comment]
What is fijkplayer_new? I only publish fijkplayer to pub.dev

**Comment by FLEasy** [comment]
![WeChatc26831702987b4a7cef9f5fee31e35f4](https://github.com/befovy/fijkplayer/assets/15194292/c378d6ed-8393-4f4c-b6e6-735f1c3c0dcb)
Sorry, this is not the author's dependency library, right?

**Comment by befovy** [comment]
Ooh, someone forked fijkplayer, and published fijkplayer_new 0.10.2 with dart 3 compatible changes

**Comment by FLEasy** [comment]
Author, will you modify fijkplayer recently to support dart 3?

**Comment by befovy** [comment]
OK, I will release a new version that support dart 3

**Comment by FLEasy** [comment]
thank you for your help

**Comment by itMcdull** [comment]
Any progress！！

**Comment by befovy** [comment]
fijkplayer version 0.11.0 released
