### ISSUE TITLE
[BUG]pod install 一直卡在Installing BIJKPlayer (0.7.16)

### ISSUE THREAD

**Issue by hanxiaofeng** [befovy/fijkplayer#594]
**Describe the bug**
清晰描述你遇到了什么问题。

ios目录下执行pod install 一直卡在Installing BIJKPlayer (0.7.16)，切换代理结点也没用

**What attempts have you made to resolve this error ?**
**为了解决这个问题你有什么尝试？**
有问题请自己先努力尝试解决。
尤其是一些已经在错误输出中给出了可能的解决办法的问题

切换不同结点进行下载，无果

**To Reproduce**
问题的复现步骤

**Expected behavior**
描述清楚你希望的运行结果是什么

**Screenshots**
如果截图有助于对此问题的理解，一定要附上截图
<img width="564" alt="image" src="https://github.com/befovy/fijkplayer/assets/10582931/becd127f-e693-47eb-89f6-fd1d761172a9">

**fijkplayer version**
Which version you used.
用了什么版本的 fijkplayer

用的最新版本0.11.0

**Comment by xueyifei123** [comment]
怎么下载啊。我也卡主了

**Comment by xueyifei123** [comment]
> 废了九牛二虎之力，终于下载成功

怎么下载啊？跪求办法
