### ISSUE TITLE
[BUG] Failed to play audio stream: "No codec could be found with id ...".

### ISSUE THREAD

**Issue by kostov** [befovy/fijkplayer#601]
Most powerful player plugin for flutter that I seen... but there are many formats it plays without audio (file or rtsp).
In logs we can see:
...
I/IJKMEDIA( 4749):     Stream #0:1
I/IJKMEDIA( 4749): : Audio: pcm_s16be, 8000 Hz, 1 channels, 128 kb/s
...
I/IJKMEDIA( 4749):     Stream #0:1
I/IJKMEDIA( 4749): (eng)
I/IJKMEDIA( 4749): : Audio: adpcm_ima_wav (ms[0][17] / 0x1100736D), 32000 Hz, 2 channels, 256 kb/s
...
I/IJKMEDIA( 4749):     Stream #0:0
I/IJKMEDIA( 4749): : Audio: pcm_alaw, 16000 Hz, 1 channels, 128 kb/s
...

And then: 
W/IJKMEDIA( 4749): No codec could be found with id [xxxxx]
Here (https://github.com/bilibili/ijkplayer/issues/23) they say that "Some rarely used codec has been disabled for smaller size".
Is there some way to enable these codecs back?

**Comment by kostov** [comment]
Build local fijkplayer plugin with enabled pcm audio decoders -- succeeded :)

Thanks to befovy, instructions are here:
     https://fijkplayer.befovy.com/docs/zh/replace-ijkplayer.html
     https://github.com/befovy/ijkplayer
-- but there are some errors. Working instruction (android only):

    add these lines to your ~/.bash_profile or ~/.profile
    export ANDROID_SDK=<your sdk path>
    export ANDROID_NDK=<your ndk path>

    git clone https://github.com/befovy/ijkplayer.git ijkplayer-android
    cd ijkplayer-android
    ./init-android.sh

    cd config
    WARNING: do not use module-*.sh to make simlink with name 'module.sh'
    edit existing module.sh:

    find part # ./configure --list-decoders
    add these lines (after export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-decoders"):
      export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_s16be"
      export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_alaw"
      export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_mulaw"
      export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=adpcm_ima_wav"

    find part # ./configure --list-demuxers
    add these lines (after export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-demuxers"):
      export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_s16be"
      export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_alaw"
      export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_mulaw"

    cd ../android/contrib
    ./compile-ffmpeg.sh clean
    ./compile-ffmpeg.sh all
    ensure added decoders and demuxers are exist in table

    cd ../ijkplayer
    ./gradlew :fijkplayer-full:assembleRelease
    result is here: /ijkplayer-android/android/ijkplayer/fijkplayer-full/build/outputs/aar/fijkplayer-full-release.aar

    your flutter project directory = ${your_project}
    local fijkplayer plugin directory = ${fijkplayer}

    copy fijkplayer-full-release.aar into ${your_project}/android/aars (create this subdir)
    edit ${your_project}/pubspec.yaml:
      #  fijkplayer: ^0.11.0
      fijkplayer:
        path: "${fijkplayer}"

    edit ${fijkplayer}/android/build.gradle:
      implementation(name: 'fijkplayer-full-release', ext: 'aar') // uncomment this line
      // implementation 'com.befovy.fijkplayer:fijkplayer-full:0.7.16' // comment this line

    cd ${fijkplayer}
    flutter pub get
    
    cd ${your_project}
    flutter pub get
    flutter build apk

**Comment by kostov** [comment]
Working (for me :) instruction for IOS:

```
git clone https://github.com/befovy/ijkplayer.git ijkplayer-ios
cd ijkplayer-ios

WARNING: stay in master brunch, do not git checkout -B latest k0.8.8

./init-ios.sh
./init-ios-openssl.sh

cd config
WARNING: do not use module-*.sh to make simlink with name 'module.sh'
edit existing module.sh:

find part # ./configure --list-decoders
add these lines (after export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-decoders"):
  export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_s16be"
  export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_alaw"
  export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_mulaw"
  export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=adpcm_ima_wav"

find part # ./configure --list-demuxers
add these lines (after export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-demuxers"):
  export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_s16be"
  export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_alaw"
  export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_mulaw"

cd ../ios

./compile-ffmpeg.sh clean
./compile-ffmpeg.sh all

ensure added decoders and demuxers are exist in table

./compile-openssl.sh all

cd IJKMediaPlayer

xcodebuild -project IJKMediaPlayer.xcodeproj -configuration Release -scheme Universal

result is here: /ijkplayer-ios/ios/CocoaPodsPub/IJKMediaPlayer.framework

your flutter project directory = ${your_project}
local fijkplayer plugin directory = $fijkplayer{}

copy IJKMediaPlayer.framework into ${fijkplayer}/ios/Frameworks/ (create this subdir)
edit ${your_project}/pubspec.yaml:

# fijkplayer: ^0.11.0
fijkplayer:
path: "${fijkplayer}"

edit ${fijkplayer}/ios/fijkplayer.podspec:

# unkomment these three lines
s.preserve_paths = 'Frameworks\*.framework'
s.vendored_frameworks = 'Frameworks/IJKMediaPlayer.framework'
s.xcconfig = { 'LD_RUNPATH_SEARCH_PATHS' => '"$(PODS_ROOT)/Frameworks/"' }

# comment this line
# s.dependency 'BIJKPlayer', '~> 0.7.16'

cd ${fijkplayer}
flutter pub get

cd ${your_project}
flutter pub get
flutter build ios
```

**Comment by shubham-jain2** [comment]
> Working (for me :) instruction for IOS:
> 
> ```
> git clone https://github.com/befovy/ijkplayer.git ijkplayer-ios
> cd ijkplayer-ios
> 
> WARNING: stay in master brunch, do not git checkout -B latest k0.8.8
> 
> ./init-ios.sh
> ./init-ios-openssl.sh
> 
> cd config
> WARNING: do not use module-*.sh to make simlink with name 'module.sh'
> edit existing module.sh:
> 
> find part # ./configure --list-decoders
> add these lines (after export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-decoders"):
>   export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_s16be"
>   export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_alaw"
>   export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=pcm_mulaw"
>   export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=adpcm_ima_wav"
> 
> find part # ./configure --list-demuxers
> add these lines (after export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --disable-demuxers"):
>   export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_s16be"
>   export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_alaw"
>   export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=pcm_mulaw"
> 
> cd ../ios
> 
> ./compile-ffmpeg.sh clean
> ./compile-ffmpeg.sh all
> 
> ensure added decoders and demuxers are exist in table
> 
> ./compile-openssl.sh all
> 
> cd IJKMediaPlayer
> 
> xcodebuild -project IJKMediaPlayer.xcodeproj -configuration Release -scheme Universal
> 
> result is here: /ijkplayer-ios/ios/CocoaPodsPub/IJKMediaPlayer.framework
> 
> your flutter project directory = ${your_project}
> local fijkplayer plugin directory = $fijkplayer{}
> 
> copy IJKMediaPlayer.framework into ${fijkplayer}/ios/Frameworks/ (create this subdir)
> edit ${your_project}/pubspec.yaml:
> 
> # fijkplayer: ^0.11.0
> fijkplayer:
> path: "${fijkplayer}"
> 
> edit ${fijkplayer}/ios/fijkplayer.podspec:
> 
> # unkomment these three lines
> s.preserve_paths = 'Frameworks\*.framework'
> s.vendored_frameworks = 'Frameworks/IJKMediaPlayer.framework'
> s.xcconfig = { 'LD_RUNPATH_SEARCH_PATHS' => '"$(PODS_ROOT)/Frameworks/"' }
> 
> # comment this line
> # s.dependency 'BIJKPlayer', '~> 0.7.16'
> 
> cd ${fijkplayer}
> flutter pub get
> 
> cd ${your_project}
> flutter pub get
> flutter build ios
> ```

@kostov Thanks for sharing this valuable insight. I attempted the same setup. But keep getting this error while running the command ./compile-openssl.sh all

`libavutil/application.c:25:14: fatal error: 'openssl/evp.h' file not found
    #include <openssl/evp.h> `

I wanted to enable mp2 codec. As you have already set up the environment correctly. Can you share with me the IJKMediaPlayer.framework file after enabling the mp2 codec using `export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2 `

Thanks

**Comment by kostov** [comment]
Sorry, I lost all the work in that project. Now deal with completely different tasks and even have no mac :). Maybe I'll can help later...
