### ISSUE TITLE
视频截图功能

### ISSUE THREAD

**Issue by HQiang** [befovy/fijkplayer#61]
现在网上关于Flutter 屏幕截图全都是采用 `RepaintBoundary` 来包裹Widget实现，但是FijkPlayer并不是一个Widget, 我在操作用这种方式截屏的时候，只能截取到我自定义的播放器UI的图，视频的播放内容截取不到，目前有没有什么其他的方法可以实现视频截图，如果你后面要实现视频截图功能，你大概会怎么做，可以给点意见吗

**Comment by befovy** [comment]
FijkView 是一个 Widget， RepaintBoundary 不能对 FijkView 进行截图吗？ @HQiang

**Comment by HQiang** [comment]
@befovy 因为我这边的需求是全屏的时候有截图功能，我直接操作的panelBuilder对应的自定义的那个Widget进行截图，它可以把我自定义的播放按钮，全屏按钮，重新刷新按钮这些截出来，但是播放器内容没得法，因为是全屏的时候截图，我就没有直接操作FijkView，周一的时候我去公司试一下操作FijkView, 但是我有预感应该也是不得行的。

**Comment by befovy** [comment]
panelBuilder 对应的自定义 Widget 是不含视频内容的，是盖在视频区域上的一块内容。
使用 RepaintBoundary 截取这个肯定是不含视频的。

另外 RepaintBoundary 是否能够对 Texture 的内容进行截图，还不清楚。有时间确认一下

**Comment by HQiang** [comment]
@befovy 对FijkView截图操作仍然不能够截取到视频的内容，Texture没暴露出来。不晓得如何操作。理论上可能也没办法，它真的只能截取到Widget

**Comment by befovy** [comment]
@HQiang 非全屏的时候可以使用 RepaintBoundary 对 FijkView 的视频播放截图吗？

**Comment by HQiang** [comment]
@befovy 我试了的，任然不行

**Comment by terry8204** [comment]
@HQiang 这个问题解决了不？我做车载视频，也需要截图保存。

**Comment by befovy** [comment]
还没有实现截图功能，完成后会在这里通知的

**Comment by terry8204** [comment]
@befovy 非常感谢，有大概计划时间不？

**Comment by qengli** [comment]
同样需要视频截图功能，非常感谢

**Comment by terry8204** [comment]
@befovy 这个功能帮忙加了不？

**Comment by befovy** [comment]
this feature has been released in version 0.8.0

**Comment by tanwanlanyue1** [comment]
大佬这个功能实现了吗

**Comment by Gaoxichao** [comment]
需要截屏和录屏功能（监控需要）
