### ISSUE TITLE
动态更改加载视频地址

### ISSUE THREAD

**Issue by cccchelly** [befovy/fijkplayer#62]
你好，我想问一下怎么在一个界面动态更改视频地址呢？
我们的视频是有清晰度1和清晰度2两种，对应两个地址。功能要求可以动态切换。

目前代码：
url = url1;
player.setDataSource(url,autoPlay: true);

然后切换的时候：
setState(() {
      url = url2;
    });

这样操作会报错：
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: setDataSource on invalid state FijkState.error
    null

请问正确的实现方式是什么呢？

**Comment by befovy** [comment]
动态切换不同的清晰度需要在传输协议和封装上下功夫， 可以等 ijkplayer 2.0 版本。 其中 dash 支持无缝切换清晰度。
https://www.bilibili.com/read/cv3901523/
目前插件功能无法做到无缝切换，只能是关闭播放器，重新启动一个。

**Comment by CaiJingLong** [comment]
> 动态切换不同的清晰度需要在传输协议和封装上下功夫， 可以等 ijkplayer 2.0 版本。 其中 dash 支持无缝切换清晰度。
> https://www.bilibili.com/read/cv3901523/
> 目前插件功能无法做到无缝切换，只能是关闭播放器，重新启动一个。

2.0 厉害了 不知道会不会开源 或者什么时候开源

**Comment by befovy** [comment]
不清楚呀，不认识 B站大神  @CaiJingLong
