### ISSUE TITLE
[BUG]直接点击播放轴，如果视频没有缓存到哪里，那么就会卡住，然后点下暂停在点播放就能了，算不算bug

### ISSUE THREAD

**Issue by songguowei** [befovy/fijkplayer#65]

**Comment by befovy** [comment]
> 直接点击播放轴，如果视频没有缓存到哪里，那么就会卡住

这样卡住之后应该是等待缓冲完毕就会继续播放，如果如你所描述，那确实算是一个bug。
请提供一下运行的日志。 @songguowei

**Comment by befovy** [comment]
@all-contributors please add @songguowei for bug

**Comment by befovy** [comment]
fixed in version 0.1.7
