### ISSUE TITLE
播放地址 final String url必须提前固定写好吗?怎么动态获取?

### ISSUE THREAD

**Issue by 718087538** [befovy/fijkplayer#66]
class VideoScreen extends StatefulWidget {
  final String url;

  VideoScreen({@required this.url});

  @override
  _VideoScreenState createState() => _VideoScreenState();
}

我在return之前调用发放修改url,但是无法播放.  写固定的url就可以播放.

十分急切,感谢,感谢.

**Comment by befovy** [comment]
VideoScreen 是example 中的代码。 播放器接口是  FijkPlayer 和 FijkView


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by befovy** [comment]
不是bug


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
