### ISSUE TITLE
横屏播放全屏后 退出全屏布局变竖屏

### ISSUE THREAD

**Issue by utoper23** [befovy/fijkplayer#73]
在安卓端会出现横屏播放，退出全屏后变为横屏的情况，IOS则不会出现

**Comment by befovy** [comment]
@utoper23 方便给个截图吗


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by befovy** [comment]
在 todo 计划中，暂时没时间。解决后再关闭。

做法是切换全屏之前，判断当前屏幕方向，如果是横屏，那么进入全屏以及退出全屏就不再切换屏幕方向了。

@utoper23 有空可以来一个 pr 吗？ 没空我就自己慢慢安排了

**Comment by befovy** [comment]
修改切换横屏方法，如果确实发生了切换操作返回 true。 如果无法切换或者本身就是横屏，返回 false。

进入全屏模式时，先切换横屏。
如果切换横屏返回true，在退出全屏时切换为竖屏。
如果切换横屏返回false，在退出全屏时不进行切换为竖屏。
