### ISSUE TITLE
[BUG]播放器在非全屏状态下设置FijkView的fit参数为FijkFit.fill，但是执行enterFullScreen()后又变为FijkFit.contain了

### ISSUE THREAD

**Issue by iperfectapp** [befovy/fijkplayer#74]
非全屏：
![C6689C2D445F37736C9E888B3D123B0F](https://user-images.githubusercontent.com/3021764/66698934-037b0200-ed15-11e9-98c4-a22cde0d0b89.png)

全屏后：
![B19DE25996BEF1B318A141AEB92D5E3F](https://user-images.githubusercontent.com/3021764/66698936-0970e300-ed15-11e9-9e10-28b43bf7c177.png)

**Comment by befovy** [comment]
这部分开始写的时候，在全屏模式就没有使用 fit 参数，而是直接使用了 contain 模式的具体内容。
看来现在这里有必要新增一个全屏模式下的 fit 参数了。

BTW，fit for fullscreen mode will be released tonight.

**Comment by befovy** [comment]
version 0.1.8 released
