### ISSUE TITLE
[BUG]把自动播放 设置false 的时候  一直是转圈圈的状态

### ISSUE THREAD

**Issue by songguowei** [befovy/fijkplayer#76]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**fijkplayer version**
Which version you used.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by befovy** [comment]
@all-contributors please add @songguowei  for bug

**Comment by befovy** [comment]
fix released at version 0.1.9
