### ISSUE TITLE
flutter 1.10 realease会闪退

### ISSUE THREAD

**Issue by utoper23** [befovy/fijkplayer#80]

**Comment by befovy** [comment]
请补充一下崩溃栈信息


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by utoper23** [comment]
java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.befovy.fijkplayer.demo-1/lib/arm/libijksdl.so"
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at java.lang.Runtime.loadLibrary(Runtime.java:372)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1076)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at tv.danmaku.ijk.media.player.e.a()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.a()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.b()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at b.b.a.b.<init>()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at b.b.a.d.a()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at c.a.c.a.a()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at com.befovy.fijkplayer.demo.MainActivity.onCreate()
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6355)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2467)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2574)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:153)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1425)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:157)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5684)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
10-21 09:14:40.963  1429  1429 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
10-21 09:14:40.969  1948  3671 W ActivityManager:   Force finishing activity com.befovy.fijkplayer.demo/.MainActivity
