### ISSUE TITLE
[BUG]播放本地視頻時影片方向錯誤

### ISSUE THREAD

**Issue by dexterliu1214** [befovy/fijkplayer#81]
播放本地視頻(例如使用豎屏拍攝)時影片方向錯誤

**Comment by befovy** [comment]
@dexterliu1214 请查看并提供一下本地视频数据的 meta 信息。这个问题可能原因是本地视频方向由 meta 中参数 rotation 控制

**Comment by befovy** [comment]
Released in version 0.2.3
