### ISSUE TITLE
Plugin not supported user-agent in some video

### ISSUE THREAD

**Issue by Ghrib-Ramadhan** [befovy/fijkplayer#83]
I have some link url m3u stream but this links play using user-agent, it's possible add user-agent to play this link.
Please I need this option because I have links url support user-agent

**Comment by befovy** [comment]
call `await setOption` before `setDataSource`.
```dart
player.setOption(FijkOption.formatCategory, "user_agent", "<your agent string>");
```

**Comment by Ghrib-Ramadhan** [comment]
setoption in class videosecreen 

import 'package:fijkplayer/fijkplayer.dart';import 'package:flutter/material.dart'; import 'app_bar.dart';// import 'custom_ui.dart'; class VideoScreen extends StatefulWidget { final String url; VideoScreen({@required this.url}); @override _VideoScreenState createState() => _VideoScreenState();} class _VideoScreenState extends State<VideoScreen> { final FijkPlayer player = FijkPlayer(); _VideoScreenState(); @override void initState() { super.initState(); 
await player.setOption(FijkOption.formatCategory, "user_agent", "<your agent string>");
player.setDataSource(widget.url, autoPlay: true).catchError((e) { FijkException fe = e as FijkException; //setState(() { // errorMsg = fe.message; //}); print("setDataSource exception: $fe"); }, test: (e) => e is FijkException); } @override Widget build(BuildContext context) { return Scaffold( appBar: FijkAppBar.defaultSetting(title: "Video"), body: Container( child: FijkVolumeWatcher( watcher: null, showToast: true, child: FijkView( player: player, // panelBuilder: simplestUI, // panelBuilder: (FijkPlayer player, BuildContext context, // Size viewSize, Rect texturePos) { // return CustomFijkPanel( // player: player, // buildContext: context, // viewSize: viewSize, // texturePos: texturePos); // }, )), ), ); } @override void dispose() { super.dispose(); player.release(); }}

**Comment by befovy** [comment]
@Ghrib-Ramadhan  please format your code using markdown ``` code section

**Comment by Ghrib-Ramadhan** [comment]
Thank you very much  it work well this method

**Comment by befovy** [comment]
You're welcome.


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
