### ISSUE TITLE
[BUG]视频不是可播放状态时，全屏不能满屏

### ISSUE THREAD

**Issue by HQiang** [befovy/fijkplayer#85]
不可播放状态指：视频加载失败，或还未加载出来的时候全屏，不能满屏

**Comment by befovy** [comment]
你好，请问使用的 fijkplayer 版本是多少

**Comment by HQiang** [comment]
最新的0.1.9

**Comment by HQiang** [comment]
我试了下的写的demo,效果也是一样的，特别说明一下我是播放的直播流媒体，不知道其他的流媒体是不是一样。视频未加载出来的时候全屏，铺不满，只有中间有，两边就是背景色

**Comment by befovy** [comment]
你说的这些情况可以截个屏看看吗


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by HQiang** [comment]
![微信截图_20191030103704](https://user-images.githubusercontent.com/13211786/67824808-5e2ca000-fb02-11e9-83de-b227984d706a.png)
![微信截图_20191030103731](https://user-images.githubusercontent.com/13211786/67824813-62f15400-fb02-11e9-87bd-0b08cb6acc87.png)
上面两张图是截取的模拟器上的图，但是真机的表现和模拟器一致
fit 参数不管是full,还是fitWidth,在视频未加载成功时，全屏都是第二张图的样子，关于播放器填充和裁剪我粗略看了下，我接下来准备自己计算，看看能否实现。

**Comment by befovy** [comment]
这个就是这样设计的。你可以强制指定  fit 参数的 ar 参数进行修改。

**Comment by HQiang** [comment]
我细看了文档，经过我的测试，似乎不管如何调整FijkFit的三个参数，全屏效果始终是居中的，并且大小也不会改变，我将FijkFit的alignment参数调整居左上，居右下以及改变aspectRatio,sizeFactor的值都对全屏无任何影响，仅对非全屏时有影响。
然后我试了下正常播放中的视频，不管FijkFit是什么，全屏都能正常铺满
所以调整FijkFit对全屏操作，是不会有任何作用的

**Comment by befovy** [comment]
全屏用的是  fsFit 参数中的值

**Comment by HQiang** [comment]
哦哦，文档中好像没有涉及fsFit,我之前都不知道有这个参数，不好意思，是我疏忽了

**Comment by HQiang** [comment]
设置fsFit为FijkFit.fill后，视频未加载成功也能够在全屏时铺满了，是我疏忽了，不好意思哈

**Comment by befovy** [comment]
😅，是我没有及时补充文档。 方便修改一下文档，贡献一个 pr 吗？ @HQiang

**Comment by HQiang** [comment]
@befovy pr是什么，闹笑话了，如果可以，我能贡献我能贡献的所有

**Comment by befovy** [comment]
“pr” 就是 pull request。github 上的一种协作方式。
先fork 仓库，然后修改代码提交，再发起 pull request 进行合并。

**Comment by HQiang** [comment]
@befovy 好的呀
