### ISSUE TITLE
希望可以实现audio focus，增加用户体验

### ISSUE THREAD

**Issue by yinlianggood** [befovy/fijkplayer#89]
希望大佬实现播放音频，暂停其它正在播放中的应用。

**Comment by befovy** [comment]
考虑实现如下：
增加一个 FijkPlayer 的设置选项，
如果选项打开后，
当播放器进入 started 状态的时候，会去申请 audioFocus。
退出 started 状态时， 释放 audioFocus。
出现 audioFocus 错误不进行处理，不判断 audioFocus 返回值。

上面实现也仅适用于 单个播放器实例，如果同时打开多个播放器，上面规则不使用。

audioFocus 怎么处理又好多情况，都涉及到产品如何决策，没办法做一个通用的，只能搞一个最简单的实现。
